.\"     Title: cifs.upcall
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/07/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"
.TH "CIFS\.UPCALL" "8" "01/07/2009" "Samba 3\.2" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
cifs.upcall - CIFSのためのユーザ空間upcallヘルパ
.SH "SYNOPSIS"
.HP 1
cifs\.upcall [\-c] [\-v] {keyid}
.SH "説明"
.PP
このツールは
\fBsamba\fR(7)システムの一部である。
.PP
cifs\.upcallは、Linux CIFSクライアントファイルシステムのための、ユーザ空間ヘルパプログラムである。kernelが簡単にそれ自身でできない、たくさんの機能がある。このプログラムは、kernelに対してそれらのことを行うcalloutプログラムであり、結果を返す。
.PP
cifs\.upcallは一般的に、kernelが特定のキータイプのために、request\-key(8)を呼び出すとき、動くつもりである。コマンドラインから直接起動できる間、その方法で動かされる事は一般的ではない。
.SH "オプション"
.PP
\-c
.RS 4
kerberosのupcallを取り扱っている間、"cifs/"で始まるサービスプリンシパルを使う。規定値は、"host/"サービスプリンシパルを使うためになっている。
.RE
.PP
\-v
.RS 4
バージョン番号を印刷して終了する。
.RE
.SH "KEYCTLのための構成方法"
.PP
cifs\.upcallはrequest\-key callout プログラム経由でkernelから呼ばれるようにデザインされている。これは、どこからと、どのようにこのプログラムを呼び出すかがrequest\-keyが語られる事を要求する。現在のcifs\.upcallプログラムは2つのキータイプを扱う:
.PP
cifs\.spnego
.RS 4
このキータイプはkerberosセッションキーを検索するためである。
.RE
.PP
dns_resolver
.RS 4
このキータイプは、ホスト名をIPアドレスに変換(解決)するためのものである。
.RE
.PP
CIFSのためにこのプログラムを使いやすくするためには、request\-key\.conf(5)中にエントリを設定する必要がある。以下はそれぞれのキータイプのためのエントリの例である:
.sp
.RS 4
.nf
#OPERATION  TYPE           D C PROGRAM ARG1 ARG2\.\.\.
#=========  =============  = = ==========================================
create	    cifs\.spnego    * * /usr/local/sbin/cifs\.upcall \-c %k
create      dns_resolver   * * /usr/local/sbin/cifs\.upcall %k
.fi
.RE
.PP
それぞれのフィールドについての詳細な情報は\fBrequest-key.conf5\fR()を参照。
.SH "参照"
.PP

\fBrequest-key.conf\fR(5),
\fBmount.cifs\fR(8)
.SH "作者"
.PP
Igor Mammedovはcifs\.upcallプログラムを書いた。
.PP
Jeff Laytonはこのマニュアルページを書いた。
.PP
Linux CIFS VFSのメンテナはSteve Frenchである。
.PP
Linux CIFSメーリングリストは、これらのプログラムに対して質問をする事に好まれる場所である。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.2\.4\-3\.2\.7 対応のものである。
.PP
このドキュメントの Samba 3\.2\.4\-3\.2\.7 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉(ribbon@samba\.gr\.jp)
.sp
.RE
によって行なわれた。
