'\" t
.\"     Title: cifs.upcall
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/16/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.5
.\"  Language: English
.\"
.TH "CIFS\&.UPCALL" "8" "11/16/2010" "Samba 3\&.5" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cifs.upcall \- CIFSのためのユーザ空間upcallヘルパ
.SH "SYNOPSIS"
.HP \w'\ 'u
cifs\&.upcall [\-\-trust\-dns|\-t] [\-\-version|\-v] {keyid}
.SH "説明"
.PP
このツールは
\fBsamba\fR(7)システムの一部である。
.PP
cifs\&.upcallは、Linux CIFSクライアントファイルシステムのためのユーザ空間ヘルパプログラムである。kernelがそれ自身では簡単にはできないような、さまざまな機能をkernelに代わって行う。このプログラムはkernelから呼び出されてこれらの機能を実行し、その結果を(kernelに)返す。
.PP
cifs\&.upcallはほとんどの場合、kernelがrequest\-key(8)で特定のキータイプを呼び出す際に実行されることを想定して作られている。コマンドラインから直接起動できるようにはなっているものの、その方法で呼び出される事は基本的に想定していない。
.SH "オプション"
.PP
\-c
.RS 4
このオプションは廃止予定で、現在は無視される。
.RE
.PP
\-\-trust\-dns|\-t
.RS 4
krb5 upcallと一緒に、サービスプリンシパルのホスト部として使われる名前は、UNCのホスト名の部分が初期値となる。このオプションは、ホスト名を得るためにサーバのネットワークアドレスを逆引きすることをupcallプログラムに許可する。
.sp
これは、信頼しているDNSよりもセキュアでない。このオプションを使うとき、アタッカがDNSを乗っ取り、まったく異なったサーバにクライアントがマウントするような偽装をすることが可能になる。代わりにすべての考えうるホスト名に対してサーバプリンシパルをKDCに追加する事が望ましいが、このオプションはそれが不可能な時のために存在している。既定値はこの形式でのホスト名の逆引きを信頼しない。
.RE
.PP
\-\-version|\-v
.RS 4
バージョン番号を表示して終了する。
.RE
.SH "KEYCTLのための構成方法"
.PP
cifs\&.upcallは、request\-key callout プログラム経由でkernelから呼ばれるようにデザインされている。このため、request\-keyに対して、どこから、どのようにこのプログラムを呼び出すかを指示してやらなければならない。現在のcifs\&.upcallプログラムは2つのキータイプを扱う:
.PP
cifs\&.spnego
.RS 4
このキータイプはkerberosセッションキーを検索する。
.RE
.PP
dns_resolver
.RS 4
このキータイプは、ホスト名をIPアドレスに変換(解決)する。
.RE
.PP
CIFSがこのプログラムを便利に使えるように、request\-key\&.conf(5)中にエントリを設定する必要がある。以下はそれぞれのキータイプのためのエントリの例である:
.sp
.if n \{\
.RS 4
.\}
.nf
#OPERATION  TYPE           D C PROGRAM ARG1 ARG2\&.\&.\&.
#=========  =============  = = ================================
create      cifs\&.spnego    * * /usr/local/sbin/cifs\&.upcall %k
create      dns_resolver   * * /usr/local/sbin/cifs\&.upcall %k
.fi
.if n \{\
.RE
.\}
.PP
それぞれのフィールドについての詳細は\fBrequest-key.conf5\fR()を参照のこと。
.SH "参照"
.PP

\fBrequest-key.conf\fR(5),
\fBmount.cifs\fR(8)
.SH "著者"
.PP
Igor Mammedovはcifs\&.upcallプログラムを書いた。
.PP
Jeff Laytonはこのマニュアルページを書いた。
.PP
Linux CIFS VFSのメンテナはSteve Frenchである。
.PP
Linux CIFSメーリングリストは、これらのプログラムに対して質問をするのにふさわしい場所である。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.4\&.3\-3\&.5\&.6 対応のものである。
.PP
このドキュメントの Samba 3\&.2\&.4\-3\&.5\&.6 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉(ribbon@samba\&.gr\&.jp)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\&.com)
.sp
.RE
によって行なわれた。
