'\" t
.\"     Title: eventlogadm
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 06/30/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.5
.\"  Language: English
.\"
.TH "EVENTLOGADM" "8" "06/30/2010" "Samba 3\&.5" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
eventlogadm \- Samba のイベントログ格納領域にレコードを書き込む
.SH "SYNOPSIS"
.HP \w'\ 'u
eventlogadm [\fB\-d\fR] [\fB\-h\fR] \fB\-o\fR\ addsource\ \fIEVENTLOG\fR\ \fISOURCENAME\fR\ \fIMSGFILE\fR
.HP \w'\ 'u
eventlogadm [\fB\-d\fR] [\fB\-h\fR] \fB\-o\fR\ write\ \fIEVENTLOG\fR
.HP \w'\ 'u
eventlogadm [\fB\-d\fR] [\fB\-h\fR] \fB\-o\fR\ dump\ \fIEVENTLOG\fR\ \fIRECORD_NUMBER\fR
.SH "説明"
.PP
このツールは
\fBsamba\fR(1)
の一部として提供されている。
.PP
eventlogadm
は特定の形式に従ったイベントログのレコードを標準入力から読み込み、 それらを Samba のイベントログ格納領域に書き込む。こうすることで、 Windows クライアントから通常の管理ツールを使ってこれらのレコードを 操作できるようになる。
.SH "オプション"
.PP
\fB\-d\fR
.RS 4

\-d
オプションを指定すると、
eventlogadmはデバッグ情報を出力する。
.RE
.PP
\fB\-o\fR addsource \fIEVENTLOG\fR \fISOURCENAME\fR \fIMSGFILE\fR
.RS 4

\-o addsource
オプションは、新しいイベントログの ソースを生成する。
.RE
.PP
\fB\-o\fR write \fIEVENTLOG\fR
.RS 4

\-o write
はイベントログのレコードを標準入力から 読み込み、それらを EVENTLOG で指定された名前の Samba のイベントログ 格納領域に書き込む。
.RE
.PP
\fB\-o\fR dump \fIEVENTLOG\fR \fIRECORD_NUMBER\fR
.RS 4

\-o dumpは、EVENTLOG tdbからのイベントログレコードを 読み、画面上の標準出力にそれをダンプする。
.RE
.PP
\fB\-h\fR
.RS 4
使用法を表示する
.RE
.SH "EVENTLOG レコードフォーマット"
.PP
書き込みの際、eventlogadm
は標準入力から書式に従ったレコードが読み込めることを期待している。 これらのレコードは、レコードキーとデータがコロン(:)で区切られた 行の並びである。各レコードは、少なくとも１個以上の空行で区切られている 必要がある。
.PP
イベントログのフィールドは以下の通り:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

LEN
\-
eventlogadm
はこの フィールドの値を自動計算するので、このフィールドには 0 をセットする。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

RS1
\- 1699505740 という値をセットする。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

RCN
\- 0 をセットする。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

TMG
\- イベントログが生成された時刻。 00:00:00 January 1, 1970, UTC からの 累積秒数をセットする。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

TMW
\- イベントログが書き込まれた時刻。 00:00:00 January 1, 1970, UTC からの 累積秒数をセットする。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

EID
\- イベントログ ID
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

ETP
\- イベントログのタイプで、以下のいずれか： "INFO", "ERROR", "WARNING", "AUDIT SUCCESS" or "AUDIT FAILURE"\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

ECT
\- イベントカテゴリ：これはマシンファイルに依存する。 主にイベントビューワ－におけるフィルタ条件として使われる。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

RS2
\- 0 をセットする。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

CRN
\- 0 をセットする。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

USL
\- 0 をセットする。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

SRC
\- このフィールドはイベントログに関連付けられるソースを指定する。 イベントログとしてメッセージファイルが指定された場合、 メッセージファイルの DLL に対してこのソース名が関連付けられた レジストリーエントリーがあるはずである。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

SRN
\- イベントログが生成されたマシンの名前。これは通常ホスト名となる。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

STR
\- イベントログに関連付けられたテキスト。 １つのレコードに複数の文字列を持つこともできる。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

DAT
\- このフィールドはセットしないようにする。
.SH "記述例"
.PP

eventlogadm
で認識できるレコードフォーマットの例：
.sp
.if n \{\
.RS 4
.\}
.nf
	LEN: 0
	RS1: 1699505740
	RCN: 0
	TMG: 112863\&.3\&.6
	TMW: 112863\&.3\&.6
	EID: 1000
	ETP: INFO
	ECT: 0
	RS2: 0
	CRN: 0
	USL: 0
	SRC: cron
	SRN: dmlinux
	STR: (root) CMD ( rm \-f /var/spool/cron/lastrun/cron\&.hourly)
	DAT:
	
.fi
.if n \{\
.RE
.\}
.PP
メッセージファイルの DLL を指定して、イベントログのソースをセットする：
.sp
.if n \{\
.RS 4
.\}
.nf
	eventlogadm \-o addsource Application MyApplication | \e\e
	    	%SystemRoot%/system32/MyApplication\&.dll
	
.fi
.if n \{\
.RE
.\}
.PP
システムログからのフィルターメッセージをイベントログとして指定する：
.sp
.if n \{\
.RS 4
.\}
.nf
	tail \-f /var/log/messages | \e\e
		入力をパースしてイベントログのレコードにするプログラム | \e\e
	      	eventlogadm SystemLogEvents
	
.fi
.if n \{\
.RE
.\}
.SH "バージョン"
.PP
このマニュアルは Samba スイートのバージョン 3\&.0\&.25 に適合する。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアおよび関連するユーティリティーは、 Andrew Tridgell によって書かれた。現在は Samba は Samba Team によって Linux カーネルの開発と同様に、オープンソースプロジェクトとして 開発されている。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.5\&.0 \- 3\&.5\&.4 対応のものである。
.PP
このドキュメントの Samba 3\&.2\&.4 \- 3\&.5\&.4 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\&.com)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉(ribbon@samba\&.gr\&.jp)
.sp
.RE
によって行なわれた。
