'\" t
.\"     Title: idmap_adex
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/02/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"  Language: English
.\"
.TH "IDMAP_ADEX" "8" "03/02/2010" "Samba 3\&.3" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
idmap_adex \- Samba の Winbind 用 idmap_adex バックエンド
.SH "説明"
.PP
idmap_adex プラグインは、RFC2307 スキーマ拡張を使った AD サーバから Winbind が id のマッピング情報を読み込むための手段を提供する。この モジュールでは idmap と nss_info API の両方を実装しており、ドメイン 信頼に加えて双方向のクロスフォレスト信頼をサポートしている。AD の users と groups オブジェクトに POSIX 属性情報を追加することで、 あらかじめ管理者が提供するマッピング情報を要求するリードオンリー プラグインとなっている。これを使う一番の目的は、Windows 2003 R2 以降で "Identity Services for Unix" を使うことにある。
.PP
注意：対象フォレストのグローバルカタログサーバの部分属性に、uidNumber, gidNumber, uid 属性を追加しなければならないことに注意してほしい。 この作業を行うには、Active Directory スキーマ管理 MMC プラグイン (schmmgmt\&.dll)を使う。
.SH "NSS_INFO"
.PP
nss_info プラグインは、user オブジェクトから unixHomeDirectory, gidNumber, loginShell, uidNumber 属性を、group オブジェクトから gidNumber 属性を読み取って、libc の getpwnam() と getgrnam() ファミリー関数が要求する情報を提供する。グループのメンバーシップは、 msSFU30PosixMember 属性ではなく Windows の group メンバーシップ に従って提供される。
.PP
ユーザの別名は、user オブジェクトに uid 属性をセットすることで 実装されている。一方、グループの別名は group オブジェクトの displayname 属性を読むという方法で実装されている。
.SH "設定例"
.PP
以下の例では、私たちのプリンシパルと信頼された AD ドメインから id のマッピング情報と NSS データを取り出す方法について示している。
.sp
.if n \{\
.RS 4
.\}
.nf
	[global]
	idmap backend = adex
	idmap uid = 1000\-4000000000
	idmap gid = 1000\-4000000000

	winbind nss info = adex
	winbind normalize names = yes
	
.fi
.if n \{\
.RE
.\}
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連ユーティリティは、Andrew Tridgell により書かれた。Samba は現在 Samba チームの元で、Linux のカーネルと 同様にオープンソースソフトウェアとして開発されている。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.3\&.2\-3\&.3\&.10 対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\&.com)
.sp
.RE
によって行なわれた。
