'\" t
.\"     Title: idmap_rid
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 01/25/2011
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.4
.\"  Language: English
.\"
.TH "IDMAP_RID" "8" "01/25/2011" "Samba 3\&.4" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
idmap_rid \- SambaのWinbind用idmap_ridバックエンド
.SH "説明"
.PP
idmap_rid バックエンドは、UID や GID と SID を対応付けるための 方法のひとつとして、アルゴリズム的なマッピングの仕組みを提供する。 このケースでは決定論的なマッピングを行うため、データベースを必要 としない。
.SH "IDMAP オプション"
.PP
range = low \- high
.RS 4
バックエンドが権威を持つと規定されている、uid と gid の利用可能な マッチング範囲を定義する。この範囲はフィルターとして動作することに 注意されたい。UID と GID の計算結果がアルゴリズム的にこの範囲外 になってしまった場合、これらは無視され、対応するマップは破棄される。 このオプションは、UID や GID がたまたまローカルとリモートでそれぞれ 定義された ID と重複してしまうのを避けるために用意されている。
.RE
.PP
base_rid = 数字
.RS 4
UID や GID から SID を生成したり、取得したSID から UID や GID を 求めたりするためのベースとなる整数を指定する。 これは、base ridよりも小さい、RIDベースのSIDがフィルタされることを 意味する。既定値は許されているRIDに制限されておらず、すなわち、 base_rid の値は0である。base_ridの好ましい値は 1000 とすることが でき、これによりユーザ RIDは1000から始まる(16進で512:訳注間違い?)。
.RE
.SH "マッピング形式"
.PP
RID用のUnix IDは以下の方法で計算される:
.sp
.if n \{\
.RS 4
.\}
.nf
                        ID = RID \- BASE_RID + LOW_RANGE_ID\&.
                
.fi
.if n \{\
.RE
.\}
.PP
それに対応して、与えられたUnix IDからRIDを計算する方法は下記の通り:
.sp
.if n \{\
.RS 4
.\}
.nf
                        RID = ID + BASE_RID \- LOW_RANGE_ID\&.
                
.fi
.if n \{\
.RE
.\}
.sp
.SH "使用例"
.PP
この例では idmap_rid で２つのドメインを設定し、それは、 基本的なドメインと信頼するドメインであり、tdbへの既定値の idマッピングスキームを残してある。この例はまた、信頼する ドメインに対してのbase_ridパラメータの使用方法も説明している。
.sp
.if n \{\
.RS 4
.\}
.nf
	[global]
	security = domain
	workgroup = MAIN

        idmap backend = tdb
        idmap uid = 1000000\-1999999
        idmap gid = 1000000\-1999999

        idmap config MAIN : backend     = rid
        idmap config MAIN : range       = 10000 \- 49999

        idmap config TRUSTED : backend  = rid
        idmap config TRUSTED : range    = 50000 \- 99999
        idmap config TRUSTED : base_rid = 1000
	
.fi
.if n \{\
.RE
.\}
.SH "著者"
.PP
オリジナルの Samba ソフトウェアとそれに関連するユーティリティーは、 Andrew Tridgell によって作られた。Samba は現在、Linux カーネル開発と 同様の方法で、Samba Team によりオープンソースプロジェクトとして 開発されている。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.4\&.0 \- 3\&.4\&.11 対応のものである。
.PP
このドキュメントの Samba 3\&.4\&.0 \- 3\&.4\&.11 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\&.com)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉(ribbon@samba\&.gr\&.jp)
.sp
.RE
によって行なわれた。
