'\" t
.\"     Title: idmap_tdb2
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 01/25/2011
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.4
.\"  Language: English
.\"
.TH "IDMAP_TDB2" "8" "01/25/2011" "Samba 3\&.4" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
idmap_tdb2 \- Samba の Winbind 用 idmap_tdb2 バックエンド
.SH "説明"
.PP
idmap_tdb2 プラグインはデフォルトの idmap_tdb バックエンドの代替と なるもので、Samba と CTDB におけるクラスタ環境において winbindd が SID/uid/gid の対応表を格納するのに使われる。
.PP
idmap_rid のようなバックエンドはリードオンリーであるが、これは 割り当て機能を持つバックエンドだと言える。つまり、新しいマッピング を生成するために、新しいユーザやグループの ID を割り当てる必要が あるということである。(割り当てを受け持つ)アロケータを idmap_tdb2 バックエンド自身が担当することもできるし、idmap_tdb や idmap_ldap といった他のバックエンドにその処理を依頼することもできる。この機能は
\fIidmap alloc backend\fR
パラメータにより有効となる。
.PP
注意：この(もしくは他のアロケータとなりうる)バックエンドで本機能が 動作するためには、デフォルトのバックエンドが書き込み可能でなければ ならない。uid と gid の割り当てに使われる範囲は、"idmap uid" と "idmap gid" で構成されるデフォルトの範囲が使われる。
.PP
さらに、書き込み可能な idmap バックエンドを使うすべてのドメインの ために、割り当てを実行できる唯一のグローバルなバックエンドがあるので、 明示的に tdb2 の idmap バックエンドで構成されたドメインは、 同じ範囲をデフォルトの範囲として持つべきである。つまり、グローバルの uid / gid アロケータを使用する必要がある。以下の例を見て欲しい。
.SH "IDMAP オプション"
.PP
range = low \- high
.RS 4
バックエンドが割り当て権限を持っていて、かつ利用可能な uid と gid の範囲を定義する。このパラメータが指定されない場合 winbind は フェイルオーバーして、smb\&.conf の "idmap uid" と "idmap gid" オプションを使う。
.RE
.SH "IDMAP スクリプト"
.PP
tdb2 idmap バックエンドは、id のマッピングをスクリプトで実行するための smb\&.conf の
\fIidmap : script\fR
オプションをサポート している。このスクリプトは、以下のコマンドラインオプションを受け付ける ようになっていなければならない。
.sp
.if n \{\
.RS 4
.\}
.nf
	SIDTOID S\-1\-xxxx
	IDTOSID UID xxxx
	IDTOSID GID xxxx
	
.fi
.if n \{\
.RE
.\}
.PP
またそのスクリプトは、以下のいずれかのレスポンスを１行で返すように なっている必要がある。
.sp
.if n \{\
.RS 4
.\}
.nf
	UID:yyyy
	GID:yyyy
	SID:yyyy
	ERR:yyyy
	
.fi
.if n \{\
.RE
.\}
.PP
注意：SID を UNIX の ID マッピングに対して渡すにあたり、このスクリプトは SID の全範囲をカバーするべきである。そうでないと、スクリプトではカバー されていない SID が、すでにスクリプトで割り当て済みの ID に割り当てられる 恐れがある。
.SH "設定例"
.PP
tdb2 がどのようにデフォルトの imapd バックエンドとして使われるかという 例を以下に示す。全ドメインについて適用されるグローバルオプションで idmap の範囲を設定していることがわかる。これと同じ範囲が uid/gid の割り当て の際に使われる。
.sp
.if n \{\
.RS 4
.\}
.nf
	[global]
	idmap backend = tdb2
	idmap uid = 1000000\-2000000
	idmap gid = 1000000\-2000000
	
.fi
.if n \{\
.RE
.\}
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連ユーティリティは、Andrew Tridgell により書かれた。Samba は現在 Samba チームの元で、Linux のカーネルと 同様にオープンソースソフトウェアとして開発されている。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.3\&.6\-3\&.4\&.11 対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\&.com)
.sp
.RE
によって行なわれた。
