.\"     Title: ldbadd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 08/13/2009
.\"    Manual: ユーザコマンド
.\"    Source: Samba 3.2
.\"
.TH "LDBADD" "1" "08/13/2009" "Samba 3\.2" "ユーザコマンド"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ldbadd - LDB にレコードを追加するためのユーザーコマンド
.SH "SYNOPSIS"
.HP 1
ldbadd [\-h] [\-H\ LDB\-URL] [ldif\-file1] [ldif\-file2] [\.\.\.]
.SH "説明"
.PP
ldbadd は ldb(7) データベースにレコードを追加する。ldbadd はコマンドライン で指定された ldif(5) ファイルを読み、これらのファイルから取り出した レコードを LDB データベースに追加する。LDB データベースは \-H オプション かまたは LDB_URL 環境変数により指定する。
.PP
ldif の入力を標準入力から行う場合、ldb ファイルとして \- を指定する。
.SH "オプション"
.PP
\-h
.RS 4
使用可能なオプションの一覧を表示する
.RE
.PP
\-H <ldb\-url>
.RS 4
接続先 LDB の URL。詳細は ldb(7) を参照のこと。
.RE
.SH "環境変数"
.PP
LDB_URL
.RS 4
接続先 LDB の URL（ \-H コマンドラインオプションで 上書きできる）
.RE
.SH "バージョン"
.PP
このマニュアルは Samba スイートのバージョン 4\.0 に適合する。
.SH "関連衡目"
.PP
ldb(7), ldbmodify, ldbdel, ldif(5)
.SH "著者"
.PP
ldb は
Andrew Tridgell
によって書かれた。
.PP
問題を報告したり何らかの提案をしたい場合は、
: http://ldb.samba.org/
Web サイトで現在の連絡先と メンテナー情報を確認してほしい。
.PP
このマニュアルページは Jelmer Vernooij により書かれた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.2\.4\-3\.2\.14 対応のものである。
.PP
このドキュメントの Samba 3\.2\.4\-3\.2\.14 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\.com)
.sp
.RE
によって行なわれた。
