'\" t
.\"     Title: ldbmodify
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/16/2010
.\"    Manual: ユーザコマンド
.\"    Source: Samba 3.5
.\"  Language: English
.\"
.TH "LDBMODIFY" "1" "11/16/2010" "Samba 3\&.5" "ユーザコマンド"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ldbmodify \- LDB データベース中のレコードを修正する。
.SH "SYNOPSIS"
.HP \w'\ 'u
ldbmodify [\-H\ LDB\-URL] [ldif\-file]
.SH "説明"
.PP
ldbmodify は LDB データベース中のレコードを変更／追加／削除する。 変更内容は指定された LDIF ファイルから読み込まれ、LDB データベースに反映 される。ファイル名として \- が指定されると、入力データは標準入力から 読み込まれる。
.PP
LDIF ファイルフォーマットの詳細は ldapmodify(1) を参照のこと。
.SH "オプション"
.PP
\-H <ldb\-url>
.RS 4
接続先 LDB の URL。詳細は ldb(7) を参照のこと。
.RE
.SH "環境変数"
.PP
LDB_URL
.RS 4
接続先 LDB の URL（ \-H コマンドラインオプションで上書きできる）
.RE
.SH "バージョン"
.PP
このマニュアルは Samba スイートのバージョン 4\&.0 に適合する。
.SH "関連項目"
.PP
ldb(7), ldbedit
.SH "著者"
.PP
ldb は
Andrew Tridgell
によって書かれた。
.PP
問題を報告したり何らかの提案をしたい場合は、
: http://ldb.samba.org/
Web サイトで現在の連絡先と メンテナー情報を確認してほしい。
.PP
このマニュアルページは Jelmer Vernooij により書かれた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.2\&.4 \- 3\&.5\&.6 対応のものである。
.PP
このドキュメントの Samba 3\&.2\&.4 \- 3\&.5\&.6 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\&.com)
.sp
.RE
によって行なわれた。
