'\" t
.\"     Title: libsmbclient
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2010
.\"    Manual: 7
.\"    Source: Samba 3.5
.\"  Language: English
.\"
.TH "LIBSMBCLIENT" "7" "11/12/2010" "Samba 3\&.5" "7"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
libsmbclient \- ネットワークブラウザのための拡張ライブラリであり、一般的なブラウジングの API を実装する。
.SH "SYNOPSIS"
.HP \w'\ 'u
.PP
Browser URL:
smb://[[[domain:]user[:password@]]server[/share[/path[/file]]]] [?options]
.SH "説明"
.PP
このツールは
\fBsamba\fR(7)システムの一部である。
.PP

libsmbclientは、ローカルなUNIX/Linuxファイルを操作するために有効なたくさんの標準POSIX関数を使う CIFS/SMBネットワークリソースを操作するためのアプリケーションを許可するライブラリツールセットである。これは、ブラウズ、 ファイルのオープン/クローズ、読み書き、アクセス権変更、ファイルの時刻変更、属性とACLの操作やその他などを許可する。もちろん、 この機能は一般的にブラウジングと呼ばれる機能のすべてを含む。
.PP

libsmbclient
は、コマンド行からは直接使えないが、その代わりに、ファイルマネージャとブラウザのような ツールの機能の拡張を提供する。このマニュアルページにはそのツールのための構成方法を説明するので、ユーザーはとても優れた機能を 持つユーティリティを得ることができる。
.SH "オプション"
.PP
URLの意味は以下のとおり:
.PP
smb://
.RS 4
ネットワーク中で有効なすべてのワークグループかドメインを表示する。動作はマイクロソフトのWindows エクスプローラと一致する。
.sp
ワークグループ(とドメインも)のリストを位置付ける方法は、(context\->options\&.browse_max_lmb_count)
コンテキスト変数の設定方法に依存して変わる。これは,これを賢明な値に設定する、ライブラリを呼び出すアプリケーションの レスポンス性である。これはコンパイル時オプションである。この値はワークグループのリスト問い合わせのために ローカルマスタブラウザの最大値を決める。それを確かにするために、存在するネットワーク上でリストは完全にされ、 すべてのマスタブラウザは問い合わせを受けなければならない。もしも、ネットワーク上に大量のワークグループがあると、 問い合わせ時間はとても大きくなる。小さなネットワーク(数個のワークグループ)のためには、この値を0に設定することを 推奨し、それはlibsmbclientにすべてのローカルマスタブラウザに問い合わせを行うようにさせる。たくさんのワーク グループを持つ環境中では、より適切な設定は3のあたりである。
.RE
.PP
smb://name/
.RS 4
このコマンドは名前検索の実行をlibsmbclientにさせる。もしも、NAME<1D>かNAME<1B> が存在するならば(ワークグループ名)、libsmbclientはワークグループ(またはドメイン)中のすべての サーバをリストする。それ以外は、NAME<20>(マシン名)のための名前検索が実行され、サーバ上の 共有リソースのリストが表示される。
.RE
.PP
libsmbclientがアプリケーションによって起動されたならば、ユーザのシェル環境中で指定された$HOME ディレクトリ 中にある、\&.smbと呼ばれるディレクトリを探す。次に、
smb\&.conf
というファイルを探し、存在すれば、システムの/etc/samba/smb\&.confファイルを完全に 上書きする。もしも、その代わりに~/\&.smb/smb\&.conf\&.appendというファイルをlibsmbclient が見つけたならば、システムの/etc/samba/smb\&.confファイルを読み込み、次に、
~/\&.smb/smb\&.conf\&.appendの内容を継ぎ足す。
.PP

libsmbclient
は、
USERパラメータのためにユーザのシェル環境をチェックし、 もしもuserパラメータがURLに含まれていないならば、その値を使う。
.SH "プログラマーズガイド"
.PP
将来の更新のためにこの場所をウォッチして欲しい。
.SH "バージョン"
.PP
このマニュアルページはSamba3\&.0スイートのために修正された。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作られた。Samba は現在、Linux カーネルが開発されているような方法でのオープンソースプロジェクトである Samba Team によって開発されている。
.PP
libsmbclient のマニュアルページは John H Terpstra によって書かれた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.2\&.4 \- 3\&.5\&.6 対応のものである。
.PP
Samba 3\&.0\&.23 \- Samba 3\&.0\&.24 対応の翻訳は、たかはしもとのぶ (monyo@samba\&.gr\&.jp) によって行なわれた。
.PP
Samba 3\&.2\&.4 \- 3\&.5\&.6 対応の翻訳は、
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉(ribbon@samba\&.gr\&.jp)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\&.com)
.sp
.RE
によって行なわれた。
