.\"     Title: nmbd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/07/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"
.TH "NMBD" "8" "01/07/2009" "Samba 3\.2" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
nmbd - NetBIOS over TCP/IP クライアントへの NetBIOS ネームサーバ機能の提供
.SH "SYNOPSIS"
.HP 1
nmbd [\-D] [\-F] [\-S] [\-a] [\-i] [\-o] [\-h] [\-V] [\-d\ <debug\ level>] [\-H\ <lmhosts\ file>] [\-l\ <log\ directory>] [\-p\ <port\ number>] [\-s\ <configuration\ file>]
.SH "説明"
.PP
このプログラムは
\fBsamba\fR(7)
システムの一部である。
.PP
nmbd
は、Windows95/98/Me、 Windows NT、Windows XP や LanManager クライアントなどの SMB/CIFS クライアントによる NetBIOS over TCP/IP のネームサービスのリクエストを認識し、 応答することができるサーバである。 また、Windows の「ネットワークコンピュータ」 で表示されるコンピュータの一覧を 作り出すブラウジングのプロトコルにも対応している。
.PP
SMB/CIFS クライアントは、起動時に SMB/CIFS サーバを探索し、 サーバが用いている IP アドレスを確認しようとする。
.PP
サービスの中でもとりわけ
nmbd
は、 そのようなリクエストを監視し、自分の NetBIOS 名が指定されたなら、 自身の IP アドレスを返答する。 「自分の NetBIOS 名」は、 既定値では動作しているホストのプライマリDNS 名であるが、 これは
\fIsmb\.conf\fR
の
\fInetbios name\fR
によって変更可能である。 このように
nmbd
は、 自分の名前(復数の場合もある)を、 ブロードキャストの問い合わせに対して返答する。nmbd が返す追加の名前を、
\fBsmb.conf\fR(5)
設定ファイル中のパラメータで設定することができる。
.PP
nmbd
は、WINS (Windows Internet Name Service) サーバとしても利用できる。 基本的にこれが意味することは、WINS データベースサーバとして、 受け取った名前登録要求からデータベースを構築でき、 またクライアントからの名前の問い合わせに応答することができるということである。
.PP
さらに
nmbd
は、WINS proxy として動作でき、 WINS サーバに対して WINS プロトコルで交信することができないクライアントからの、 ブロードキャスト要求を中継することができる。
.SH "オプション"
.PP
\-D
.RS 4
このパラメータが指定されると、nmbd
はデーモンとして動作する。 すなわち、自分自身を分離してバックグラウンドで動作し、適切なポートのリクエストを処理する。 既定では、nmbd
はデーモンとして動作しない。 推奨しないが、nmbd は
inetd
からのメタ・デーモンとしても動作可能である。
.RE
.PP
\-F
.RS 4
このパラメータを指定すると、
nmbd
のメインプロセスはデーモン化しなくなる。 つまり、 2 回の
fork(2)
と端末からの切り離しを行なわない。 通常通り接続要求を処理するための子プロセスが生成されるが、 メインプロセスは終了しない。 この動作方式は、 Daniel J\. Bernstein 作の
daemontools
パッケージに含まれる
supervise
と
svscan
や、 AIX のプロセスモニターなど、プロセス監視の下で
nmbd
を動作させるのに都合がよい。
.RE
.PP
\-S
.RS 4
このパラメータが指定されると、nmbd
は ファイルではなく標準出力にログを出力する。
.RE
.PP
\-i
.RS 4
このパラメータが指定されると、 サーバがシェルのコマンドライン上から起動されてもサーバはデーモンとはならずに「対話的に」動作する。 このパラメータにより、コマンドラインから起動した際に暗黙的にデーモンモードとなることが抑止される。 また、\fB\-S\fR
パラメータが指定されていたとしても、
nmbd
は標準出力にログを出力する。
.RE
.PP
\-h|\-\-help
.RS 4
Print a summary of command line options\.
.RE
.PP
\-H <filename>
.RS 4
NetBIOS lmhosts ファイルの指定。lmhosts ファイルは、 NetBIOS 名と IP アドレスの組で構成されるリストである。 これは、nmbd サーバによってロードされ、任意の NetBIOS 名を解決する問い合わせのために、
\fBsmb.conf\fR(5)中で記述されている、
\fIname resolve order\fR
名前解決メカニズムに従って、サーバが必要とする NetBIOS 名の問い合わせを解決するために使われる。 このファイルの内容は、
nmbd
が、 任意の名前問い合わせに応答する時には\fI決して使われない\fRことに注意。 このファイルに行を追加すると、 このホストからの NetBIOS 解決に\fIのみ\fR影響する。
.sp
このファイルへの既定値のパス名は、 Samba をビルドする過程でバイナリに埋め込まれる。 共通のデフォルト値は、
\fI/usr/local/samba/lib/lmhosts\fR、
\fI/usr/samba/lib/lmhosts\fR
または
\fI/etc/samba/lmhosts\fR
である。 このファイルの内容の詳細は、
\fBlmhosts\fR(5)
マニュアルページを参照のこと。
.RE
.PP
\-V
.RS 4
Prints the program version number\.
.RE
.PP
\-s <configuration file>
.RS 4
The file specified contains the configuration details required by the server\. The information in this file includes server\-specific information such as what printcap file to use, as well as descriptions of all the services that the server is to provide\. See
\fIsmb\.conf\fR
for more information\. The default configuration file name is determined at compile time\.
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
Base directory name for log/debug files\. The extension
\fB"\.progname"\fR
will be appended (e\.g\. log\.smbclient, log\.smbd, etc\.\.\.)\. The log file is never removed by the client\.
.RE
.PP
\-p <UDP port number>
.RS 4
UDP ポート番号には正の整数を指定する。 このオプションは、nmbd
が名前問い合わせに返答する、 既定値の UDP ポート番号(通常は137)を変更する。 あなたがどんな場面でも助けを必要としない専門家でない限り、 このオプションを使用してはならない!
.RE
.SH "関連ファイル"
.PP
\fI/etc/inetd\.conf\fR
.RS 4
サーバが
inetd
メタ・デーモン経由で動作しているならば、このファイルは メタ・デーモンのための適切な起動情報を含む必要がある。
.RE
.PP
\fI/etc/rc\fR
.RS 4
(またはシステムが使う初期化スクリプト)
.sp
サーバをデーモンとして起動させるならば、 このファイルにサーバに応じた適切なスタートアップ 手順を含む必要がある。
.RE
.PP
\fI/etc/services\fR
.RS 4
サーバを
inetd
メタ・デーモン経由で起動させるなら、このファイルにサービス名 (例えば netbios\-ssn)とサービスポート(例えば139)、 プロトコルタイプ(例えば tcp)のマッピングを含んでいなければいけない。
.RE
.PP
\fI/usr/local/samba/lib/smb\.conf\fR
.RS 4
これは、
\fBsmb.conf\fR(5)
のデフォルトの位置である。 本ファイルのこれ以外の標準的なインストール位置は、
\fI/usr/samba/lib/smb\.conf\fR
と
\fI/etc/samba/smb\.conf\fR
である。
.sp
WINS サーバとして動作させるなら (\fBsmb.conf\fR(5)
マニュアルページの
\fIwins support\fR
パラメータを参照)、
nmbd
は、Samba がインストールされた場所の下に作成される
\fIvar/locks\fR
ディレクトリ中の
\fIwins\.dat\fR
ファイルに WINS データベースを格納する。
.sp
nmbd
が
\fI ブラウズマスタ\fR
(
\fBsmb.conf\fR(5)
マニュアルページの
\fIlocal master\fR
パラメータを参照) として動作している場合、
nmbd
は、Samba がインストールされた場所の下に作成される
\fIvar/locks\fR
ディレクトリ中の
\fIbrowse\.dat\fR
ファイルにブラウジングのデータベースを格納する。
.RE
.SH "シグナル"
.PP
nmbd
プロセスをシャットダウンするために、 SIGKILL(\-9) を使用した場合、 名前データベースが整合性の崩れた状態で残ってしまう可能性があるため、 最後の手段として以外には
\fI決して\fR推奨しない。 正しい方法は、SIGTERM(\-15) を送り、nmbd
が自ら終了するまで待つことである。
.PP
nmbd
が SIGHUP を受け取ると、名前の一覧を
\fI/usr/local/samba/var/locks\fR
ディレクトリ (または Samba 自身がインストールされた場所の配下に作成される
\fIvar/locks\fR
ディレクトリ)中のファイル
\fInamelist\.debug\fR
にダンプする。 同様に nmbd はサーバデータベースを
\fIlog\.nmb\fR
ファイルにダンプする。
.PP
\fBsmbcontrol\fR(1)
を使うと nmbd のデバッグ・ログ・レベルを上げたり下げたりできる (SIGUSR[1|2] シグナルは Samba 2\.2 からもはや使用されていない)。 これにより、通常は低いログ・レベルで動作させた状態で、 一時的な問題を診断することができる。
.SH "バージョン"
.PP
この man ページは、Samba システムのバージョン 3 用になっている。
.SH "関連項目"
.PP

\fBinetd\fR(8)、
\fBsmbd\fR(8)、
\fBsmb.conf\fR(5)、
\fBsmbclient\fR(1)、
\fBtestparm\fR(1)、
\fBtestprns\fR(1)、 Internet RFC の
\fIrfc1001\.txt\fR、\fIrfc1002\.txt\fR。 その他 CIFS(以前のSMB)の仕様を以下のWebページにあるリンクから入手できる:
http://samba\.org/cifs/
。
.SH "作者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、 Andrew Tridgell によって作られた。Samba は現在 Linux カーネルが 開発されているような方法でのオープンソースプロジェクトである Samba Team によって開発されている。
.PP
オリジナルの Samba の マニュアルページは Karl Auer によって書かれた。 マニュアルページは YODL 形式(別の、優秀なオープンソースソフトウェアで、
ftp://ftp\.icce\.rug\.nl/pub/unix/
にある) で変換され、Jeremy Allison によって Samba 2\.0 リリースのために更新された。 Samba 2\.2 のための DocBook 形式への変換は Gerald Carter が行った。 Samba 3\.0 のための DocBook XML 4\.2 形式への変換は Alexander Bokovoy が行った。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.0\.23 \- Samba 3\.0\.24 対応のものである。
.PP
このドキュメントの Samba 3\.0\.0 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
たかはしもとのぶ (monyo@samba\.gr\.jp)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
はせがわ ようすけ
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ちかましゅうへい
.sp
.RE
によって行なわれた。
.PP
Samba 3\.0\.23 \- Samba 3\.0\.24 対応の翻訳は、たかはしもとのぶ (monyo@samba\.gr\.jp) によって行なわれた。
.PP
Samba 3\.2\.4\-3\.2\.6 対応の翻訳は、太田俊哉 (ribbon@samba\.gr\.jp) によって行なわれた。
