.\"     Title: pdbedit
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/20/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"
.TH "PDBEDIT" "8" "04/20/2009" "Samba 3\.2" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pdbedit - SAM データベース (Samba ユーザのデータベース) を管理する
.SH "SYNOPSIS"
.HP 1
pdbedit [\-L] [\-v] [\-w] [\-u\ username] [\-f\ fullname] [\-h\ homedir] [\-D\ drive] [\-S\ script] [\-p\ profile] [\-a] [\-t,\ \-\-password\-from\-stdin] [\-m] [\-r] [\-x] [\-i\ passdb\-backend] [\-e\ passdb\-backend] [\-b\ passdb\-backend] [\-g] [\-d\ debuglevel] [\-s\ configfile] [\-P\ account\-policy] [\-C\ value] [\-c\ account\-control] [\-y]
.SH "説明"
.PP
このツールは、\fBsamba\fR(7)
システムの一部である。
.PP
pdbedit プログラムは SAM データベース内に保持されるユーザアカウントを管理するために利用され、 root だけが実行できる。
.PP
pdbedit ツールは、 passdb モジュールのインターフェイス経由で操作を行なうことで、 実際に利用するユーザーデータベースの種類 (現在のところ、smbpasswd ファイル、LDAP、NIS+、tdb ベースのデータベースがあり、それ以外のものもツールの変更なしに追加が可能) に依存しない作りになっている。
.PP
pdbedit の主な利用方法として、 ユーザーアカウントの追加、 ユーザーアカウントの削除、 ユーザーアカウントの変更、 ユーザーアカウントの一覧表示、 ユーザーアカウントの取り込みの 5 種類がある。
.SH "オプション"
.PP
\-L
.RS 4
データベースのすべてのユーザーアカウントを一覧表示する。 ユーザー名と UID の組み合わせが「:」で区切られて一覧表示される。
.sp
例:
pdbedit \-L
.sp
.sp
.RS 4
.nf
sorce:500:Simo Sorce
samba:45:Test User
.fi
.RE
.RE
.PP
\-v
.RS 4
冗長な一覧表示形式を有効にする。 データベース内のユーザーを一覧表示する際には、 アカウントの各項目を詳細に表示する。
.sp
例:
pdbedit \-L \-v
.sp
.sp
.RS 4
.nf
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
username:       sorce
user ID/Group:  500/500
user RID/GRID:  2000/2001
Full Name:      Simo Sorce
Home Directory: \e\eBERSERKER\esorce
HomeDir Drive:  H:
Logon Script:   \e\eBERSERKER\enetlogon\esorce\.bat
Profile Path:   \e\eBERSERKER\eprofile
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
username:       samba
user ID/Group:  45/45
user RID/GRID:  1090/1091
Full Name:      Test User
Home Directory: \e\eBERSERKER\esamba
HomeDir Drive:  
Logon Script:   
Profile Path:   \e\eBERSERKER\eprofile
.fi
.RE
.RE
.PP
\-w
.RS 4
一覧表示を「smbpasswd」形式にする。 データベース内のユーザを一覧表示する際、
アカウントの各項目は
\fIsmbpasswd\fR
ファイル互換の形式 (詳細は
\fBsmbpasswd\fR(5)
を参照のこと) で表示される。
.sp
例:
pdbedit \-L \-w
.sp
.RS 4
.nf
sorce:500:508818B733CE64BEAAD3B435B51404EE:
          D2A2418EFC466A8A0F6B1DBB5C3DB80C:
          [UX         ]:LCT\-00000000:
samba:45:0F2B255F7B67A7A9AAD3B435B51404EE:
          BC281CE3F53B6A5146629CD4751D3490:
          [UX         ]:LCT\-3BFA1E8D:
.fi
.RE
.RE
.PP
\-u username
.RS 4
操作 (表示・追加・削除など) の対象とするユーザ名を指定する。 追加・削除・変更操作においては\fI必須\fRであり、 表示操作においては\fI任意\fRである。
.RE
.PP
\-f fullname
.RS 4
ユーザの追加および変更を行なう際に、 ユーザのフルネームを指定する。
.sp
例:
\-f "Simo Sorce"
.RE
.PP
\-h homedir
.RS 4
ユーザの追加および変更を行なう際に、 ユーザのホームディレクトリとなるネットワークパスを指定する。
.sp
例:
\-h "\e\e\e\eBERSERKER\e\esorce"
.RE
.PP
\-D drive
.RS 4
ユーザの追加および変更を行なう際に、 ホームディレクトリの割り当て先とする Windows のドライブ名を指定する。
.sp
例:
\-D "H:"
.RE
.PP
\-S script
.RS 4
ユーザの追加および変更を行なう際に、 ユーザのログオンスクリプトのパスを指定する。
.sp
例:
\-S "\e\e\e\eBERSERKER\e\enetlogon\e\esorce\.bat"
.RE
.PP
\-p profile
.RS 4
ユーザの追加および変更を行なう際に、 ユーザのプロファイルパスを指定する。
.sp
例:
\-p "\e\e\e\eBERSERKER\e\enetlogon"
.RE
.PP
\-G SID|rid
.RS 4
ユーザの追加および変更を行なう際に、 ユーザのプライマリグループの SID (セキュリティ識別子) または RID を指定する。
.sp
例:
\-G S\-1\-5\-21\-2447931902\-1787058256\-3961074038\-1201
.RE
.PP
\-U SID|rid
.RS 4
ユーザの追加および変更を行なう際に、 ユーザの SID (セキュリティ識別子) または RID を指定する。
.sp
例:
\-U S\-1\-5\-21\-2447931902\-1787058256\-3961074038\-5004
.RE
.PP
\-c account\-control
.RS 4
ユーザの追加および変更を行なう際に、 ユーザのアカウント制御プロパティを指定する。 指定可能なフラグを以下に示す:
.sp

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
N: パスワード不要
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
D: アカウント無効
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
H: ホームディレクトリ必須
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
T: 一時的に他のアカウントと重複
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
U: 通常のユーザアカウント
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
M: MNS ログオン用のユーザアカウント
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
W: コンピュータ信頼アカウント(訳注: ドメインに参加する各マシンのためのアカウント)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
S: サーバ信頼アカウント
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
L: 自動ロック
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
X: 無期限パスワード
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
I: ドメイン信頼アカウント(訳注: 信頼関係するドメインのためのアカウント)
.sp
.RE
.sp
例:
\-c "[X ]"
.RE
.PP
\-a
.RS 4
ユーザをデータベースに追加する際に指定する。 ユーザ名を
\fI\-u\fR
オプションで指定する必要がある。 ユーザを追加する際、 pdbedit はユーザのパスワードの入力を求める。
.sp
例:
pdbedit \-a \-u sorce
.sp
.RS 4
.nf
new password:
retype new password
.fi
.RE
.sp
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note

\fIunix password sync\fR
が設定されていた場合でも、 pdbedit はスクリプトを実行せず、Samba のユーザデータベース内のデータのみを更新する点に注意。
.sp
ユーザの追加と同時にパスワード同期を直ちに行ないたい場合は、
smbpasswd
の
\fB\-a\fR
オプションを使用すること。
.RE
.PP
\-t, \-\-password\-from\-stdin
.RS 4
パスワードを (passwd(1)
プログラムのように) /dev/tty から読み取る代わりに標準入力から読み取らせる。 パスワードは二度入力し、各々末尾に改行(newline)文字を付けること。
.RE
.PP
\-r
.RS 4
データベースの既存のユーザの情報を変更する際に指定する。 ユーザ名は
\fI\-u\fR
オプションで指定する必要がある。 これ以外のオプションは、 指定したユーザのプロパティを変更するために用いられる。 このオプションは過去との互換性を保つために残されているだけで、 現在は指定する必要はない。
.RE
.PP
\-m
.RS 4
このオプションは
\fI\-a\fR
オプションと組み合わせて利用する。 これにより、 pdbedit はユーザーアカウントではなくコンピュータ信頼アカウントを追加する。 (\-u username にはコンピュータ名を指定する)
.sp
例:
pdbedit \-a \-m \-u w2k\-wks
.RE
.PP
\-x
.RS 4
データベースからユーザを削除する際に指定する。 ユーザ名は
\fI\-u\fR
オプションで指定する必要がある。
.sp
例:
pdbedit \-x \-u bob
.RE
.PP
\-i passdb\-backend
.RS 4
ユーザ情報の取得元となるパスワードデータベースとして、 smb\.conf で指定したものとは別のものを指定する。 これは、ローカルのユーザデータベースにデータを取り込む (インポートする) 際に利用する。
.sp
このオプションにより、 パスワードデータベースの移行を容易に行うことができる。
.sp
例:
pdbedit \-i smbpasswd:/etc/smbpasswd\.old
.RE
.PP
\-e passdb\-backend
.RS 4
指定したパスワードデータベースに存在するすべてのユーザを転送 (エクスポート) する。
.sp
このオプションにより、 パスワードデータベースの移行とバックアップを容易に行うことが可能となる。
.sp
例:
pdbedit \-e smbpasswd:/root/samba\-users\.backup
.RE
.PP
\-g
.RS 4
\fI\-g\fR
オプションを指定すると、
\fI\-i in\-backend \-e out\-backend\fR
オプションはユーザーデータベースではなく、 グループマッピングに対して適用される。
.sp
このオプションにより、 パスワードデータベースの移行とバックアップを容易に行うことが可能となる。
.RE
.PP
\-b passdb\-backend
.RS 4
デフォルト以外のパスワードデータベースを指定する。
.sp
例:
pdbedit \-b xml:/root/pdb\-backup\.xml \-l
.RE
.PP
\-P account\-policy
.RS 4
アカウントポリシーを表示する。
.sp
有効なポリシーは、 「minimum password age」、「reset count minutes」、 「disconnect time」、「user must logon to change password」、 「password history」、「lockout duration」、 「min password length」、「maximum password age」、 「bad lockout attempt」である。
.sp
例:
pdbedit \-P "bad lockout attempt"
.sp
.sp
.RS 4
.nf
account policy value for bad lockout attempt is 0
.fi
.RE
.RE
.PP
\-C account\-policy\-value
.RS 4
アカウントポリシーを指定した値に設定する。 このオプションは、\fI\-P\fR
オプションと組み合わせて使用する。
.sp
例:
pdbedit \-P "bad lockout attempt" \-C 3
.sp
.sp
.RS 4
.nf
account policy value for bad lockout attempt was 0
account policy value for bad lockout attempt is now 3
.fi
.RE
.RE
.PP
\-y
.RS 4

\fI\-y\fR
オプションを指定すると、
\fI\-i in\-backend \-e out\-backend\fR
オプションはユーザーデータベースではなく、 アカウントポリシーに対して適用される。
.sp
このオプションにより、 アカウントポリシーをデフォルトの TDB から LDAP ディレクトリサーバなどのパスワードデータベースに移行することが可能となる。
.sp
例:
pdbedit \-y \-i tdbsam: \-e ldapsam:ldap://my\.ldap\.host
.RE
.PP
\-h|\-\-help
.RS 4
コマンドラインオプションの要約を表示する。
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
は0から10までの整数値である。 既定値の値は、パラメータが設定されていなければ0である。
.sp
この値を大きくするほど、サーバの動作に関するより詳細な情報が ログファイルに記録される。レベル 0 では、致命的なエラーと重大な警告 のみが記録される。レベル 1 は日々の運用に適しており、少量の稼働状況 に関する情報を生成する。
.sp
1 より上のレベルは大量のログが生成されるので、問題解決の時にのみ 使用すべきである。 3 より上のレベルは開発者だけが利用するように設計されて おり、莫大な量のログデータが生成される。そのほとんどは非常に謎めいた内容 となっている
.sp
このパラメータの指定は、\fIsmb\.conf\fRファイル中の、
\fI\%smb.conf.5.html#\fR
パラメータの 指定よりも優先する。
.RE
.PP
\-V
.RS 4
プログラムのバージョン番号を表示する。
.RE
.PP
\-s <configuration file>
.RS 4
サーバーが必要とする詳細な設定を含む設定ファイルを 指定する。このファイルには、サーバーが提供するサービスに関する記述や、 どの printcap ファイルを利用するかといった情報が含まれている。詳細は
\fIsmb\.conf\fR
を参照のこと。設定ファイルの名前の既定値は、コンパイル時 に決定される。
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
ログ/デバッグファイルのファイル名。拡張子として
\fB"\.progname"\fR
が追加される(例えば log\.smbclient, log\.smbd,など)。ログファイルはクライアントによって削除されることはない。
.RE
.SH "注意"
.PP
このコマンドは root だけが利用できる。
.SH "バージョン"
.PP
このマニュアルページは、Samba バージョン 3 用に記述されている。
.SH "関連項目"
.PP
\fBsmbpasswd\fR(5),
\fBsamba\fR(7)
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、 Andrew Tridgell によって作られた。 Samba は現在、Linux カーネルが開発されているような方法でのオープンソースプロジェクトである Samba Team によって開発されている。
.PP
pdbedit のマニュアルページは Simo Sorce と Jelmer Vernooij によって作られた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.0\.23 \- Samba 3\.0\.24 対応のものである。
.PP
このドキュメントの Samba 3\.0\.24 対応の翻訳は たかはしもとのぶ (monyo@samba\.gr\.jp) によって行なわれた。
.PP
このドキュメントの Samba 3\.2\.4\-3\.2\.11 対応の翻訳は 太田俊哉 (ribbon@samba\.gr\.jp) によって行なわれた。
