.\"     Title: rpcclient
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 12/16/2008
.\"    Manual: ユーザコマンド
.\"    Source: Samba 3.2
.\"
.TH "RPCCLIENT" "1" "12/16/2008" "Samba 3\.2" "ユーザコマンド"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
rpcclient - クライアント側の MS-RPC 関数を発行するツール
.SH "SYNOPSIS"
.HP 1
rpcclient [\-A\ authfile] [\-c\ <command\ string>] [\-d\ debuglevel] [\-h] [\-l\ logdir] [\-N] [\-s\ <smb\ config\ file>] [\-U\ username[%password]] [\-W\ workgroup] [\-N] [\-I\ destinationIP] {server}
.SH "説明"
.PP
このツールは
\fBsamba\fR(7)
システムの一部である。
.PP
rpcclient
は Samba の MS\-RPC 機能をテストするために開発されたユーティリティであり、 開発と安定を何度か繰り返している。 多数のシステム管理者がこのツールを用いて UNIX ワークステーションから Windows NT クライアントを管理するスクリプトを作成している。
.SH "オプション"
.PP
server
.RS 4
接続先のサーバを NetBIOS 名で指定する。 サーバは SMB/CIFS サーバである必要がある。 この名前の解決には
\fBsmb.conf\fR(5 )
ファイルの
\fIname resolve order\fR
パラメータが用いられる。
.RE
.PP
\-c|\-\-command=\'command string\'
.RS 4
実行するコマンド (以下で記述) をセミコロンで区切って指定する。
.RE
.PP
\-I IP\-address
.RS 4
\fIIP address\fR
は接続先の サーバのアドレスを指定する。記述方法は、標準的な "a\.b\.c\.d" のフォーマットで指定する。
.sp
通常、クライアントは上記の
\fIname resolve order \fR
パラメータで指定された名前解決の機能を使用して NetBIOS 名を検索し、SMB/CIFS サーバを特定する。 このパラメータを使用することで、クライアントに対し強制的に 指定された IP Address にサーバがあると認識させ、接続しようとしているリソースの NetBIOS 名を無視させることができる。
.sp
このパラメータにデフォルトの値はない。 もしこの値が指定されていないのなら、上で述べたようにクライアントが 自動的に判別する。
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
は0から10までの整数値である。 既定値の値は、パラメータが設定されていなければ0である。
.sp
この値を大きくするほど、サーバの動作に関するより詳細な情報が ログファイルに記録される。レベル 0 では、致命的なエラーと重大な警告 のみが記録される。レベル 1 は日々の運用に適しており、少量の稼働状況 に関する情報を生成する。
.sp
1 より上のレベルは大量のログが生成されるので、問題解決の時にのみ 使用すべきである。 3 より上のレベルは開発者だけが利用するように設計されて おり、莫大な量のログデータが生成される。そのほとんどは非常に謎めいた内容 となっている
.sp
このパラメータの指定は、\fIsmb\.conf\fRファイル中の、
\fI\%smb.conf.5.html#\fR
パラメータの 指定よりも優先する。
.RE
.PP
\-V
.RS 4
プログラムのバージョン番号を表示する。
.RE
.PP
\-s <configuration file>
.RS 4
サーバーが必要とする詳細な設定を含む設定ファイルを 指定する。このファイルには、サーバーが提供するサービスに関する記述や、 どの printcap ファイルを利用するかといった情報が含まれている。詳細は
\fIsmb\.conf\fR
を参照のこと。設定ファイルの名前の既定値は、コンパイル時 に決定される。
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
ログ/デバッグファイルのファイル名。拡張子として
\fB"\.progname"\fR
が追加される(例えば log\.smbclient, log\.smbd,など)。ログファイルはクライアントによって削除されることはない。
.RE
.PP
\-N
.RS 4
このオプションを指定すると、クライアントはユーザーへの パスワード入力要求をしなくなる。パスワードが必要ないサービスにアクセスする ときに有用である。
.sp
コマンドラインにパスワードが指定されておらず、このオプションも指定 されていないと、クライアントはパスワードを要求する。
.sp
もしも、パスワードがコマンドライン上で指定され、このオプションも 定義されていた場合、コマンドライン上のパスワードは無視され、パスワードは 使われない。
.RE
.PP
\-k
.RS 4
Kerberos による認証を試みる。アクティブディレクトリ環境でのみ有効である。
.RE
.PP
\-A|\-\-authentication\-file=filename
.RS 4
このオプションは、指定したファイルから、接続に使用する ユーザー名とパスワードを読み込むために使用する。ファイルの形式は次の通り:
.sp
.sp
.RS 4
.nf
username = <value>
password = <value>
domain   = <value>
.fi
.RE
.sp
ファイルのパーミッションを確認し、ほかのユーザーから参照されない ように注意すること。
.RE
.PP
\-U|\-\-user=username[%password]
.RS 4
SMB のユーザー名、またはユーザー名とパスワードを指定する。
.sp
もしも %password を指定しないと、ユーザーにパスワードの入力を求める。 クライアントはまず初めに\fBUSER\fR、\fBLOGNAME\fRの順に 環境変数の存在を調べ、もしもどちらかが存在するならば、その文字列を大文字にする。 環境変数が存在しない場合、ユーザ名として\fBGUEST\fRが用いられる。
.sp
このほかに、平文のユーザー名とパスワードを記述した認証ファイルを使用する オプションがある。このオプションは主にスクリプト向けに用意されており、認証情報を コマンドラインや環境変数に含めたくない場合に有用である。このオプションを利用する ときは、ファイルのパーミッションを確認し、ほかのユーザーから参照されないように 注意すること。詳細は\fI\-A\fRオプションを参照のこと。
.sp
パスワードをスクリプトに含める場合は注意すること。多くのシステムでは、実行 中のプロセスのコマンドラインはpsコマンドで参照することが できてしまう。安全のため、必ず、rpcclientを使用して、 パスワード入力を要求し、直接入力するようにしておくこと。
.RE
.PP
\-n <primary NetBIOS name>
.RS 4
Samba 自身の NetBIOS 名を指定する。このオプションは、
\fIsmb\.conf\fR中の、\fI\%smb.conf.5.html#\fR
パラメータの設定に相当する。コマンドラインの指定は、
\fIsmb\.conf\fR
内の設定よりも優先される。
.RE
.PP
\-i <scope>
.RS 4
nmblookupが、通信用のNetBIOS名 を生成する時に使うNetBIOS スコープを指定する。NetBIOS スコープの詳細な 利用方法については、 RFC 1001 と RFC 1002 を参照のこと。NetBIOSスコープ は\fIごく稀にしか\fR利用されない。NetBIOS システム 全体を運営している管理者が、そのシステム内の相手と通信する場合にのみ、 このパラメータを設定する。
.RE
.PP
\-W|\-\-workgroup=domain
.RS 4
ユーザー名の SMB ドメインを指定する。このオプションは、 smb\.conf 内のデフォルトのドメイン設定よりも優先される。ドメイン名として サーバーの NetBIOS 名を指定すると、クライアントは (ドメインの SAM では なく) サーバーのローカル SAM を使用してログオンを試みる。
.RE
.PP
\-O socket options
.RS 4
クライアントのソケットに設定する TCP のソケットオプ ション。有効なオプションの一覧については、\fIsmb\.conf\fR
マニュアルページ 中の socket options パラメータを参照のこと。
.RE
.PP
\-h|\-\-help
.RS 4
コマンドラインオプションの要約を表示する。
.RE
.SH "コマンド"
.SS "LSARPC"
.PP
lsaquery
.RS 4
info policy を問い合わせる。
.RE
.PP
lookupsids
.RS 4
リストされた SID からユーザ名を解決する。
.RE
.PP
lookupnames
.RS 4
リストされたユーザ名から SID を解決する。
.RE
.PP
enumtrusts
.RS 4
信頼するドメインの一覧を表示する。
.RE
.PP
enumprivs
.RS 4
ユーザ権利の一覧を表示する。
.RE
.PP
getdispname
.RS 4
ユーザ権利の名前を取得する。
.RE
.PP
lsaenumsid
.RS 4
LSA の SID の一覧を表示する。
.RE
.PP
lsaenumprivsaccount
.RS 4
指定した SID の持つユーザ権利を一覧表示する。
.RE
.PP
lsaenumacctrights
.RS 4
指定されたユーザ権利を持つ SID を一覧表示する。
.RE
.PP
lsaenumacctwithright
.RS 4
指定されたユーザ権利を持つアカウントを一覧表示する。
.RE
.PP
lsaaddacctrights
.RS 4
アカウントにユーザ権利を追加する。
.RE
.PP
lsaremoveacctrights
.RS 4
アカウントからユーザ権利を取り除く。
.RE
.PP
lsalookupprivvalue
.RS 4
ユーザ権利の名前から値を取得する。
.RE
.PP
lsaquerysecobj
.RS 4
LSA セキュリティオブジェクトを問い合わせる。
.RE
.SS "LSARPC\-DS"
.PP
dsroledominfo
.RS 4
プライマリドメインの情報を取得する。
.RE
.PP
.PP
\fIDFS\fR
.PP
dfsexist
.RS 4
DFS をサポートしているか問い合わせる。
.RE
.PP
dfsadd
.RS 4
DFS の共有を追加する。
.RE
.PP
dfsremove
.RS 4
DFS の共有を削除する。
.RE
.PP
dfsgetinfo
.RS 4
DFS の共有の情報を問い合わせる。
.RE
.PP
dfsenum
.RS 4
DFS の共有の一覧を表示する。
.RE
.SS "REG"
.PP
shutdown
.RS 4
遠隔操作でシャットダウンさせる。
.RE
.PP
abortshutdown
.RS 4
シャットダウンを中止させる。
.RE
.SS "SRVSVC"
.PP
srvinfo
.RS 4
サーバ情報を問い合わせる。
.RE
.PP
netshareenum
.RS 4
共有を一覧表示する。
.RE
.PP
netfileenum
.RS 4
開いているファイルを一覧表示する。
.RE
.PP
netremotetod
.RS 4
リモートサーバの時間を取得する。
.RE
.SS "SAMR"
.PP
queryuser
.RS 4
ユーザ情報を問い合わせる。
.RE
.PP
querygroup
.RS 4
グループ情報を問い合わせる。
.RE
.PP
queryusergroups
.RS 4
ユーザが所属するグループを問い合わせる。
.RE
.PP
querygroupmem
.RS 4
グループに所属するメンバーを問い合わせる。
.RE
.PP
queryaliasmem
.RS 4
エイリアスに所属するメンバーを問い合わせる。
.RE
.PP
querydispinfo
.RS 4
ユーザ情報の一覧を表示する。
.RE
.PP
querydominfo
.RS 4
ドメイン情報を問い合わせる。
.RE
.PP
enumdomusers
.RS 4
ドメインユーザを一覧表示する。
.RE
.PP
enumdomgroups
.RS 4
ドメイングループを一覧表示する。
.RE
.PP
enumalsgroups
.RS 4
エイリアスグループ(ローカルグループ)を一覧表示する。
.RE
.PP
createdomuser
.RS 4
ドメインユーザを作成する。
.RE
.PP
samlookupnames
.RS 4
名前を検索する。
.RE
.PP
samlookuprids
.RS 4
rid を検索する。
.RE
.PP
deletedomuser
.RS 4
ドメインユーザを削除する。
.RE
.PP
samquerysecobj
.RS 4
SAMR セキュリティオブジェクトを問い合わせる。
.RE
.PP
getdompwinfo
.RS 4
ドメインパスワード情報を取得する
.RE
.PP
lookupdomain
.RS 4
ドメイン情報を検索する
.RE
.SS "SPOOLSS"
.PP
adddriver <arch> <config> [<version>]
.RS 4
プリンタドライバ情報をサーバに登録するために AddPrinterDriver() RPC の呼び出しを行なう。ドライバファイルは
getdriverdir
コマンドが返却するディレクトリ中に予め存在している必要が ある。\fIarch\fR
に設定できる値は
getdriverdir
コマンドで取得できる値と同じである。
\fIconfig\fR
パラメータでは以下の形式のファイルを 指定する。
.sp
.sp
.RS 4
.nf
Long Printer Name:\e
Driver File Name:\e
Data File Name:\e
Config File Name:\e
Help File Name:\e
Language Monitor Name:\e
Default Data Type:\e
Comma Separated list of Files
.fi
.RE
.sp
空のフィールドには、"NULL" という文字列を指定しておくこと。
.sp
Samba は Print Monitor 機能をサポートする必要がない。 これは、この機能が双方向通信を利用するドライバを使うローカルプリンタにしか関係しないためである。 このフィールドは必ず「NULL」にしておくこと。 遠隔の NT プリントサーバにコマンドを発行する場合、 ドライバの Print Monitor 機能をドライバの追加前にインストールしていないと、 RPC に失敗する。
.sp
\fIversion\fR
パラメータにより、プリンタドライバのバージョン番号が指定される。 省略した場合、アーキテクチャに応じたバージョンが用いられる。 このオプションは Windows 2000 (バージョン 3)のプリンタドライバのアップロードに用いることができる。
.RE
.PP
addprinter <printername> <sharename> <drivername> <port>
.RS 4
遠隔のサーバ上にプリンタを追加する。このプリンタは自動的に共有される。 このコマンドを実行する前に、プリンタドライバをサーバ上にインストール して (adddriver
を参照のこと)、\fIport \fR
を有効なポート名にしておく (enumports
を参照) 必要があることに注意。
.RE
.PP
deldriver
.RS 4
指定されたプリンタドライバについて、すべてのアーキテクチャ用のものを削除する。これは、 ドライバのファイル自体をサーバから削除するわけではなく、 サーバのドライバのリストからエントリだけを削除するものである。
.RE
.PP
deldriverex <driver> [architecture] [version]
.RS 4
指定されたプリンタドライバについて、ドライバファイルも含めて削除する。 削除対象のバージョンやアーキテクチャを指定することも可能である。 アーキテクチャが指定されなかった場合、すべてのドライバファイルが削除される。
.RE
.PP
enumdata
.RS 4
サーバ上に格納されているプリンタの設定情報を一覧表示する。Windows NT クライアントの場合、 これらの情報はレジストリに格納されているが、Samba サーバの場合、 プリンタ用の TDB ファイル中に格納されている。このコマンドは、 Microsoft Platform SDK 中にある GetPrinterData() 関数に相当する。 (このコマンドは現在実装されていない)
.RE
.PP
enumdataex
.RS 4
キーに基づいたプリンタの情報を表示する。
.RE
.PP
enumjobs <printer>
.RS 4
指定されたプリンタのジョブおよびその状況を表示する。 このコマンドは、Microsoft Platform SDK 中の EnumJobs() 関数に相当する。
.RE
.PP
enumkey
.RS 4
プリンタキーを 一覧表示する。
.RE
.PP
enumports [level]
.RS 4
指定された info level でEnumPorts() 関数を呼び出す。現在、info level 1 と 2 のみがサポートされている。
.RE
.PP
enumdrivers [level]
.RS 4
EnumPrinterDrivers() を実行する。これは全てのアーキテクチャ用の インストールされたドライバの一覧を表示する。フラグとオプションの 詳細については、Microsoft Platform SDK のドキュメントを参照のこと。 現在、info level 1, 2, 3 のみがサポートされている。
.RE
.PP
enumprinters [level]
.RS 4
EnumPrinters() を実行する。これは共有されている インストール済プリンタの一覧を表示する。フラグとオプションの詳細に ついては、Microsoft Platform SDK のドキュメントを参照のこと。 現在、info level 1, 2, 5 のみがサポートされている。
.RE
.PP
getdata <printername> <valuename;>
.RS 4
指定されたプリンタの設定情報を取得する。 詳細な情報に付いては、enumdata
コマンドを参照のこと。 このコマンドは Microsoft Platform SDK 中の GetPrinterData() に相当するものである。
.RE
.PP
getdataex
.RS 4
キー名に基づいた プリンタドライバのデータを取得する。
.RE
.PP
getdriver <printername>
.RS 4
指定されたプリンタのプリンタドライバの情報 (ドライバファイル、 設定ファイル、関連するファイルなど) を取得する。このコマンドは Microsoft Platform SDK 中の GetPrinterDriver() に相当するものである。 現在、info level 1, 2, 3 のみがサポートされている。
.RE
.PP
getdriverdir <arch>
.RS 4
GetPrinterDriverDirectory() RPC を発行して、SMB 共有名と指定された アーキテクチャ用のプリンタドライバの格納されているサブディレクトリを 取得する。\fIarch\fR
に指定できる値は、 "Windows 4\.0" (for Windows 95/98), "Windows NT x86", "Windows NT PowerPC", "Windows Alpha_AXP", "Windows NT R4000" である。
.RE
.PP
getprinter <printername>
.RS 4
現在のプリンタ情報を取得する。このコマンドは Microsoft Platform SDK の GetPrinter() に相当する。
.RE
.PP
getprintprocdir
.RS 4
print processor ディレクトリを取得する。
.RE
.PP
openprinter <printername>
.RS 4
指定したプリンタに対して、OpenPrinterEx() と ClosePrinter() RPC を実行する。
.RE
.PP
setdriver <printername> <drivername>
.RS 4
SetPrinter() コマンドを実行して、既にインストール されているプリンタ用のプリンタドライバを更新する。 更新されるプリンタドライバは、プリントサーバ上に適切にインストール されている必要がある。
.sp
インストールされているプリンタやドライバの一覧を取得する方法に ついては
enumprinters
や
enumdrivers
コマンドも参照のこと。
.RE
.PP
addform
.RS 4
フォームを追加する。
.RE
.PP
setform
.RS 4
フォームを設定する。
.RE
.PP
getform
.RS 4
フォームを取得する。
.RE
.PP
deleteform
.RS 4
フォームを削除する。
.RE
.PP
enumforms
.RS 4
フォームを 一覧表示する。
.RE
.PP
setprinter
.RS 4
プリンタのコメントを 設定する。
.RE
.PP
setprinterdata
.RS 4
REG_SZ プリンタデータを設定する。
.RE
.PP
setprintername <printername> <newprintername>
.RS 4
プリンタ名を設定する。
.RE
.PP
rffpcnex
.RS 4
Rffpcnex テストを実行する。
.RE
.SS "NETLOGON"
.PP
logonctrl2
.RS 4
Logon Control 2 に変更する。
.RE
.PP
logonctrl
.RS 4
Logon Control に変更する。
.RE
.PP
samsync
.RS 4
Sam Synchronisation をはかり、結果を表示する。
.RE
.PP
samdeltas
.RS 4
Sam Delta Synchronisation をはかり、結果を表示する。
.RE
.PP
samlogon
.RS 4
ドメインユーザでログオンする。
.RE
.SS "共通コマンド"
.PP
debuglevel
.RS 4
現在の debug level を設定する。これはログ情報の書き込みに影響する。
.RE
.PP
help (?)
.RS 4
コマンド一覧の表示と、 幾つかのコマンドに付いての詳細な説明を表示する。
.RE
.PP
quit (exit)
.RS 4
rpcclient
を終了させる。
.RE
.SH "バグ"
.PP
rpcclient
は開発者のテストツールとしての利用を 念頭に置いているため、あまり動作が安定していない部分 (コマンドラインの解析など) もある。無効なパラメータを解析しようとすると、 失敗してコアダンプするのは既知の不具合である。
.PP
Luke Leighton のオリジナルの rpcclient マニュアルページより:
.PP
\fI警告!\fR
SMB 上の MSRPC コードは ネットワークトレースを行なうことで開発されている。オリジナルの開発者 (Microsoft) からは、SMB 上で MSRPC がどのように動作するか、 個々の MSRPC サービスがどのように動作するかについての情報は提供されていない。 これらのサービスに関する Microsoft の実装も、場所によってはかなり風変わりで あることが明らかになっている。
.PP
同様に Samba への実装も場あたり的な面がある。 多くのサービスの実装が解明されるにつれて、\fBsmbd \fR(8)
や
\fBrpcclient\fR(1)
は、幾つかのコマンドやサービスにおいてバージョン間の互換性が なくなることもありうる。なお、開発者達は発見した問題を Microsoft に対してレポートしており、報告された問題はサービスパックで修正されているが、 その結果互換性が損なわれることがあるかもしれない。
.SH "バージョン"
.PP
このマニュアルページは Samba バージョン 3 用である。
.SH "作者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、 Andrew Tridgell によって作成された。現在 Samba は Samba Team によって、 Linux カーネルの開発と同様のオープンソースプロジェクトとして開発が 行なわれている。
.PP
オリジナルの rpcclient マニュアルページは Matthew Geddes と Luke Keneth Casson Leighton によって作成され、 Gerald Carter によって書き直された。 Samba 2\.2 における DocBook 形式への変換は、Gerald Carter によって行なわれた。Samba 3\.0 における DocBook XML 4\.2 形式への変換は Alexander Bokovoy によって行われた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.0\.23 \- Samba 3\.2\.4\-3\.2\.6 対応のものである。
.PP
このドキュメントの Samba 3\.0\.0 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
高橋 基信 (monyo@samba\.gr\.jp)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
はせがわ ようすけ
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
山田 史朗 (shiro@miraclelinux\.com)
.sp
.RE
によって行なわれた。
.PP
Samba 3\.0\.23 \- Samba 3\.2\.4\-3\.2\.6 対応の翻訳は、たかはしもとのぶ (monyo@samba\.gr\.jp) によって行なわれた。
