'\" t
.\"     Title: smbcquotas
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/20/2010
.\"    Manual: ユーザコマンド
.\"    Source: Samba 3.4
.\"  Language: English
.\"
.TH "SMBCQUOTAS" "1" "03/20/2010" "Samba 3\&.4" "ユーザコマンド"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
smbcquotas \- NTFS 5 共有の Quota 情報を取得・設定する
.SH "SYNOPSIS"
.HP \w'\ 'u
smbcquotas {//server/share} [\-u\ user] [\-L] [\-F] [\-S\ QUOTA_SET_COMMAND] [\-n] [\-t] [\-v] [\-d\ debuglevel] [\-s\ configfile] [\-l\ logdir] [\-V] [\-U\ username] [\-N] [\-k] [\-A]
.SH "説明"
.PP
このプログラムは
\fBSamba\fR(7)
システムの一部である\&.
.PP
smbcquotas
プログラムは SMB ファイル共有に対して NT Quota の操作を行う。
.SH "オプション"
.PP
smbcquotas
プログラムは下記のオプションを提供する :
.PP
\-u user
.RS 4
Quota の情報の取得や設定を行うユーザを指定する。 デフォルトでは、カレントユーザが使用される。
.RE
.PP
\-L
.RS 4
共有の Quota のレコードを全て表示する。
.RE
.PP
\-F
.RS 4
共有の Quota のステータスとデフォルトの制限を表示する。
.RE
.PP
\-S QUOTA_SET_COMMAND
.RS 4
このコマンドはユーザか共有の Quota の設定や変更を行う。 ユーザか共有かどちらに対して操作が行われるかは、後述される QUOTA_SET_COMMAND により決まる。
.RE
.PP
\-n
.RS 4
このオプションは全ての Quota 情報を数値化した値で 表示する。デフォルトでは SID を名前に、Quota の上限を文字列に変換する。
.RE
.PP
\-t
.RS 4
実際に処理は行わず、指定した引数の正当性を検証する。
.RE
.PP
\-v
.RS 4
冗長モードにする。
.RE
.PP
\-h|\-\-help
.RS 4
コマンドラインオプションの要約を表示する。
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
は0から10までの整数値である。 既定値の値は、パラメータが設定されていなければ0である。
.sp
この値を大きくするほど、サーバの動作に関するより詳細な情報が ログファイルに記録される。レベル 0 では、致命的なエラーと重大な警告 のみが記録される。レベル 1 は日々の運用に適しており、少量の稼働状況 に関する情報を生成する。
.sp
1 より上のレベルは大量のログが生成されるので、問題解決の時にのみ 使用すべきである。 3 より上のレベルは開発者だけが利用するように設計されて おり、莫大な量のログデータが生成される。そのほとんどは非常に謎めいた内容 となっている
.sp
このパラメータの指定は、smb\&.confファイル中の、
\m[blue]\fB\%smb.conf.5.html#\fR\m[]
パラメータの 指定よりも優先する。
.RE
.PP
\-V
.RS 4
プログラムのバージョン番号を表示する。
.RE
.PP
\-s <configuration file>
.RS 4
サーバーが必要とする詳細な設定を含む設定ファイルを 指定する。このファイルには、サーバーが提供するサービスに関する記述や、 どの printcap ファイルを利用するかといった情報が含まれている。詳細は
smb\&.conf
を参照のこと。設定ファイルの名前の既定値は、コンパイル時 に決定される。
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
ログ/デバッグファイルのファイル名。拡張子として
\fB"\&.progname"\fR
が追加される(例えば log\&.smbclient, log\&.smbd,など)。ログファイルはクライアントによって削除されることはない。
.RE
.PP
\-N
.RS 4
このオプションを指定すると、クライアントはユーザーへの パスワード入力要求をしなくなる。パスワードが必要ないサービスにアクセスする ときに有用である。
.sp
コマンドラインにパスワードが指定されておらず、このオプションも指定 されていないと、クライアントはパスワードを要求する。
.sp
もしも、パスワードがコマンドライン上で指定され、このオプションも 定義されていた場合、コマンドライン上のパスワードは無視され、パスワードは 使われない。
.RE
.PP
\-k
.RS 4
Kerberos による認証を試みる。アクティブディレクトリ環境でのみ有効である。
.RE
.PP
\-A|\-\-authentication\-file=filename
.RS 4
このオプションは、指定したファイルから、接続に使用する ユーザー名とパスワードを読み込むために使用する。ファイルの形式は次の通り:
.sp
.if n \{\
.RS 4
.\}
.nf
username = <value>
password = <value>
domain   = <value>
.fi
.if n \{\
.RE
.\}
.sp
ファイルのパーミッションを確認し、ほかのユーザーから参照されない ように注意すること。
.RE
.PP
\-U|\-\-user=username[%password]
.RS 4
SMB のユーザー名、またはユーザー名とパスワードを指定する。
.sp
もしも %password を指定しないと、ユーザーにパスワードの入力を求める。 クライアントはまず初めに\fBUSER\fR、\fBLOGNAME\fRの順に 環境変数の存在を調べ、もしもどちらかが存在するならば、その文字列を大文字にする。 環境変数が存在しない場合、ユーザ名として\fBGUEST\fRが用いられる。
.sp
このほかに、平文のユーザー名とパスワードを記述した認証ファイルを使用する オプションがある。このオプションは主にスクリプト向けに用意されており、認証情報を コマンドラインや環境変数に含めたくない場合に有用である。このオプションを利用する ときは、ファイルのパーミッションを確認し、ほかのユーザーから参照されないように 注意すること。詳細は\fI\-A\fRオプションを参照のこと。
.sp
パスワードをスクリプトに含める場合は注意すること。多くのシステムでは、実行 中のプロセスのコマンドラインはpsコマンドで参照することが できてしまう。安全のため、必ず、rpcclientを使用して、 パスワード入力を要求し、直接入力するようにしておくこと。
.RE
.SH "QUOTA_SET_COMAND"
.PP
QUOTA_SET_COMMANDの形式は、その操作に固有の一連のパラメータが伴う 操作名である。
.PP
\-u で指定されたユーザかカレントユーザ特有の Quota 制限を設定する :
.PP
\fB UQLIM:<username>:<softlimit>/<hardlimit> \fR
.PP
共有のデフォルトの Quota 制限を設定する :
.PP
\fB FSQLIM:<softlimit>/<hardlimit> \fR
.PP
共有の Quota 設定を変更する :
.PP
\fB FSQFLAGS:QUOTA_ENABLED/DENY_DISK/LOG_SOFTLIMIT/LOG_HARD_LIMIT \fR
.PP
すべての制限はバイト数によって指定される。
.SH "終了ステータス"
.PP
smbcquotas
コマンドは操作の成功か、それ以外かにより exit status をセットする。exit status は以下のうちのいずれかである :
.PP
操作が成功した場合、smbcquotas は exit status として 0 を返す。 もし
smbcquotas
が指定されたサーバに接続できなかった場合や、 Quota の情報を取得やセットしようとしてエラーが出た場合、exit status の 1 が返される。もしコマンドラインの引数の構文解析に対してエラーがあった場合、 exit status の 2 が返される。
.SH "バージョン"
.PP
この man page は version 3 の Samba システム用である。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連ユーティリティは、Andrew Tridgell によって作成された。現在 Samba は、Samba Team によって Linux カーネルの開発と同様に、オープンソースプロジェクトとして開発されている。
.PP
smbcquotas
は Stefan Metzmacher によって書かれた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.2\&.4 \- 3\&.5\&.1 対応のものである。
.PP
このドキュメントの Samba 3\&.2\&.4 \- 3\&.5\&.1 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
山田 史朗 (shiro@miraclelinux\&.com)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉 (ribbon@samba\&.gr\&.jp)
.sp
.RE
によって行なわれた。
