'\" t
.\"     Title: smbcacls
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 06/28/2010
.\"    Manual: ユーザコマンド
.\"    Source: Samba 3.4
.\"  Language: English
.\"
.TH "SMBCACLS" "1" "06/28/2010" "Samba 3\&.4" "ユーザコマンド"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
smbcacls \- Windows NT 上のファイルやディレクトリの ACL の取得や設定
.SH "SYNOPSIS"
.HP \w'\ 'u
smbcacls {//server/share} {filename} [\-D\ acls] [\-M\ acls] [\-a\ acls] [\-S\ acls] [\-C\ name] [\-G\ name] [\-\-numeric] [\-t] [\-U\ username] [\-h] [\-d]
.SH "説明"
.PP
このツールは
\fBsamba\fR(7)システムの一部である。
.PP
smbcacls
は、SMB ファイル共有内の ACL (Access Control Lists) を操作するプログラムである。
.SH "オプション"
.PP
smbcacls
コマンドでは以下のオプションが 利用可能である。ACL の形式は、ACL FORMAT セクションで記述する。
.PP
\-a acls
.RS 4
ACL リストで指定された ACL を追加する。既存の ACL は変更されない。
.RE
.PP
\-M acls
.RS 4
コマンドラインで指定された ACL の mask 値 (パーミッション) を変更する。ACL リストに指定された ACL が存在しない場合、その ACL 毎にエラーが出力される。
.RE
.PP
\-D acls
.RS 4
コマンドラインで指定された ACL を削除する。ACL ACL リストに指定された ACL が存在しない場合、その ACL 毎にエラーが 出力される。
.RE
.PP
\-S acls
.RS 4
このコマンドは、コマンドラインで指定された ACL のみをファイルに設定する。その他の全ての ACL は削除される。 呼び出しを成功させるためには、指定する ACL に最低限リビジョン、タイプ、 所有者とグループが含まれている必要がある。
.RE
.PP
\-U username
.RS 4
指定されたサービスに接続する際に利用するユーザ名を 指定する。ユーザ名が "username" の形式で与えられた場合、\fBsmb.conf\fR(5)
で指定されたワークグループが用いられ、ユーザには パスワード入力を求めるプロンプトが表示される。"username%password" もしくは "DOMAIN\eusername%password" を指定した場合、パスワードや ワークグループ名は指定されたものが用いられる。
.RE
.PP
\-C name
.RS 4

\fI\-C\fR
オプションを利用することで、 ファイルやディレクトリの所有者を name で指定したアカウントに変更することが可能である。 name は S\-1\-x\-y\-z 形式の sid で指定するか、 最初の引数で指定したサーバが認識可能な名前で指定する。
.sp
このコマンドは \-M OWNER:name の短縮形になる。
.RE
.PP
\-G name
.RS 4
ファイルやディレクトリのグループ所有者は、\fI \-G\fR
オプションを利用することで指定した name に変更することが可能である。名前は S\-1\-x\-y\-z 形式の sid で指定するか、 先頭の引数で指定したサーバが認識可能な name で指定する。
.sp
このコマンドは \-M OWNER:name の短縮形になる。
.RE
.PP
\-\-numeric
.RS 4
このオプションは、全ての ACL 情報を数値形式で 表示させる。デフォルトでは、SID は名前に、ACE の type と mask は、 可読性のある文字列形式に変換される。
.RE
.PP
\-t
.RS 4
実際に処理は行わず、指定した引数の正当性を検証する。
.RE
.PP
\-h|\-\-help
.RS 4
コマンドラインオプションの要約を表示する。
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
は0から10までの整数値である。 既定値の値は、パラメータが設定されていなければ0である。
.sp
この値を大きくするほど、サーバの動作に関するより詳細な情報が ログファイルに記録される。レベル 0 では、致命的なエラーと重大な警告 のみが記録される。レベル 1 は日々の運用に適しており、少量の稼働状況 に関する情報を生成する。
.sp
1 より上のレベルは大量のログが生成されるので、問題解決の時にのみ 使用すべきである。 3 より上のレベルは開発者だけが利用するように設計されて おり、莫大な量のログデータが生成される。そのほとんどは非常に謎めいた内容 となっている
.sp
このパラメータの指定は、smb\&.confファイル中の、
\m[blue]\fB\%smb.conf.5.html#\fR\m[]
パラメータの 指定よりも優先する。
.RE
.PP
\-V
.RS 4
プログラムのバージョン番号を表示する。
.RE
.PP
\-s <configuration file>
.RS 4
サーバーが必要とする詳細な設定を含む設定ファイルを 指定する。このファイルには、サーバーが提供するサービスに関する記述や、 どの printcap ファイルを利用するかといった情報が含まれている。詳細は
smb\&.conf
を参照のこと。設定ファイルの名前の既定値は、コンパイル時 に決定される。
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
ログ/デバッグファイルのファイル名。拡張子として
\fB"\&.progname"\fR
が追加される(例えば log\&.smbclient, log\&.smbd,など)。ログファイルはクライアントによって削除されることはない。
.RE
.SH "ACL FORMAT"
.PP
ACL の形式は、コンマか改行記号で 1 つ以上の ACL エントリを区切ったもの である。ACL エントリは以下のいずれかの形式をとる:
.PP
.if n \{\
.RS 4
.\}
.nf
 
REVISION:<revision number>
OWNER:<sid or name>
GROUP:<sid or name>
ACL:<sid or name>:<type>/<flags>/<mask>
.fi
.if n \{\
.RE
.\}
.PP
REVISION は、セキュリティディスクリプタに対する内部的な Windows NT ACL のリビジョンを表す。特に指定されない場合のデフォルトは 1 である。 1 以外の値を指定した場合は、挙動がおかしくなることがある。
.PP
OWNER と GROUP はオブジェクトの所有者およびグループの sid を指定する。 SID が S\-1\-x\-y\-z の形式で指定された場合はそのまま用いられ、 それ以外の場合、指定された名前はファイルやディレクトリが存在するサーバに よって解析される。
.PP
ACL は SID に対して与えられるパーミッションを指定する。この SID も S\-1\-x\-y\-z の形式で指定するか、名前で指定することが可能で、後者の場合、 ファイルやディレクトリが存在するサーバによって解析される。 type, flag, mask の値は、SIDに対して与えられたアクセスの種類を指定する。
.PP
typeは SID に対する許可および拒否に対応する(訳注: 実際は type は ALLOWED か DENIED を指定し、それぞれ SID に対するアクセス許可および拒否に対応する、が正しい(fumiya))。 flag の値はファイルの ACL の場合通常 0 であり、ディレクトリの ACL の場合は通常 9 か 2 である。 共通的な flags は以下の通りである:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB#define SEC_ACE_FLAG_OBJECT_INHERIT 0x1\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB#define SEC_ACE_FLAG_CONTAINER_INHERIT 0x2\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB#define SEC_ACE_FLAG_NO_PROPAGATE_INHERIT 0x4\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB#define SEC_ACE_FLAG_INHERIT_ONLY 0x8\fR
.sp
.RE
.PP
現在のところ flag の値は 10 進数もしくは 16 進数でのみ指定することができる。
.PP
mask は SID に対して与えられたアクセス権を表現する値である。それは 10 進数もしくは 16 進数で設定するか、NT のファイルパーミッションと同じ名称である 以下の文字列のうちの一つを利用して設定することができる。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIR\fR
\- 読みとりの許可
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIW\fR
\- 書き込みの許可
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIX\fR
\- オブジェクトの実行
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fID\fR
\- オブジェクトの削除
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIP\fR
\- パーミッションの変更
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIO\fR
\- 所有権の取得
.sp
.RE
.PP
以下の複合パーミッションも指定可能である:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIREAD\fR
\- \'RX\' パーミッションと等価である。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fICHANGE\fR
\- \'RXWD\' パーミッションと等価である。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIFULL\fR
\- \'RWXDPO\' パーミッションと等価である。
.SH "終了ステータス"
.PP
smbcacls
コマンドは、操作が成功したか、 その他の結果になったかに応じた戻り値を設定する。 戻り値は、以下の値のいずれかになる。
.PP
操作が成功した場合、smbcacls
は戻り値として 0 を返す。もし
smbcacls
が指定したサーバに接続できなかったか、 ACL を取得または設定する際にエラーが発生した場合、戻り値として 1 が返される。 コマンドライン引数の解析に失敗した場合は、戻り値として 2 が返される。
.SH "バージョン"
.PP
このマニュアルページは Samba バージョン 3用である。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team によって、Linux カーネルの開発と同様のオープンソースプロジェクトとして開発が行なわれている。
.PP
smbcacls
は Andrew Tridgell と Tim Potter によって書かれた。
.PP
Samba 2\&.2 における DocBook 形式への変換は、Gerald Carter によって行なわれた。Samba 3\&.0 における DocBook XML 4\&.2 形式への変換は、 Alexander Bokovoy によって行われた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.0\&.0 \- 3\&.5\&.4 対応のものである。
.PP
このドキュメントの Samba 3\&.0\&.0 \- Samba 3\&.5\&.4 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
たかはしもとのぶ (monyo@samba\&.gr\&.jp)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
山田 史朗 (shiro@miraclelinux\&.com)
.sp
.RE
によって行なわれた。
