.\"     Title: smbget
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/17/2009
.\"    Manual: ユーザコマンド
.\"    Source: Samba 3.3
.\"
.TH "SMBGET" "1" "04/17/2009" "Samba 3\.3" "ユーザコマンド"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
smbget - SMB 経由でファイルをダウンロードするための wget ライクな ユーティリティー
.SH "SYNOPSIS"
.HP 1
smbget [\-a,\ \-\-guest] [\-r,\ \-\-resume] [\-R,\ \-\-recursive] [\-u,\ \-\-username=STRING] [\-p,\ \-\-password=STRING] [\-w,\ \-\-workgroup=STRING] [\-n,\ \-\-nonprompt] [\-d,\ \-\-debuglevel=INT] [\-D,\ \-\-dots] [\-P,\ \-\-keep\-permissions] [\-o,\ \-\-outputfile] [\-f,\ \-\-rcfile] [\-q,\ \-\-quiet] [\-v,\ \-\-verbose] [\-b,\ \-\-blocksize] [\-?,\ \-\-help] [\-\-usage] {smb://host/share/path/to/file} [smb://url2/] [\.\.\.]
.SH "説明"
.PP
このツールは
\fBsamba\fR(7)
スイートの一部である。
.PP
smbget は SMB サーバからファイルをダウンロードできる、wget ライクな 使い勝手を持つシンプルなユーティリティーである。ダウンロードしたい ファイルをコマンドラインで指定することができる。
.PP
ファイルは smb\-URL の書式で指定する。たとえば UNC パスで
\fI\e\e\e\eHOST\e\eSHARE\e\efile\fR
というファイルであれば、 smb://host/share/file のように指定する。
.SH "オプション"
.PP
\-a, \-\-guest
.RS 4
guest ユーザとして接続する
.RE
.PP
\-r, \-\-resume
.RS 4
前回中断したファイルから自動的に処理を継続する
.RE
.PP
\-R, \-\-recursive
.RS 4
ファイルを再帰的にダウンロードする
.RE
.PP
\-u, \-\-username=STRING
.RS 4
使用するユーザ名
.RE
.PP
\-p, \-\-password=STRING
.RS 4
使用するパスワード
.RE
.PP
\-w, \-\-workgroup=STRING
.RS 4
使用するワークグループ（オプション）
.RE
.PP
\-n, \-\-nonprompt
.RS 4
ユーザに対して問い合わせを行わない（非会話型）
.RE
.PP
\-d, \-\-debuglevel=INT
.RS 4
使用するデバッグレベル
.RE
.PP
\-D, \-\-dots
.RS 4
プログラムの進行状況をドットで表示する
.RE
.PP
\-P, \-\-keep\-permissions
.RS 4
リモートファイルと同じパーミッションを ローカルファイルに適用する。
.RE
.PP
\-o, \-\-outputfile
.RS 4
出力ファイル名として別のファイル名を指定する。\-R と同時には指定できない。
.RE
.PP
\-f, \-\-rcfile
.RS 4
指定された rcfile を使う。これはオプションで指定された順に読み込まれる。 つまりこの前に何かのオプションを指定した場合、そのオプションは rcfile の内容で上書きされる。
.RE
.PP
\-q, \-\-quiet
.RS 4
処理中にメッセージを出力しない
.RE
.PP
\-v, \-\-verbose
.RS 4
冗長表示を行う
.RE
.PP
\-b, \-\-blocksize
.RS 4
ダウンロードする際の読み込み単位（バイト）。 デフォルトは 64000。
.RE
.PP
\-?, \-\-help
.RS 4
ヘルプメッセージを表示する
.RE
.PP
\-\-usage
.RS 4
使用法の概要を表示する
.RE
.SH "SMB URL"
.PP
SMB の URL は以下の書式で指定する：
.PP
.RS 4
.nf
smb://[[[ドメイン名;]ユーザ名[:パスワード@]]サーバー名[/共有名[/パス名[/ファイル名]]]]
.fi
.RE
.PP
.RS 4
.nf
smb:// はすべてのワークグループを意味する
.fi
.RE
.PP
.RS 4
.nf
smb://名前/ \- \fI名前\fR がワークグループ名の場合は
そのワークグループ内のすべてのサーバー、\fI名前\fR が
サーバー名の場合はそのサーバー上のすべての共有名を意味する。
.fi
.RE
.SH "実行例"
.sp
.RS 4
.nf
# \'src\' ディレクトリー配下を再帰的にダウンロード
smbget \-R smb://rhonwyn/jelmer/src
# FreeBSD の ISO ファイルをダウンロード。中断後のリジュームも有効に。
smbget \-r smb://rhonwyn/isos/FreeBSD5\.1\.iso
# すべての ISO ファイルをダウンロード
smbget \-Rr smb://rhonwyn/isos
# データを rhonwyn にバックアップ
smbget \-Rr smb://rhonwyn/
.fi
.RE
.SH "バグ"
.PP
ある種の原因不明なエラー（ URL の書式が誤っていたり、\-R オプションなしで ディレクトリを取得しようとしたなど）の場合、Permission denied が 返されることがある。
.SH "バージョン"
.PP
このマニュアルは Sambaバージョン 3用である。
.SH "作者"
.PP
オリジナルの Samba ソフトウェアおよび関連するユーティリティーは、 Andrew Tridgell によって書かれた。現在は Samba は Samba Team によって Linux カーネルの開発と同様に、オープンソースプロジェクトとして 開発されている。
.PP
smbget のマニュアルは Jelmer Vernooij によって書かれた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.2\.4\-3\.3\.2 対応のものである。
.PP
このドキュメントの Samba 3\.2\.4\-3\.3\.2 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\.com)
.sp
.RE
によって行なわれた。
