.\"     Title: smbpasswd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/17/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"
.TH "SMBPASSWD" "8" "04/17/2009" "Samba 3\.2" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
smbpasswd - ユーザーの SMB パスワードを変更する
.SH "SYNOPSIS"
.HP 1
smbpasswd [\-a] [\-c\ <config\ file>] [\-x] [\-d] [\-e] [\-D\ debuglevel] [\-n] [\-r\ <remote\ machine>] [\-R\ <name\ resolve\ order>] [\-m] [\-U\ username[%password]] [\-h] [\-s] [\-w\ pass] [\-W] [\-i] [\-L] [username]
.SH "説明"
.PP
このツールは、\fBSamba\fR(7)システムの一部である。
.PP
smbpasswd プログラムは、
\fIroot\fR
ユーザーによって実行される場合とそうでない場合とで、いくつかの機能が異なる。 一般ユーザーによって実行される場合、ユーザーは SMB パスワードを格納するあらゆるマシン上で、SMB セッションのために利用する自分のパスワードを変更することができる。
.PP
デフォルト (引数なしで実行した場合) では、 ローカルマシン上の実行したユーザーの SMB パスワードの変更を試みる。 これは
passwd(1)
プログラムと似た動作となる。
smbpasswd
は、
\fIsetuid root\fR
されていない点と、 クライアント/サーバーモードで動作し、同一ホストで動作している
\fBsmbd\fR(8)
と通信する点が
passwd(1)
と異なる。 このため、パスワードを変更するには、 smbd デーモンがローカルマシン上で動作していなければならない。 UNIX マシン上では、通常、 暗号化された SMB パスワードは
\fBsmbpasswd\fR(5)
ファイルに保持される。
.PP
一般ユーザーが引数なしで実行すると、 smbpasswd は古い (現在の) SMB パスワードの入力を求めた後、 新しいパスワードが正しく入力されることを確実にするため、 新しいパスワードの入力を 2 回求める。 入力したパスワードは画面上には表示されない。 ユーザーにパスワードが割り当てられていない場合 (smbpasswd ファイルで「NO PASSWORD」という文字列が指定されている場合) は、 古いパスワードの入力を求められたときに <Enter> キーだけを押すこと。
.PP
smbpasswd は、一般ユーザーが Windows NT プライマリドメインコントローラーなどのリモートマシン上の SMB パスワードを変更する際に使用することもできる。 詳細は下記の
\fI\-r\fR
オプションと
\fI\-U\fR
オプションを参照のこと。
.PP
root が実行する場合、smbpasswd は smbpasswd ファイルへの ユーザーの追加・削除、既存ユーザーの属性を変更することが可能である。 このとき、
smbpasswd
はローカルの smbpasswd ファイルに 直接アクセスする。よって、 smbd が実行されていなくても変更を行うことが可能である。
.SH "オプション"
.PP
\-a
.RS 4
このオプションは、 指定したユーザー username を新しいパスワードとともにローカルの smbpasswd ファイルに追加することを指示する。
すでに指定されたユーザーが存在する場合はオプションは無視され、 通常どおりパスワード変更コマンドとして動作する。 注意: デフォルトのパスワードデータベースバックエンドは、 システムのパスワードファイル (通常は
\fI/etc/passwd\fR) に同名のユーザーが存在いることを要求するため、 システムにユーザーが存在しないとユーザーの追加は失敗する。
.sp
このオプションは、 root が smbpasswd を実行するときだけ利用できる。
.RE
.PP
\-c
.RS 4
このオプションは、既定値のファイルと位置ものを使うことが重要な時、
\fIsmb\.conf\fR設定ファイルのパスとファイル名を指定することに使うことが出来る。
.RE
.PP
\-x
.RS 4
このオプションは、 指定したユーザー username をローカルの smbpasswd ファイルから削除することを指示する。
.sp
このオプションは、 root が smbpasswd を実行するときだけ利用できる。
.RE
.PP
\-d
.RS 4
このオプションは、 ローカルの smbpasswd ファイル内の指定したユーザー username を\fB無効にすること\fRを指示する。 これは、 smbpasswd ファイルのアカウント制御領域に 「\fBD\fR」 フラグを書き込むことで行なわれる。 こうすることで、 このユーザー名を利用した SMB の認証はすべて失敗するようになる。
.sp
smbpasswd ファイルが Samba 2\.0 以前の古い形式の場合、 ユーザーのパスワードエントリに情報を書き込むための領域がないため、
このオプション指定は失敗する。 新旧のパスワードファイル形式についての詳細は、
\fBsmbpasswd\fR(5)
を参照のこと。
.sp
このオプションは、 root が smbpasswd を実行するときだけ利用できる。
.RE
.PP
\-e
.RS 4
このオプションは、 ローカルの smbpasswd ファイル内の指定したユーザー username を\fB有効にすること\fRを指示する。 アカウントが無効になっていなければ、このオプションはなんの効果もない。 アカウントを有効にすることで、 このユーザーは再び SMB の認証が受けられるようになる。
.sp
smbpasswd ファイルが古い形式の場合、
smbpasswd
はアカウントの有効化に失敗する。 新旧のパスワードファイル形式についての詳細は、
\fBsmbpasswd\fR(5)
を参照のこと。
.sp
このオプションは、 root が smbpasswd を実行するときだけ利用できる。
.RE
.PP
\-D debuglevel
.RS 4
デバッグレベルを
\fIdebuglevel\fR
に設定する。
\fIdebuglevel\fR
は、0 から 10 までの整数である。 このパラメータを指定しないときのデフォルト値は 0 である。
.sp
この値を大きくするほど、 smbpasswd の動作に関するより詳細な情報がログファイルに記録される。 レベル 0 では、致命的なエラーと重大な警告のみが記録される。
.sp
1 より上のレベルは大量のログが生成されるので、 問題解決の時にのみ使用すべきである。 3 より上のレベルは開発者だけが利用するように設計されており、 莫大な量のログデータが生成される。 そのほとんどは非常に謎めいた内容となっている。
.RE
.PP
\-n
.RS 4
このオプションは、 ローカルの smbpasswd ファイル内の指定したユーザー username のパスワードをなくすよう指示する (すなわち、パスワードなしとなる)。 これは、 smbpasswd ファイルのパスワード保持領域の先頭部分に 「NO PASSWORD」という文字列を書き込むことで行なわれる。
.sp
注意: smbpasswd ファイル内でパスワードが「NO PASSWORD」に設定されると、 そのユーザーが Samba サーバーにログオンするためには、
\fIsmb\.conf\fR
ファイルの [global] セクションに下記のパラメータを設定しなければならない:
.sp
null passwords = yes
.sp
このオプションは、 root が smbpasswd を実行するときだけ利用できる。
.RE
.PP
\-r remote machine name
.RS 4
このオプションは、 変更したいパスワードがどのマシン上にあるかを指定することができる。 このパラメータが指定されていないと、デフォルトはローカルホストになる。
\fIremote machine name\fR
には、パスワード変更を試みるために接続する SMB/CIFS サーバーの NetBIOS 名を指定する。 この名前は、 Samba のすべてのプログラムで利用される標準的な名前解決方式によって、 IP アドレスへと変換される。 名前解決方式の設定については、
\fI\-R name resolve order\fR
パラメータを参照のこと。
.sp
パスワードの変更対象となるユーザーの名前は、 smbpasswd 実行時の UNIX のログイン名となる。 異なるユーザー名のパスワードの変更方法については、
\fI\-U username\fR
パラメータを参照のこと。
.sp
注意: Windows NT ドメインのパスワードを変更するには、 プライマリドメインコントローラーを指定しなければならない。 (バックアップドメインコントローラーは、 読み込み専用のユーザアカウントデータベースの複製を持っているだけで、 パスワードを変更することはできない)
.sp
\fI注意:\fR
Windows 95/98 は実際のパスワードデータベースを持っていないため、 Windows 95/98 マシンを指定してもパスワードの変更はできない。
.RE
.PP
\-R name resolve order
.RS 4
このオプションにより、smbpasswd のユーザーは、接続先のホストのNetBIOS 名の検索にどの名前解決サービスを使用するかを決めることができる。
.sp
オプションには、"lmhosts"、"host"、"wins"、"bcast"のいずれかを指定する。それぞれの名前解決は以下のように行われる。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBlmhosts\fR: Samba lmhosts ファイルで IP アドレスが検索される。lmhosts の行に NetBIOS 名にアタッチされるネームタイプがない場合(詳細については
\fBlmhosts\fR(5)
を参照)、ネームタイプがどれであるかは検索結果に影響しなくなる。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBhost\fR: システムの
\fI/etc/hosts \fR、NIS、DNS ルックアップを使用した、ホスト名 \- IP アドレス間の標準の名前解決が行われる。名前解決の方法の詳細な部分は、IRIX、Solaris といった OS によって変わる。\fI/etc/nsswitch\.conf\fR
で制御できる場合もある。この方法は、検索される NetBIOS 名のタイプが 0x20 (サーバー) である時にのみ使用できる点に注意。さもなければ指定しても無視される。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBwins\fR:
\fIwins server\fR
パラメータに指定された IP アドレスを持つ名前が検索される。WINS サーバーが指定されていなければ、無視される。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBbcast\fR:
\fIinterfaces\fR
パラメータに指定された既知のローカル･インターフェースそれぞれについてブロードキャストを行う。ターゲット・ホストがローカル接続サブネット上にある場合にしか使えないので、最も信頼性の低い名前解決法。
.sp
.RE
デフォルトの優先順位は、lmhosts、host、wins、bcast
となる。このパラメータがない場合、あるいは\fBsmb.conf\fR(5)
ファイルにエントリがない場合、この順序で名前解決方法が試行される。
.RE
.PP
\-m
.RS 4
このオプションは、 パスワードの変更対象のアカントがマシンアカウントであることを smbpasswd に指示する。 現在のところ、このオプションは、Samba が NT プライマリドメインコントローラーとして動作しているときに利用される。
.sp
このオプションは、 root が smbpasswd を実行するときだけ利用できる。
.RE
.PP
\-U username
.RS 4
このオプションは、
\fI\-r\fR
オプションと共に利用する。 リモートマシン上のパスワードを変更する場合に、
パスワード変更対象とする(リモート)マシン上のユーザー名を指定することができる。 これにより、 ユーザーがリモートマシン上で異なるユーザー名を持っている場合でも、 ユーザーはパスワードを変更することができる。
.RE
.PP
\-h
.RS 4
このオプションは、
smbpasswd
のヘルプを表示する。
.RE
.PP
\-s
.RS 4
このオプションを指定すると、 smbpasswd は寡黙 (すなわちプロンプトを出さない) になり、 新旧のパスワードを (passwd(1)
プログラムのように)
\fI/dev/tty\fR
からは読み込まず、 標準入力から読み込むようになる。 このオプションは smbpasswd を扱うスクリプトを書くときに有用となる。
.RE
.PP
\-w password
.RS 4
このオプションは、Samba がLDAPサポートを指定してコンパイルされているときのみ利用できる。
\fI\-w\fR
オプションは、
\fIldap admin dn\fR
に使用するパスワードを設定するために利用する。 注意: パスワードは LDAP 管理者の DN をキーにして
\fIsecrets\.tdb\fR
ファイルに格納される。 このため、
\fI\%smb.conf.5.html#\fR
パラメータの値を変更した場合は、 パスワードの更新も必要になる。
.RE
.PP
\-W
.RS 4
注意:このオプションは標準入力からパスワードを受け取ることを除いて、"\-w"と同じである。
.sp
このパラメータはSambaがLDAPサポート付きでコンパイルされている場合に のみ有効である。\fI\-W\fRスイッチは\fIldap admin dn\fRと ともに使われるパスワードを指定するのに使われる。 注意: パスワードは LDAP 管理者の DN をキーにして
\fIsecrets\.tdb\fR
ファイルに格納される。 このため、
\fI\%smb.conf.5.html#\fR
パラメータの値を変更した場合は、 パスワードの更新も必要になる。
.RE
.PP
\-i
.RS 4
このオプションは、 パスワードの変更対象のアカントがドメイン間信頼アカウントであることを smbpasswd に指示する。 現在のところ、このオプションは、Samba が NT プライマリドメインコントローラーとして動作しているときに利用される。 このアカウントには、 信頼する側のドメインに関する情報が含まれる。
.sp
このオプションは、 root が smbpasswd を実行するときだけ利用できる。
.RE
.PP
\-L
.RS 4
ローカルモードで起動する。
.RE
.PP
username
.RS 4
すべての
\fIroot 専用\fR
オプション用に、操作対象とするユーザーの名前を指定する。 ローカルの smbpasswd ファイルを直接修正する権限を持つ root だけがこのパラメータを指定することができる。
.RE
.SH "注意"
.PP
一般ユーザーが実行する場合、
smbpasswd
はローカルの smbd とクライアント/サーバーモードで通信するため、 機能するには smbd デーモンが動作していなければならない。 よくある問題として、 ローカルマシンで動作している
smbd
にアクセス可能なホストを制限するため
\fBsmb.conf\fR(5)
ファイルに
\fIallow hosts\fR
または
\fIdeny hosts\fR
パラメータを設定したときに、 「localhost」にアクセス許可を与えるのを忘れてしまうことがある。
.PP
なお、smbpasswd コマンドは、 Samba が暗号化パスワードを使うように設定してあるときのみ利用できる。
.SH "バージョン"
.PP
このマニュアルページは、Samba バージョン 3用に記述されている。
.SH "関連項目"
.PP
\fBsmbpasswd\fR(5),
\fBSamba\fR(7)\.
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、 Andrew Tridgell によって作られた。 Samba は現在、Linux カーネルが開発されているような方法でのオープンソースプロジェクトである Samba Team によって開発されている。
.PP
オリジナルの Samba のマニュアルページは Karl Auer によって書かれた。マニュアルページのソースは YODL 形式(別の、優秀なオープンソースソフトウェアで、ftp://ftp\.icce\.rug\.nl/pub/unix/にある)で変換され、Jeremy Allison によって Samba 2\.0 リリースのために更新された。 Samba 2\.2 のための DocBook 形式への変換は Gerald Carter が行った。 Samba 3\.0 のための DocBook XML 4\.2 形式の変換は Alexander Bokovoy によって行われた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.2\.4\-3\.2\.10 対応のものである。
.PP
このドキュメントの Samba 3\.0\.0 対応の翻訳は、さとうふみやす によって行なわれた。
.PP
このドキュメントの Samba 3\.2\.4\-3\.2\.10 対応の翻訳は、太田俊哉(ribbon@samba\.gr\.jp)によって行なわれた。
