'\" t
.\"     Title: smbspool
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 01/15/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"  Language: English
.\"
.TH "SMBSPOOL" "8" "01/15/2010" "Samba 3\&.3" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
smbspool \- 印刷ファイルを SMB プリンタへ送信する
.SH "SYNOPSIS"
.HP \w'\ 'u
smbspool {job} {user} {title} {copies} {options} [filename]
.SH "説明"
.PP
このツールは
\fBSamba\fR(7)システムの一部である。
.PP
smbspoolは印刷ファイルをSMBプリンタに送るための とても小さい印刷スプール用プログラムである。 Common UNIX Printing System との互換性のため コマンドライン引数は位置に依存するが、smbspool を任意の印刷システムで使ったり プログラムやスクリプトから使ったりすることもできる。
.PP
\fIDEVICE URI\fR
.PP
smbspool は印刷先を Uniform Resource Identifier ("URI") を用いて指定する。 手段は "smb" を用いる。この文字列はいくつかの形式を取ることができる:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
smb://server/printer
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
smb://workgroup/server/printer
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
smb://username:password@server/printer
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
smb://username:password@workgroup/server/printer
.sp
.RE
.PP
smbspool は 環境変数
\fBDEVICE_URI\fRからURI を得ようとする。 もし\fBDEVICE_URI\fRがなければ、smbspoolは、\(lqsmb://\(rq
が プログラム名であったらargv[0]を、そうでなければargv[1]をを参照する。
.PP
exec(2)
を使うプログラムは argv[0] に URI を渡すことができる。一方シェルスクリプトは smbspool を起動する以前に環境変数\fBDEVICE_URI\fR
を設定しなければならない。
.SH "オプション"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
job 引数 (argv[1]) にはジョブID番号が入るが、 現在 smbspool では使われていない。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
user 引数 (argv[2]) には印刷ユーザの名前が入るが、 現在 smbspool では使われていない。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
title 引数 (argv[3]) には ジョブのタイトル文字列が入り、印刷ジョブを送信する時に リモートファイル名として渡される。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
copies 引数 (argv[4]) には 名前が指定されたファイルを印刷する部数が入る。 もしファイル名が指定されていなければ smbspool は この引数を使用しない。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
option 引数 (argv[5]) には 印刷オプションが単一文字列で入るが、現在 smbspool では使われていない。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
filename 引数 (argv[6]) には 印刷するファイルの名前が入る。もしこの引数が指定されなければ 印刷ファイルは標準入力から読み込まれる。
.SH "バージョン"
.PP
このマニュアルページはバージョン3のSamba用である。
.SH "関連項目"
.PP
\fBsmbd\fR(8)
と
\fBSamba\fR(7)。
.SH "著者"
.PP
smbspool
は、Easy Software Products の Michael Sweet によって書かれた。
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、 Andrew Tridgell によって作られた。Samba は現在 Linux カーネルが 開発されているような方法でのオープンソースプロジェクトである Samba Team によって開発されている。
.PP
オリジナルの Samba の マニュアルページは Karl Auer によって書かれた。 マニュアルページは YODL 形式(別の、優秀なオープンソースソフトウェアで、
ftp://ftp\&.icce\&.rug\&.nl/pub/unix/にある) で変換され、Jeremy Allison によって Samba 2\&.0 リリースのために更新された。 Samba 2\&.2 のための DocBook 形式への変換は Gerald Carter が行った。 Samba 3\&.0 のための DocBook XML 4\&.2 形式への変換は Alexander Bokovoy が行った。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.2\&.4\-3\&.3\&.10 対応のものである。
.PP
このドキュメントの Samba 3\&.0\&.0 対応の翻訳は、ちかましゅうへい によって行なわれた。
.PP
このドキュメントの Samba 3\&.2\&.4\-3\&.3\&.10 対応の翻訳は、太田俊哉(ribbon@samba\&.gr\&.jp)によって行なわれた。
