'\" t
.\"     Title: smbstatus
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/02/2010
.\"    Manual: ユーザコマンド
.\"    Source: Samba 3.3
.\"  Language: English
.\"
.TH "SMBSTATUS" "1" "03/02/2010" "Samba 3\&.3" "ユーザコマンド"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
smbstatus \- 現在の Samba の接続を報告
.SH "SYNOPSIS"
.HP \w'\ 'u
smbstatus [\-P] [\-b] [\-d\ <debug\ level>] [\-v] [\-L] [\-B] [\-p] [\-S] [\-s\ <configuration\ file>] [\-u\ <username>]
.SH "説明"
.PP
このツールは
\fBSamba\fR(7)システムの一部である。
.PP
smbstatus
は現在の Samba への接続を 表示するだけの非常に単純なプログラムである。
.SH "オプション"
.PP
\-P|\-\-profile
.RS 4
Samba が profiling オプション付きでコンパイルされた場合に、profile された共有メモリの内容だけを出力する。
.RE
.PP
\-b|\-\-brief
.RS 4
簡単な出力を表示する。
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
は0から10までの整数値である。 既定値の値は、パラメータが設定されていなければ0である。
.sp
この値を大きくするほど、サーバの動作に関するより詳細な情報が ログファイルに記録される。レベル 0 では、致命的なエラーと重大な警告 のみが記録される。レベル 1 は日々の運用に適しており、少量の稼働状況 に関する情報を生成する。
.sp
1 より上のレベルは大量のログが生成されるので、問題解決の時にのみ 使用すべきである。 3 より上のレベルは開発者だけが利用するように設計されて おり、莫大な量のログデータが生成される。そのほとんどは非常に謎めいた内容 となっている
.sp
このパラメータの指定は、smb\&.confファイル中の、
\m[blue]\fB\%smb.conf.5.html#\fR\m[]
パラメータの 指定よりも優先する。
.RE
.PP
\-V
.RS 4
プログラムのバージョン番号を表示する。
.RE
.PP
\-s <configuration file>
.RS 4
サーバーが必要とする詳細な設定を含む設定ファイルを 指定する。このファイルには、サーバーが提供するサービスに関する記述や、 どの printcap ファイルを利用するかといった情報が含まれている。詳細は
smb\&.conf
を参照のこと。設定ファイルの名前の既定値は、コンパイル時 に決定される。
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
ログ/デバッグファイルのファイル名。拡張子として
\fB"\&.progname"\fR
が追加される(例えば log\&.smbclient, log\&.smbd,など)。ログファイルはクライアントによって削除されることはない。
.RE
.PP
\-v|\-\-verbose
.RS 4
詳細な出力を表示する。
.RE
.PP
\-L|\-\-locks
.RS 4
ロックのリストだけを表示する。
.RE
.PP
\-B|\-\-byterange
.RS 4
バイト範囲のロック(byte range lock)を含めて表示する
.RE
.PP
\-p|\-\-processes
.RS 4
\fBsmbd\fR(8)
のプロセスの一覧を表示し、終了する。 スクリプト作成時に有用である。
.RE
.PP
\-S|\-\-shares
.RS 4
共有の一覧だけを表示する。 (訳注: "共有の" は "接続の" としたほうが正しい。)
.RE
.PP
\-h|\-\-help
.RS 4
コマンドラインオプションの要約を表示する。
.RE
.PP
\-u|\-\-user=<username>
.RS 4
\fIusername\fR
で 指定されたユーザに関する情報だけを表示する。
.RE
.SH "バージョン"
.PP
このマニュアルページはバージョン3のSamba用である。
.SH "関連項目"
.PP
\fBsmbd\fR(8)
と
\fBsmb.conf\fR(5)\&.
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、 Andrew Tridgell によって作られた。Samba は現在 Linux カーネルが 開発されているような方法でのオープンソースプロジェクトである Samba Team によって開発されている。
.PP
オリジナルの Samba の マニュアルページは Karl Auer によって書かれた。 マニュアルページは YODL 形式(別の、優秀なオープンソースソフトウェアで、
ftp://ftp\&.icce\&.rug\&.nl/pub/unix/にある) で変換され、Jeremy Allison によって Samba 2\&.0 リリースのために更新された。 Samba 2\&.2 のための DocBook 形式への変換は Gerald Carter が行った。 Samba 3\&.0 のための DocBook XML 4\&.2 形式への変換は Alexander Bokovoy が行った。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.2\&.4\-3\&.3\&.10 対応のものである。
.PP
このドキュメントの Samba 3\&.0\&.0 対応の翻訳は、ちかましゅうへい によって行なわれた。
.PP
このドキュメントの Samba 3\&.2\&.4\-3\&.3\&.10 対応の翻訳は、太田俊哉(ribbon@samba\&.gr\&.jp)によって行なわれた。
