'\" t
.\"     Title: smbtree
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 04/02/2012
.\"    Manual: ユーザコマンド
.\"    Source: Samba 3.4
.\"  Language: English
.\"
.TH "SMBTREE" "1" "04/02/2012" "Samba 3\&.4" "ユーザコマンド"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
smbtree \- テキストベースの SMB ネットワークブラウザ
.SH "SYNOPSIS"
.HP \w'\ 'u
smbtree [\-b] [\-D] [\-S]
.SH "説明"
.PP
このツールは、\fBSamba\fR(7)システムの一部である。
.PP
smbtree
はテキストモードの SMB ネットワークブラウザである。 Windows にある「ネットワークコンピュータ」あるいは「マイネットワーク」 と類似の機能を持ち、 既知のドメイン、そのドメインに属するサーバー、 そしてサーバー上の共有のすべてをツリーで表示する。
.SH "オプション"
.PP
\-b
.RS 4
マスターブラウザに問い合わせるのではなく、ネットワーク ノードにブロードキャストを送信することで問い合わせる。
.RE
.PP
\-D
.RS 4
ブロードキャストあるいはマスターブラウザから得たドメインの一覧だけを表示する。
.RE
.PP
\-S
.RS 4
ブロードキャストあるいはマスターブラウザから得たドメインと応答したサーバーの一覧だけを表示する。
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
は0から10までの整数値である。 既定値の値は、パラメータが設定されていなければ0である。
.sp
この値を大きくするほど、サーバの動作に関するより詳細な情報が ログファイルに記録される。レベル 0 では、致命的なエラーと重大な警告 のみが記録される。レベル 1 は日々の運用に適しており、少量の稼働状況 に関する情報を生成する。
.sp
1 より上のレベルは大量のログが生成されるので、問題解決の時にのみ 使用すべきである。 3 より上のレベルは開発者だけが利用するように設計されて おり、莫大な量のログデータが生成される。そのほとんどは非常に謎めいた内容 となっている
.sp
このパラメータの指定は、smb\&.confファイル中の、
\m[blue]\fB\%smb.conf.5.html#\fR\m[]
パラメータの 指定よりも優先する。
.RE
.PP
\-V
.RS 4
プログラムのバージョン番号を表示する。
.RE
.PP
\-s <configuration file>
.RS 4
サーバーが必要とする詳細な設定を含む設定ファイルを 指定する。このファイルには、サーバーが提供するサービスに関する記述や、 どの printcap ファイルを利用するかといった情報が含まれている。詳細は
smb\&.conf
を参照のこと。設定ファイルの名前の既定値は、コンパイル時 に決定される。
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
ログ/デバッグファイルのファイル名。拡張子として
\fB"\&.progname"\fR
が追加される(例えば log\&.smbclient, log\&.smbd,など)。ログファイルはクライアントによって削除されることはない。
.RE
.PP
\-N
.RS 4
このオプションを指定すると、クライアントはユーザーへの パスワード入力要求をしなくなる。パスワードが必要ないサービスにアクセスする ときに有用である。
.sp
コマンドラインにパスワードが指定されておらず、このオプションも指定 されていないと、クライアントはパスワードを要求する。
.sp
もしも、パスワードがコマンドライン上で指定され、このオプションも 定義されていた場合、コマンドライン上のパスワードは無視され、パスワードは 使われない。
.RE
.PP
\-k
.RS 4
Kerberos による認証を試みる。アクティブディレクトリ環境でのみ有効である。
.RE
.PP
\-A|\-\-authentication\-file=filename
.RS 4
このオプションは、指定したファイルから、接続に使用する ユーザー名とパスワードを読み込むために使用する。ファイルの形式は次の通り:
.sp
.if n \{\
.RS 4
.\}
.nf
username = <value>
password = <value>
domain   = <value>
.fi
.if n \{\
.RE
.\}
.sp
ファイルのパーミッションを確認し、ほかのユーザーから参照されない ように注意すること。
.RE
.PP
\-U|\-\-user=username[%password]
.RS 4
SMB のユーザー名、またはユーザー名とパスワードを指定する。
.sp
もしも %password を指定しないと、ユーザーにパスワードの入力を求める。 クライアントはまず初めに\fBUSER\fR、\fBLOGNAME\fRの順に 環境変数の存在を調べ、もしもどちらかが存在するならば、その文字列を大文字にする。 環境変数が存在しない場合、ユーザ名として\fBGUEST\fRが用いられる。
.sp
このほかに、平文のユーザー名とパスワードを記述した認証ファイルを使用する オプションがある。このオプションは主にスクリプト向けに用意されており、認証情報を コマンドラインや環境変数に含めたくない場合に有用である。このオプションを利用する ときは、ファイルのパーミッションを確認し、ほかのユーザーから参照されないように 注意すること。詳細は\fI\-A\fRオプションを参照のこと。
.sp
パスワードをスクリプトに含める場合は注意すること。多くのシステムでは、実行 中のプロセスのコマンドラインはpsコマンドで参照することが できてしまう。安全のため、必ず、rpcclientを使用して、 パスワード入力を要求し、直接入力するようにしておくこと。
.RE
.PP
\-h|\-\-help
.RS 4
コマンドラインオプションの要約を表示する。
.RE
.SH "バージョン"
.PP
このマニュアルページは、Samba スイートのバージョン 3用である。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、 Andrew Tridgell によって作られた。 Samba は現在、Linux カーネルが開発されているような方法でのオープンソースプロジェクトである Samba Team によって開発されている。
.PP
smbtree のマニュアルページは Jelmer Vernooij により書かれた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.2\&.4 \- 3\&.4\&.15 対応のものである。
.PP
このドキュメントの Samba 3\&.0\&.0 \- 3\&.4\&.15 対応の翻訳は さとうふみやすによって行なわれた。
