'\" t
.\"     Title: swat
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.5
.\"  Language: English
.\"
.TH "SWAT" "8" "11/12/2010" "Samba 3\&.5" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
swat \- Samba Web 管理ツール
.SH "SYNOPSIS"
.HP \w'\ 'u
swat [\-s\ <Samba\ 設定ファイル>] [\-a] [\-P]
.SH "説明"
.PP
このツールは
\fBSamba\fR(7)システムの一部である。
.PP
swat
は、Samba 管理者が Web ブラウザを使って複雑な
\fBsmb.conf \fR(5)
の設定を行うことを可能にする。それに加え、swat
の設定ページには、smb\&.conf
中で設定可能な全てのオプションへのリンクがあり、 管理者が設定変更の影響を簡単に調べられるようになっている。
.PP
swat
は
inetd
から実行される。
.SH "オプション"
.PP
\-s smb configuration file
.RS 4
デフォルトの設定ファイルのパスは、 コンパイル時に設定される。設定されたファイルには、
\fBsmbd\fR(8)
サーバに必要な詳細な設定が記述される。このファイルが
swat
によって修正されるファイルである。 ファイルには、そのサーバが提供する全てのサービスの記述に加え、 printcap ファイルの位置のようなサーバ固有の情報も含まれる。 詳細情報については、smb\&.conf
を参照のこと。
.RE
.PP
\-a
.RS 4
このオプションは、認証機能を無効にし、swat
をデモモードにする。 このモードでは、誰でも
smb\&.conf
ファイルを修正する事ができてしまう。
.sp
\fI警告: 運用中のサーバでは、 このオプションを絶対に有効にしないこと。 \fR
.RE
.PP
\-P
.RS 4
このオプションは、リードオンリユーザを、パスワード管理ページに制限する。
swatは次に、"View"と"Status"メニューボタンを見せることなしに ユーザのパスワードを変更することが出来る。
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
は0から10までの整数値である。 既定値の値は、パラメータが設定されていなければ0である。
.sp
この値を大きくするほど、サーバの動作に関するより詳細な情報が ログファイルに記録される。レベル 0 では、致命的なエラーと重大な警告 のみが記録される。レベル 1 は日々の運用に適しており、少量の稼働状況 に関する情報を生成する。
.sp
1 より上のレベルは大量のログが生成されるので、問題解決の時にのみ 使用すべきである。 3 より上のレベルは開発者だけが利用するように設計されて おり、莫大な量のログデータが生成される。そのほとんどは非常に謎めいた内容 となっている
.sp
このパラメータの指定は、smb\&.conf
ファイル中の、
\m[blue]\fBlog level\fR\m[]
パラメータの指定よりも優先する。
.RE
.PP
\-V
.RS 4
プログラムのバージョン番号を表示する。
.RE
.PP
\-s <configuration file>
.RS 4
サーバーが必要とする詳細な設定を含む設定ファイルを 指定する。このファイルには、サーバーが提供するサービスに関する記述や、 どの printcap ファイルを利用するかといった情報が含まれている。詳細は
smb\&.conf
を参照のこと。設定ファイルの名前の既定値は、コンパイル時 に決定される。
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
ログ/デバッグファイルのファイル名。拡張子として
\fB"\&.progname"\fR
が追加される(例えば log\&.smbclient, log\&.smbd,など)。ログファイルはクライアントによって削除されることはない。
.RE
.PP
\-h|\-\-help
.RS 4
コマンドラインオプションの要約を表示する。
.RE
.SH "インストール"
.PP
Swat は、ほとんどのディストリビューションのバイナリパッケージに 含まれている。 その場合パッケージマネージャがインストールと設定を行う。 このセクションは一から swat をコンパイルした人のみを対象としている。
.PP
SWAT をコンパイルした後、make install
を実行して
swat
バイナリといろいろなヘルプとイメージ ファイルをインストールする必要がある。 デフォルトのインストールでは以下のものが入れられる:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
/usr/local/samba/bin/swat
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
/usr/local/samba/swat/images/*
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
/usr/local/samba/swat/help/*
.sp
.RE
.SS "Inetd Installation"
.PP
inetd
から SWAT を起動するには、
/etc/inetd\&.conf
と
/etc/services
を修正する必要がある。
.PP
/etc/services
には、 以下の一行を加える:
.PP
swat 901/tcp
.PP
NIS/YP および LDAP ユーザへの注意: ローカルな
/etc/services
ファイルの代わりに、NIS サービスマップを再構築する必要があるかも知れない。
.PP
ポート番号は、1024 より小さい番号のポートで現在使用中でないもので あればなんでも良い (1024 より大きいポートを用いる事は、
inetd
デーモンの実装内容によっては、 セキュリティホールを提供してしまう)。
.PP
/etc/inetd\&.conf
については、 以下のような行を追加すること:
.PP
swat stream tcp nowait\&.400 root /usr/local/samba/bin/swat swat
.PP
/etc/services
と
/etc/inetd\&.conf
を編集したら、inetd に HUP シグナルを送ること。それには
kill \-1 PID
のように入力する。 ここでPIDは inetd デーモンのプロセスIDを示す。
.SH "起動"
.PP
SWAT を起動するには、 お好みのWebブラウザを起動して、 "http://localhost:901/" を開く。
.PP
IP 的に接続可能なマシンから SWAT を起動することも可能であるが、 パスワードは伝送路上を平文で送られているため、別マシンからの接続を 行なうとパスワードを盗聴される可能性があることに注意。
.SH "関連ファイル"
.PP
/etc/inetd\&.conf
.RS 4
このファイルには、メタデーモンのための適切な 起動情報が含まれている。
.RE
.PP
/etc/services
.RS 4
このファイルには、サービス名 (例: SWAT) とサービスポート (例: 901)、そのプロトコルの種類 (例: tcp) のマッピングに関する情報が含まれている。
.RE
.PP
/usr/local/samba/lib/smb\&.conf
.RS 4
これは swat が編集する
\fBsmb.conf\fR(5)
サーバ設定ファイルのデフォルトの位置である。 他によくあるインストール先としては
/usr/samba/lib/smb\&.conf
や
/etc/smb\&.conf
がある。 このファイルにはサーバがクライアントに提供する全てのサービスに ついての記述がある。
.RE
.SH "警告"
.PP
swat
は
\fB smb.conf\fR(5)
ファイルを書き換えてしまう。エントリは再配置され、コメントや
\fIinclude=\fR、\fIcopy=\fR
オプションは削除されてしまう。 既に念入りに手をかけて作成した
smb\&.conf
を持っている場合は、事前にバックアップしておくか、swat を使わないこと!
.SH "バージョン"
.PP
このマニュアルページは Samba バージョン 3用である。
.SH "関連項目"
.PP
inetd(5),
\fBsmbd\fR(8),
\fBsmb.conf\fR(5)
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、 Andrew Tridgell によって作成された。現在 Samba は Samba Team によって、 Linux カーネルの開発と同様の オープンソースプロジェクトとして開発が 行なわれている。
.PP
オリジナルの Samba マニュアルページは Karl Auer によって作成された。マニュアルページは YODL 形式 (ftp://ftp\&.icce\&.rug\&.nl/pub/unix/
で入手可能な優れたオープンソースソフトウェア) に変換され、 Samba 2\&.0 リリースに伴い、Jeremy Allison によって更新された。 Samba 2\&.2 における DocBook 形式への変換は、Gerald Carter によって行なわれた。 Samba 3\&.0 における DocBook XML 4\&.2 への変換は Alexander Bokovoy によって行われた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.2\&.4 \- 3\&.5\&.6 対応のものである。
.PP
このドキュメントの Samba 3\&.0\&.0 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
たかはし もとのぶ(monyo@samba\&.gr\&.jp)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
山田 史朗 (shiro@miraclelinux\&.com)
.sp
.RE
によって行なわれた。
.PP
このドキュメントの Samba 3\&.2\&.4 \- 3\&.5\&.6 対応の翻訳は 太田俊哉(ribbon@samba\&.gr\&.jp)によって行われた。
