'\" t
.\"     Title: tdbbackup
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/20/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"  Language: English
.\"
.TH "TDBBACKUP" "8" "03/20/2010" "Samba 3\&.3" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
tdbbackup \- Samba の \&.tdb ファイルのバックアップや整合性の確認を行うツール
.SH "SYNOPSIS"
.HP \w'\ 'u
tdbbackup [\-s\ suffix] [\-v] [\-h]
.SH "説明"
.PP
このツールは
\fBSamba\fR(1)
システムの一部である。
.PP
tdbbackup
は Samba の \&.tdb ファイルのバックアップを とるために使用される。また Samba の起動前にこのツールを使うことで、ファイルの 破損が確認された場合には、以前のバックアップファイルから復元することもできる。
.SH "オプション"
.PP
\-h
.RS 4
help を表示する。
.RE
.PP
\-s suffix
.RS 4

\-s
オプションは Administrator にバックアップファイルの 拡張子を指定できる権限を与える。これにより、Administrator はバックアップのたびに新しいサフィックスをつけることができ、TDB のバックアップの履歴を管理することが可能になる。
.RE
.PP
\-v
.RS 4

\-v
はデータベースに対しダメージ (破損したデータ) がないか確認し、もしダメージが発見された場合はバックアップから復元する。
.RE
.SH "コマンド"
.PP
\fI概要\fR
.PP

tdbbackupユーティリティは任意のタイミングで安全に動作することが出来る。 Sambaが動作中でもtdbファイルの整合性を検証できるよう、任意のタイミングで使えるように設計されて いる。典型的な使用方法は :
.PP
tdbbackup [\-s suffix] *\&.tdb
.PP
Samba を再起動する前に以下のコマンドを実行することで \&.tdb ファイルの整合性を確認できる :
.PP
tdbbackup \-v [\-s suffix] *\&.tdb
.PP
Samba の \&.tdb ファイルはいろいろな場所に保存されているため、システムにある全ての \&.tdb ファイルをバックアップをとるようにする。重要なファイルは :
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

secrets\&.tdb
\- 通常のディレクトリの位置は /usr/local/samba/private で、システムによっては /etc/samba になる。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

passdb\&.tdb
\- 通常のディレクトリの位置は /usr/local/samba/private で、システムによっては /etc/samba になる。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

*\&.tdb
通常のディレクトリの位置は /usr/local/samba/var で、システムによっては /var/cache や /var/lib/samba になる。
.SH "バージョン"
.PP
このマニュアルページは Samba バージョン 3用である。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連ユーティリティは、Andrew Tridgell によって作成された。現在 Samba は、Samba Team によって Linux カーネルの開発と同様に、オープンソースプロジェクトとして開発されている。
.PP
tdbbackup の man page は John H Terpstra によって作成された。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.2\&.4\-3\&.3\&.12 対応のものである。
.PP
このドキュメントの Samba 3\&.0\&.0 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
山田 史朗 (shiro@miraclelinux\&.com)
.sp
.RE
によって行なわれた。
.PP
このドキュメントの Samba 3\&.2\&.4\-3\&.3\&.12 対応の翻訳は 太田俊哉(ribbon@samba\&.gr\&.jp)によって行われた。
