.\"     Title: tdbtool
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/04/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"
.TH "TDBTOOL" "8" "01/04/2009" "Samba 3\.2" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
tdbtool - TDB ファイルの内容を操作する
.SH "SYNOPSIS"
.HP 1
tdbtool
.HP 1
tdbtool \fITDBFILE\fR [\fIコマンド\fR...]
.SH "説明"
.PP
このツールは
\fBsamba\fR(1)
システムの一部として提供されている。
.PP
tdbtool
は TDB (Trivial DataBase) ファイルの内容を表示したり変更したりするツール である。後述のコマンドを会話的に投入したり、コマンドラインで指定したり することができる。
.SH "コマンド"
.PP
\fBcreate\fR \fITDBFILE\fR
.RS 4
\fITDBFILE\fR
という名前の新しいデータベースを生成する。
.RE
.PP
\fBopen\fR \fITDBFILE\fR
.RS 4
\fITDBFILE\fR
という名前を持つ既存のデータベースを開く。
.RE
.PP
\fBerase\fR
.RS 4
現在のデータベースを消去する。
.RE
.PP
\fBdump\fR
.RS 4
現在のデータベースを文字列としてダンプする。
.RE
.PP
\fBcdump\fR
.RS 4
現在のデータベースを接続レコードとしてダンプする。
.RE
.PP
\fBkeys\fR
.RS 4
現在のデータベースのキーを文字列としてダンプする。
.RE
.PP
\fBhexkeys\fR
.RS 4
現在のデータベースのキーを 16 進数の値としてダンプする。
.RE
.PP
\fBinfo\fR
.RS 4
現在のデータベースに関する概要を表示する。
.RE
.PP
\fBinsert\fR \fIKEY\fR \fIDATA\fR
.RS 4
現在のデータベースにレコードを挿入する。
.RE
.PP
\fBmove\fR \fIKEY\fR \fITDBFILE\fR
.RS 4
現在のデータベースにあるレコードを
\fITDBFILE\fR
に移動する。
.RE
.PP
\fBstore\fR \fIKEY\fR \fIDATA\fR
.RS 4
現在のデータベースにレコードを格納（置換）する。
.RE
.PP
\fBshow\fR \fIKEY\fR
.RS 4
キーによりレコードを表示する。
.RE
.PP
\fBdelete\fR \fIKEY\fR
.RS 4
キーによりレコードを削除する。
.RE
.PP
\fBlist\fR
.RS 4
現在のデータベースのハッシュテーブルと空き領域リストを表示する。
.RE
.PP
\fBfree\fR
.RS 4
現在のデータベースの概要と空き領域リストを表示する。
.RE
.PP
\fB!\fR \fICOMMAND\fR
.RS 4
指定されたシステムコマンドを実行する。
.RE
.PP
\fBfirst\fR
.RS 4
現在のデータベースで先頭レコードを表示する。
.RE
.PP
\fBnext\fR
.RS 4
現在のデータベースで次のレコードを表示する。
.RE
.PP
\fBquit\fR
.RS 4
tdbtool
を終了する。
.RE
.SH "警告"
.PP
Samba の TDB ファイルの内容は Samba の実装に依存しており、
tdbtool
で変更してはならない。
.SH "バージョン"
.PP
このマニュアルは Sambaバージョン 3\.0\.25 用である。
.SH "作者"
.PP
オリジナルの Samba ソフトウェアおよび関連するユーティリティーは、 Andrew Tridgell によって書かれた。現在は Samba は Samba Team によって Linux カーネルの開発と同様に、オープンソースプロジェクトとして 開発されている。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.2\.4\-3\.2\.6 対応のものである。
.PP
このドキュメントの Samba 3\.2\.4\-3\.2\.6 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
堀田 倫英(hotta@net\-newbie\.com)
.sp
.RE
によって行なわれた。
