'\" t
.\"     Title: umount.cifs
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/16/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.5
.\"  Language: English
.\"
.TH "UMOUNT\&.CIFS" "8" "11/16/2010" "Samba 3\&.5" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
umount.cifs \- ルート権限のない一般ユーザが自身でマウントした Common Internet File System (CIFS) をアンマウントする。
.SH "SYNOPSIS"
.HP \w'\ 'u
umount\&.cifs {mount\-point} [\-nVvhfle]
.SH "説明"
.PP
このツールは
\fBsamba\fR(7)
システムの一部である。
.PP
umount\&.cifs は Linux の CIFS ファイルシステムをアンマウントする。 実際には
\fBumount\fR(8)
コマンドが /sbin ディレクトリにある umount\&.cifs を間接的に起動している。 但し、umount に \-i オプションを指定した場合はこの限りではなく、 その場合は umount\&.cifs のような umount 補助プログラムは実行されない。 umount\&.cifs コマンドは Linux でのみ機能する。但し、カーネルが cifs ファイルシステムに対応している必要がある。 CIFS プロトコルは、SMB プロトコルの後継で、 よく知られた Open Source サーバである Samba 以外にも、殆どの Windows サーバや他の多くの商用サーバ、NAS 製品等で利用されている。
.PP
umount\&.cifs ユーティリティは、 一致する UNC 名 (サーバ側のネットワーク資源) からローカルディレクトリ
\fImount\-point\fR
を切り離し、 関連づけられたカーネル資源を解放する。 umount\&.cifs のファイルモードを setuid ルートに設定する (又はファイル /etc/permissions を同様の設定を行なう) ことで、 書込み許可を持つディレクトリへの共有を非ルートユーザが umount 出来るようになる。 ルートユーザに実行された ルートユーザのみがアンマウント可能であるかどうかや、 /etc/fstab で明示的に指定されたエントリによってマウントやアンマウントを行なえるかどうかは、 典型的に umount\&.cifs ユーティリティの必要とするところではない。 詳細は
\fBfstab\fR(5)
を参照のこと。
.SH "オプション"
.PP
\-\-verbose
.RS 4
デバッグ情報も表示する
.RE
.PP
\-\-no\-mtab
.RS 4
アンマウントが正しく完了した場合でも mtab を更新しない (/proc/mounts は正しい情報を表示し続ける)
.RE
.SH "備考"
.PP
(ルートユーザは常にアンマウントを実行可能なので) このコマンドは通常 setuid を設定して使われることを意図されている。 umount\&.cifs を使う代わりに、 特定のユーザがマウントやアンマウント出来るように /etc/fstab に特定のエントリを追加しても構わない。
.SH "設定方法"
.PP
設定を変更したり、cifs vfs 用のデバッグ情報を読んだりする場合は、 基本的に Linux /proc ファイルシステム経由で行なう。 ディレクトリ
/proc/fs/cifs
には、 デバッグ情報を表示出来る様々な設定ファイルや擬似ファイルがある。 より詳細な情報は、 カーネルファイル
fs/cifs/README
を参照のこと。
.SH "バグ"
.PP
現時点では、umount\&.cifs は umount ユーティリティと同一のロックを用いるマウントテーブルをロックしない。 このため、異なるプロセスから複数のアンマウントを実行しようとしてはならない。 (特に cifs マウントとそれ以外の種類のファイルシステムのマウントを同時にアンマウントしないように。)
.PP
同一のマウントポイントを cifs 複数回マウントした場合、 umount\&.cifs は /etc/mtab の中でマッチするエントリのうち最後のものをマウントテーブルから削除するのではなく、 マッチするエントリの全てを削除する。 (実際には、umount\&.cifs は最後のものしかアンマウントしていない。) 疑似ファイル /proc/mounts は正しい情報を表示するので、 /etc/mtab にエントリが存在しなくても外のアンマウントを妨げることはない。
.PP
バグ報告への対応では、まず最新版で試してみることを提案することがよくある。 それを試した後、 バグ報告の際には関連するソフトウェアの使用中バージョンを必ず報告に含めることを強くお願いしたい。 最低限、umount\&.cifs (umount\&.cifs \-V を参照)、カーネル (/proc/version を参照)、 及び接続したいサーバタイプは含めておいて欲しい。
.SH "バージョン"
.PP
このマニュアルページは cifs vfs ファイルシステムバージョン 1\&.34 (Linux kernel 2\&.6\&.12 辺り) 用に書かれている。
.SH "関連項目"
.PP
Linux カーネルソースツリーの Documentation/filesystems/cifs\&.txt 及び fs/cifs/README には、 追加のオプションや情報が書かれている。
.PP
\fBmount.cifs\fR(8)
.SH "著者"
.PP
Steve French
.PP
文法は umount ユーティリティにほぼ準拠し、マニュアルページは mount\&.cifs\&.8 にほぼ準拠する。 本マニュアルページは Steve French が作成した。
.PP
Linux cifs vfs 及びユーザ空間ツール
\fIumount\&.cifs\fR
のメンテナは
Steve French
である。 これらプログラムに関する問い合わせは、
Linux CIFS メーリングリスト
まで。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.2\&.4 \- 3\&.5\&.6 対応のものである。
.PP
このドキュメントの Samba 3\&.2\&.4 \- 3\&.5\&.6 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
しらいたかし
.sp
.RE
によって行なわれた。
