.\"     Title: vfs_smb_traffic_analyzer
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 08/13/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"
.TH "VFS_SMB_TRAFFIC_ANAL" "8" "08/13/2009" "Samba 3\.2" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_smb_traffic_analyzer - ヘルパアプリケーションに対して、ソケット経由でのSamba VFS読み出し 書き込み操作のログを取る
.SH "SYNOPSIS"
.HP 1
vfs objects = smb_traffic_analyzer
.SH "説明"
.PP
このVFSモジュールは、\fBsamba\fR(7)システムの一部である。
.PP
vfs_smb_traffic_analyzer
VFSモジュールは、 Sambaサーバ上のクライアント書き込みと読み出し操作のログを取り、 このデータを、SQLデータベースに送る、ヘルパプログラムに対して ソケット上で送信する。ヘルパプログラムの詳細な情報は、 http://holger123\.wordpress\.com/smb\-traffic\-analyzer/ にあるプロジェクトホームページから得られる。
.PP
vfs_smb_traffic_analyzerは現在、以下のVFS操作を 理解する:
.IP "" 4
write
.IP "" 4
pwrite
.IP "" 4
read
.IP "" 4
pread
.PP
vfs_smb_traffic_analyzer
sends the following data in a fixed format seperated by a comma through either an internet or a unix domain socket:
.PP
vfs_smb_traffic_analyzerは、コンマによって分離された 固定フォーマットで、以下のデータを、インターネットまたはUNIXドメインソケット を通じて送る:
.sp
.RS 4
.nf
	BYTES|USER|DOMAIN|READ/WRITE|SHARE|FILENAME|TIMESTAMP
	
.fi
.RE
.PP
レコードの詳細:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
BYTES
\- VFS操作のバイト単位の長さ
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
USER
\- 操作を開始したユーザ
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
DOMAIN
\- ユーザのドメイン
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
READ/WRITE
\- "W"なら書き込み操作、"R"なら読み出し操作
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
SHARE
\- VFS操作が行われた共有の名前
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FILENAME
\- VFS操作によって使われたファイルの名前
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
TIMESTAMP
\- VFS操作が行われたことを示す "yyyy\-mm\-dd hh\-mm\-ss\.ms" での時間
.sp
.RE
.PP
このモジュールはスタック可能である。
.SH "オプション"
.PP
smb_traffic_analyzer:mode = STRING
.RS 4
もしも、STRINGが "unix_domain_socket" に一致するならば、モジュール は/var/tmp/stadsocketに位置するunixドメインソケットを使い、もしも、 STRINGにそのほかの文字列か、未定義ならば、モジュールは、データの転送 のためにインターネットドメインソケットを使う。
.RE
.PP
smb_traffic_analyzer:host = STRING
.RS 4
モジュールはホスト名がSTRINGという名前のシステムにデータを送る。
.RE
.PP
smb_traffic_analyzer:port = STRING
.RS 4
モジュールはSTRING中で指定されたTCPポートにデータを送る。
.RE
.PP
smb_traffic_analyzer:anonymize_prefix = STRING
.RS 4
モジュールは、STRINGで与えられたプレフィックスと単純なハッシュ値で ユーザ名を置き換える。
.RE
.PP
smb_traffic_analyzer:total_anonymization = STRING
.RS 4
もしもSTRINGが\'yes\'と一致するのであれば、モジュールは 追加のハッシュ値を生成しないで、smb_traffic_analyzer:anonymize_prefix オプションによって与えられる文字列でユーザ名を置き換える。これは 任意の転送データが単一のユーザにマッピングされることを意味し、 ユーザに関連するデータの全体的な匿名化を導く。
.RE
.SH "使用例"
.PP
unixドメインソケットを使い、共有"example_share"上でモジュールを走らせる
.sp
.RS 4
.nf
	\fI[example_share]\fR
	\fIpath = /data/example\fR
	\fIvfs objects = smb_traffic_analyzer\fR
	\fIsmb_traffic_analyzer:mode = unix_domain_socket\fR
	
.fi
.RE
.PP
The module running on share "example_share", using an internet socket, connecting to host "examplehost" on port 3491\.
.PP
インターネットソケットを使い、ポート3491のホスト名"examplehost"に対して 接続し、共有"example_share"上でモジュールを走らせる
.sp
.RS 4
.nf
	\fI[example_share]\fR
	\fIpath = /data/example\fR
	\fIvfs objects = smb_traffic_analyzer\fR
	\fIsmb_traffic_analyzer:host = examplehost\fR
	\fIsmb_traffic_analyzer:port = 3491\fR
	
.fi
.RE
.PP
The module running on share "example_share", using an internet socket, connecting to host "examplehost" on port 3491, anonymizing user names with the prefix "User"\.
.PP
インターネットソケットを使い、ポート3491のホスト名"examplehost"に対して 接続し、プレフィックス"User"でユーザ名を匿名化する
.sp
.RS 4
.nf
	\fI[example_share]\fR
	\fIpath = /data/example\fR
	\fIvfs objects = smb_traffic_analyzer\fR
	\fIsmb_traffic_analyzer:host = examplehost\fR
	\fIsmb_traffic_analyzer:port = 3491\fR
	\fIsmb_traffic_analyzer:anonymize_prefix = User\fR
	
.fi
.RE
.SH "バージョン"
.PP
このマニュアルページはSamba3\.2\.0用のものである。
.SH "著者"
.PP
オリジナルのバージョンのVFSモジュールとヘルパツールは、 Holger Hetterichによって作成された。
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.2\.14 対応のものである。
.PP
このドキュメントの Samba 3\.2\.14 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉 (ribbon@samba\.gr\.jp)
.sp
.RE
によって行なわれた。
