'\" t
.\"     Title: vfs_acl_xattr
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 04/02/2012
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.4
.\"  Language: English
.\"
.TH "VFS_ACL_XATTR" "8" "04/02/2012" "Samba 3\&.4" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vfs_acl_xattr \- 拡張属性(EA)にNTFSのACLを保存する
.SH "SYNOPSIS"
.HP \w'\ 'u
vfs objects = acl_xattr
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である。
.PP
vfs_acl_xattr
VFSモジュールは、 拡張属性(EA)中にNTFSのアクセスコントロールリスト(ACL)を保存する。 これにより、Sambaサーバ上でWindows ACLの完全なマッピングが可能になる。
.PP
ACLはファイル又はディレクトリの
\fIsecurity\&.NTACL\fR拡張属性中に保存される。 この属性は
getfattr \-d filenameによってリストすることは\fIできない。\fR
現在の値を表示するためには、EAの名前を指定する必要がある(たとえば、
getfattr \-n security\&.NTACL filename)。
.PP
このモジュールは
\fI実験的\fRであることに注意して欲しい!
.PP
このモジュールはスタッカブルである。
.SH "オプション"
.PP

vfs_acl_xattrにはオプションが存在しない。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\&.3\&.6 \- 3\&.4\&.15 対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉 (ribbon@samba\&.grjp)
.sp
.RE
によって行なわれた。
