.\"     Title: vfs_cacheprime
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/07/2009
.\"    Manual: System Administration tools
.\"    Source: Samba 3.2
.\"
.TH "VFS_CACHEPRIME" "8" "01/07/2009" "Samba 3\.2" "System Administration tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_cacheprime - カーネルのファイルデータキャッシュを用意する
.SH "SYNOPSIS"
.HP 1
vfs objects = cacheprime
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である\.
.PP
vfs_cacheprime
VFS モジュールは クライアントから読み込むように要求されたファイル内のデータの周辺を、 大きな塊として読み込む。 これにより、その周辺がクライアントが後で実際に読み込み要求 した場合、カーネルのファイルデータキャッシュに残っているようにする。 する。
.PP
vfs_cacheprimeコマンドで有効になるディスクリード処理のデータサイズは、 cacheprime:rsizeオプションで決まる。 すべてのディスクリードオペレーションは、ここで指定したサイズの倍数単位で同期(調整)される。 ファイルデータは、クライアントがファイルをオープンしている間、前もって準備されている。
.PP
このモジュールはスタッカブルである
.SH "OPTIONS"
.PP
cacheprime:rsize = BYTES
.RS 4
カーネルデータキャッシュに用意しておく容量を指定する。
.sp
以下のサィックスをBYTESに付け加えることができる
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
K
\- KByte単位で指定する
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
M
\- MByte単位で指定する
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
G
\- GByte単位で指定する
.sp
.RE
.RE
.SH "EXAMPLES"
.PP
高性能なディスクアレーでは、リードオペレーションのサイズを1MByte(1048576bytes)にして、 1MByte単位で行われるように設定する必要がある。
.sp
.RS 4
.nf
	\fI[hypothetical]\fR
	\fIvfs objects = cacheprime\fR
	\fIcacheprime:rsize = 1M\fR
.fi
.RE
.SH "CAVEATS"
.PP
cacheprimeは多目的に用意した先読みメカニズムではない。 この機能はある限定された環境、ディスク読み込みがある単位で行われなければならず、 そのサイズが分かっている(可能な限り大きな値)、のために用意されている。
.SH "VERSION"
.PP
このマニュアルはSambaシステムバージョン3\.0\.25に対応している
.SH "AUTHOR"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\.0\.25\-3\.2\.4\-3\.2\.7対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\.co\.jp)
.sp
.RE
によって行なわれた。
