'\" t
.\"     Title: vfs_readonly
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/25/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.4
.\"  Language: English
.\"
.TH "VFS_READONLY" "8" "02/25/2010" "Samba 3\&.4" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vfs_readonly \- 指定された時間、Samba共有を読み込み専用にする
.SH "SYNOPSIS"
.HP \w'\ 'u
vfs objects = readonly
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である。
.PP
vfs_readonly
VFSモジュールは指定された時間、 共有を読み込み専用とする。この間のクライアントからの接続の書き込み アクセスは、アクセス権限によらず、すべて拒否される。
.PP
このモジュールはスタッカブルである。
.SH "オプション"
.PP
readonly:period = BEGIN, END
.RS 4
クライアントからの接続が、BEGINとENDで指定された間、共有は読み込み専用となる。 日付を指定する構文はGNU
\fBdate\fR(1)の\-dオプションと同じ。
.RE
.SH "使用例"
.PP
すべての共有を読み込み専用とする:
.sp
.if n \{\
.RS 4
.\}
.nf
        \fI[global]\fR
	\m[blue]\fBvfs objects = readonly\fR\m[]
.fi
.if n \{\
.RE
.\}
.PP
[backup]共有を、業務時間の間読み込み専用とする
.sp
.if n \{\
.RS 4
.\}
.nf
        \fI[backup]\fR
	\m[blue]\fBpath = /readonly\fR\m[]
	\m[blue]\fBvfs objects = readonly\fR\m[]
	\m[blue]\fBreadonly:period = readonly:period = "today 9:00","today 17:00"\fR\m[]
.fi
.if n \{\
.RE
.\}
.SH "バージョン"
.PP
このマニュアルはSambaシステムバージョン3\&.0\&.25(訳注:3\&.3?)に対応している
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\&.0\&.25 \- 3\&.4\&.6 対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\&.co\&.jp)
.sp
.RE
によって行なわれた。
