'\" t
.\"     Title: vfs_scannedonly
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/16/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.5
.\"  Language: English
.\"
.TH "VFS_SCANNEDONLY" "8" "11/16/2010" "Samba 3\&.5" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vfs_scannedonly \- エンドユーザに対して、ウィルスをスキャンするファイルをのみを 見えるように、かつアクセスできるようにさせる。
.SH "SYNOPSIS"
.HP \w'\ 'u
vfs objects = scannedonly
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(8)システムの一部である。
.PP
vfs_scannedonly
VFS モジュールはエンドユーザに対して ウィルスチェックを行うファイルのみを、表示、アクセス可能にさせる。もしも ウィルスチェックをしないファイルが見つかった場合、ウィルススキャンデーモンは その旨通知する。ウィルススキャンデーモンはSambaの一部ではない。
.PP
Scanreadonlyは2つの部分からなっている。それはSamba vfsモジュールと (1つまたはそれ以上の)デーモンである。デーモンはファイルをスキャンする。もしも 特定のファイルが正常であれば、プレフィックス\&.scanned:
というプレフィックスを持つファイルが生成される。Sambaモジュールは、単に
\&.scanned:というファイルが存在するかと、関連する ファイルよりも新しいかを調べる。もしもその場合は、ファイルはユーザに見える ようになる。もしもそうでない場合、ファイルはディレクトリ一覧表示(設定可能) では見えない。Samba vfsモジュールはそのファイルをスキャンするようにデーモンに 通知する。
.PP
これが、既定値の設定でユーザに対して行われることである。最初にディレクトリ 一覧が表示された時、ファイルはウィルススキャン中のように表示されるが、 そのあとは、すべてのファイルが表示される。すべてのディレクトリをあらかじめ スキャンするために役立つscannedonly_prescanユーティリティが用意されている。 新しいファイルが作成された時、デーモンへは、ファイルへの書き込みが完了後に 引き続いて通知される。
.PP
もしもデーモンによって、ウィルスが発見された場合、警告メッセージを含む ファイルがユーザのディレクトリ中に作成され、警告がログに書き込まれ、ファイルは
\&.virus:というプレフィックスを持つ名前に改名される。
\&.virus:プレフィックスを持つファイルはユーザには決して 見えず、アクセスは拒否される。
.PP
このモジュールはスタック可能である。
.SH "設定"
.PP
vfs_scannedonlyはscannedonlyソケット(UNIXドメイン ソケットかUDPソケット)上でリッスンするウィルススキャンデーモンに依存する。
.SH "オプション"
.PP
scannedonly:domain_socket = True
.RS 4
UNIXドメインソケットを使うか否かの指定(Falseはudpを使う)
.RE
.PP
scannedonly:socketname = /var/lib/scannedonly/scan
.RS 4
接続するUNIXドメインソケットの位置
.RE
.PP
scannedonly:portnum = 2020
.RS 4
接続するUDPポート番号
.RE
.PP
scannedonly:scanhost = localhost
.RS 4
UDP使用時、スキャンデーモンが動作するホスト (このホストはファイルへのアクセスを必要とする!)
.RE
.PP
scannedonly:show_special_files = True
.RS 4
ユーザに対して見えるべきソケット、デバイスとfifo (すべてウィルスチェックを行わない)かどうかの指定
.RE
.PP
scannedonly:rm_hidden_files_on_rmdir = True
.RS 4
見せないファイル(\&.scanned:ファイル、
\&.failed:ファイルと\&.virus:
ファイル)は、もしもユーザがディスクから削除しようと した時に、見えないファイルを削除すべきかどうかの指定。もしも 偽ならば、ユーザは"ディレクトリが空ではありません"というエラーが 生じる。
.RE
.PP
scannedonly:hide_nonscanned_files = True
.RS 4
もしも偽ならば、すべてのスキャンされないファイルはディレクトリ 一覧表示で見えるようになる。もしも、そのようなファイルが ディレクトリ一覧中に見つかった場合、スキャンデーモンに スキャンが要求されたと通知する。スキャンされないファイルへの アクセスは引き続き拒否される(scannedonly:allow_nonscanned_files を参照のこと)。
.RE
.PP
scannedonly:scanning_message = is being scanned for viruses
.RS 4
もしも、スキャンされないファイルが隠し状態 (scannedonly:hide_nonscanned_files = Trueの場合)、見かけ上 0バイトのファイルが表示される。ファイル名はサフィックスとして メッセージとオリジナルのファイル名を結合したものである。
.RE
.PP
scannedonly:recheck_time_open = 50
.RS 4
スキャンされないファイルがオープンしていた場合、vfs モジュールは、\&.scanned:ファイルを作成するために、 スキャンデーモンに対して、recheck_tries_open回、recheck_time_open ミリ秒待つ。時間内(*回再試行)にデーモンによってスキャンされる 小さなファイルは、その動作がアクセス後とのスキャニングのように 振る舞う。
.RE
.PP
scannedonly:recheck_tries_open = 100
.RS 4
recheck_time_openを参照。
.RE
.PP
scannedonly:recheck_time_readdir = 50
.RS 4
もしも、スキャンされないファイルがディレクトリ一覧表示中にあるならば、 vfsモジュールはデーモンに通知し(そのディレクトリ中のものは、 すべてスキャンが必要と一回は通知する)、recheck_tries_readdir回 recheck_time_readdirミリ秒待つ。hide_nonscanned_filesが偽の 時にのみ使われる。
.RE
.PP
scannedonly:recheck_tries_readdir = 20
.RS 4
recheck_time_readdirを参照。
.RE
.PP
scannedonly:allow_nonscanned_files = False
.RS 4
スキャンされないファイルへのアクセスを認める。しかし、デーモンには 通知されるが、それは\&.scanned:のような特別な ファイルである。\&.virus:ファイルと
\&.failed:ファイルは一覧表示されない。
.RE
.SH "例"
.PP
ウィルススキャンを有効にする:
.sp
.if n \{\
.RS 4
.\}
.nf
        \fI[homes]\fR
	\m[blue]\fBvfs objects = scannedonly\fR\m[]
	\m[blue]\fBscannedonly:hide_nonscanned_files = False\fR\m[]
.fi
.if n \{\
.RE
.\}
.SH "警告"
.PP
これは、オンアクセススキャンと同値でないことに注意。しかしながら、 すでにスキャンされたファイルに対してはとても高速である。
.SH "バージョン"
.PP
このマニュアルページは、バージョン 3\&.5\&.0 のSamba用である。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\&.5\&.0 \- 3\&.5\&.6 対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉 (ribbon@samba\&.grjp)
.sp
.RE
によって行なわれた。
