.\"     Title: vfs_commit
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/20/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"
.TH "VFS_COMMIT" "8" "04/20/2009" "Samba 3\.3" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_commit - 書き込み済みデータを特定の間隔でフラッシュする
.SH "SYNOPSIS"
.HP 1
vfs objects = commit
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である\.
.PP
vfs_commit
VFS モジュールはファイルに書き込まれた多くのデータ を管理し、指定された単位でファイに書き込む(同期する)。
.PP
vfs_commitは次の2つの状況で役に立つ。 第一に、非常に重要なデータが大量にある場合、commit:dthreshに小さな値を指定すれば 予期しない電源断に対して被害を最小にとどめることができる。 第二に、あるシステムでは書き込みデータを早期にフラッシュすることで パフォーマンスを向上することができる。
.PP
このモジュールはスタッカブルである。
.SH "オプション"
.PP
commit:dthresh = BYTES
.RS 4
指定されたバイト数が書き込まれるたびにファイルを同期する
.sp
以下のサフィックスが使用可能
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
K
\- BYTES はKByte表記
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
M
\- BYTES はMByte表記
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
G
\- BYTES はGByte表記
.sp
.RE
.RE
.SH "設定例"
.PP
512 KBytes(524288 bytes)データを書き込むたびに、ファイルを同期する
.sp
.RS 4
.nf
        \fI[precious]\fR
	\fIpath = /data/precious\fR
	\fIvfs objects = commit\fR
	\fIcommit:dthresh = 512K\fR
.fi
.RE
.SH "警告"
.PP
一部のシステムでは、commitによるデータ同期を行うと パフォーマンスを損なうことになる。
.SH "バージョン"
.PP
このヘルプはSambaシステム　3\.0\.25(訳注3\.3?)に対応している
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\.0\.25\-3\.3\.2対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\.co\.jp)
.sp
.RE
によって行なわれた。
