'\" t
.\"     Title: vfs_readahead
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/02/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"  Language: English
.\"
.TH "VFS_READAHEAD" "8" "03/02/2010" "Samba 3\&.3" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vfs_readahead \- カーネルバッファキャッシュをプリロードする
.SH "SYNOPSIS"
.HP \w'\ 'u
vfs objects = readahead
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である。
.PP
このvfs_readahead
VFS モジュールは 与えられたオフセット(既定値は16進で0x80000)の倍数としてread要求を検出する。 そしてreadaheadシステムコール(Linuxの場合)か、posix_fadviseシステムコールを用いて カーネルに通知し、このデータをプリフェッチして、バッファキャッシュに入れる。
.PP
このモジュールはWindows Vista クライアントがエクスプローラーでデータを読み込む際に 有用である。エクスプローラーは0x80000の倍数ごとに非同期ファイル読み込み要求をおこなう ため、このオプションが有用になる。
.PP
オフセットの倍数はreadahead:offsetオプションで指定する。既定値は 0x80000である。
.PP

vfs_readaheadで行われるディスクリード処理のサイズは readahead:length オプションで指定する。 このパラメータの既定値はreadahead:offsetと同一の値になる。明示的にに値が指定 されていなければ、readahead:offsetと同じ値が使用される。
.PP
このモジュールはスタッカブルである
.SH "オプション"
.PP
readahead:offset = BYTES
.RS 4
オフセット量で、カーネルバッファーキャッシュに要求する元になる数値
.RE
.PP
readahead:length = BYTES
.RS 4
各々のreadaheadコールでカーネルバッファキャッシュに読み込むバイト数を指定する
.RE
.PP
以下のサフィックスがBYTES指定に使用できる
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
K
\- KByteで指定する
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
M
\- MByteで指定する
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
G
\- GByteで指定する
.SH "設定例"
.sp
.if n \{\
.RS 4
.\}
.nf
	\fI[hypothetical]\fR
	\m[blue]\fBvfs objects = readahead\fR\m[]
.fi
.if n \{\
.RE
.\}
.SH "バージョン"
.PP
このヘルプはSamba3\&.0\&.25用(訳注:3\&.3?)である。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\&.0\&.25\-3\&.3\&.10対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\&.co\&.jp)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉 (ribbon@samba\&.grjp)
.sp
.RE
によって行なわれた。
