'\" t
.\"     Title: vfs_full_audit
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 01/15/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"  Language: English
.\"
.TH "VFS_FULL_AUDIT" "8" "01/15/2010" "Samba 3\&.3" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vfs_full_audit \- Samba VFS　の動作をsystem logに記録する
.SH "SYNOPSIS"
.HP \w'\ 'u
vfs objects = full_audit
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である\&.
.PP
vfs_full_auditVFSモジュールは指定したクライアントの 動きを\fBsyslog\fR(3)でシステムログに記録する。
.PP
vfs_full_audit
はSamba VFSの動作すべてを記録することが可能である。
.RS 4
aio_cancel
.RE
.RS 4
aio_error
.RE
.RS 4
aio_fsync
.RE
.RS 4
aio_read
.RE
.RS 4
aio_return
.RE
.RS 4
aio_suspend
.RE
.RS 4
aio_write
.RE
.RS 4
chdir
.RE
.RS 4
chflags
.RE
.RS 4
chmod
.RE
.RS 4
chmod_acl
.RE
.RS 4
chown
.RE
.RS 4
close
.RE
.RS 4
closedir
.RE
.RS 4
connect
.RE
.RS 4
disconnect
.RE
.RS 4
disk_free
.RE
.RS 4
fchmod
.RE
.RS 4
fchmod_acl
.RE
.RS 4
fchown
.RE
.RS 4
fget_nt_acl
.RE
.RS 4
fgetxattr
.RE
.RS 4
flistxattr
.RE
.RS 4
fremovexattr
.RE
.RS 4
fset_nt_acl
.RE
.RS 4
fsetxattr
.RE
.RS 4
fstat
.RE
.RS 4
fsync
.RE
.RS 4
ftruncate
.RE
.RS 4
get_nt_acl
.RE
.RS 4
get_quota
.RE
.RS 4
get_shadow_copy_data
.RE
.RS 4
getlock
.RE
.RS 4
getwd
.RE
.RS 4
getxattr
.RE
.RS 4
kernel_flock
.RE
.RS 4
lgetxattr
.RE
.RS 4
link
.RE
.RS 4
linux_setlease
.RE
.RS 4
listxattr
.RE
.RS 4
llistxattr
.RE
.RS 4
lock
.RE
.RS 4
lremovexattr
.RE
.RS 4
lseek
.RE
.RS 4
lsetxattr
.RE
.RS 4
lstat
.RE
.RS 4
mkdir
.RE
.RS 4
mknod
.RE
.RS 4
open
.RE
.RS 4
opendir
.RE
.RS 4
pread
.RE
.RS 4
pwrite
.RE
.RS 4
read
.RE
.RS 4
readdir
.RE
.RS 4
readlink
.RE
.RS 4
realpath
.RE
.RS 4
removexattr
.RE
.RS 4
rename
.RE
.RS 4
rewinddir
.RE
.RS 4
rmdir
.RE
.RS 4
seekdir
.RE
.RS 4
sendfile
.RE
.RS 4
set_nt_acl
.RE
.RS 4
set_quota
.RE
.RS 4
setxattr
.RE
.RS 4
stat
.RE
.RS 4
statvfs
.RE
.RS 4
symlink
.RE
.RS 4
sys_acl_add_perm
.RE
.RS 4
sys_acl_clear_perms
.RE
.RS 4
sys_acl_create_entry
.RE
.RS 4
sys_acl_delete_def_file
.RE
.RS 4
sys_acl_free_acl
.RE
.RS 4
sys_acl_free_qualifier
.RE
.RS 4
sys_acl_free_text
.RE
.RS 4
sys_acl_get_entry
.RE
.RS 4
sys_acl_get_fd
.RE
.RS 4
sys_acl_get_file
.RE
.RS 4
sys_acl_get_perm
.RE
.RS 4
sys_acl_get_permset
.RE
.RS 4
sys_acl_get_qualifier
.RE
.RS 4
sys_acl_get_tag_type
.RE
.RS 4
sys_acl_init
.RE
.RS 4
sys_acl_set_fd
.RE
.RS 4
sys_acl_set_file
.RE
.RS 4
sys_acl_set_permset
.RE
.RS 4
sys_acl_set_qualifier
.RE
.RS 4
sys_acl_set_tag_type
.RE
.RS 4
sys_acl_to_text
.RE
.RS 4
sys_acl_valid
.RE
.RS 4
telldir
.RE
.RS 4
unlink
.RE
.RS 4
utime
.RE
.RS 4
write
.RE
.PP
これらの動作に加え、
vfs_full_auditは"all" and "none "という オプションを使用することができる。これらはすべてのVFS動作に対し有効になり、 ここのVFS動作に対して指定することはできない。
.PP
vfs_full_auditは動作を\'|\'をセパレーターとして 固定フォーマットで記録する。 記録フォーマットは
.sp
.if n \{\
.RS 4
.\}
.nf
		smbd_audit: PREFIX|OPERATION|RESULT|FILE
	
.fi
.if n \{\
.RE
.\}
.PP
各フィールドは:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
PREFIX
\- full_audit:prefix文字と、可変長の解説
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
OPERATION
\- VFSの名称
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
RESULT
\- 動作が成功したか、失敗したか
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FILE
\- 動作が行われたファイルやディレクトリの名称
.sp
.RE
.PP
このモジュールはスタッカブルである。
.SH "オプション"
.PP
vfs_full_audit:prefix = STRING
.RS 4
STRINGで監査メッセージを結合する。STRINGは
\fBsmb.conf\fR(5)に記載された指定を置き換える 初期値は"%u|%I"\&.
.RE
.PP
vfs_full_audit:success = LIST
.RS 4
LISTはVFSオペレーションのリストで、動作が成功したときに記録を残すものを表す。 オペレーションは上に示したリストにある名前で指定する。
.RE
.PP
vfs_full_audit:failure = LIST
.RS 4
LISTはVFSオペレーションのリストで、動作が失敗したときに記録を残すものを表す。 オペレーションは上に示したリストにある名前で指定する。
.RE
.PP
full_audit:facility = FACILITY
.RS 4

\fBsyslog\fR(3)のfacilityを指定する
.RE
.PP
full_audit:priority = PRIORITY
.RS 4

\fBsyslog\fR(3)のpriorityを指定する
.RE
.SH "設定例"
.PP
[records]共有の中のファイルやディレクトリをオープンしたときにログを残す。 その際、LOCAL7ファシリティーと、ALERTプライオリティーを使用し、 ユーザー名とIPアドレスも記録する:
.sp
.if n \{\
.RS 4
.\}
.nf
        \fI[records]\fR
	\m[blue]\fBpath = /data/records\fR\m[]
	\m[blue]\fBvfs objects = full_audit\fR\m[]
	\m[blue]\fBfull_audit:prefix = %u|%I\fR\m[]
	\m[blue]\fBfull_audit:success = open opendir\fR\m[]
	\m[blue]\fBfull_audit:failure = all\fR\m[]
	\m[blue]\fBfull_audit:facility = LOCAL7\fR\m[]
	\m[blue]\fBfull_audit:priority = ALERT\fR\m[]
.fi
.if n \{\
.RE
.\}
.SH "バージョン"
.PP
このヘルプはSambaシステム　3\&.0\&.25(訳注:3\&.3?)に対応している
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\&.0\&.25\-3\&.3\&.10対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\&.co\&.jp)
.sp
.RE
によって行なわれた。
