'\" t
.\"     Title: vfs_default_quota
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/20/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"  Language: English
.\"
.TH "VFS_DEFAULT_QUOTA" "8" "03/20/2010" "Samba 3\&.2" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vfs_default_quota \- Windowsクライアント用の容量制限(quota)レコードを保存する
.SH "SYNOPSIS"
.HP \w'\ 'u
vfs objects = default_quota
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である\&.
.PP
多くの一般的な容量制限の実装はユーザやグループ単位で設定することはできるが、 既定値を指定することができない。 Sambaのvfs_default_quotaモジュールは容量制限の 初期値を持つことができ、Windowsのエクスプローラーから調べることができる。
.PP
初期設定では、SambaはLO_LIMITをデフォルトクオータとして返却し、 内容は変更できない。
vfs_default_quotaはデフォルトクオータをユーザの クオータレコードの内容に読み替えて返却する。 初期設定では、ルートユーザはこの動作をしない。なぜなら容量制限は通常 ルートユーザに有効にならないからである。
.PP
このモジュールはスタッカブルである。
.SH "オプション"
.PP
default_quota:uid = UID
.RS 4
デフォルトユーザクオータが保存されているユーザIDを指定する。
.RE
.PP
default_quota:gid = GID
.RS 4
デフォルトユーザクオータが保存されているグループIDを指定する
.RE
.PP
default_quota:uid nolimit = BOOL
.RS 4
パラメータにTrueを指定すると、デフォルトユーザクオーターが指定されていても 容量制限なし(NO_LIMIT)と通知される。そうでない場合、保存されている値がレポートされる。
.RE
.PP
default_quota:gid nolimit = BOOL
.RS 4
パラメータにTrueを指定すると、デフォルトグループクオーターが指定されていても 容量制限なし(NO_LIMIT)と通知される。そうでない場合、保存されている値がレポートされる。
.RE
.SH "使用例"
.PP
ユーザーID65535のクオータレコードにデフォルトクオータレコードを保存する。 そして、そのユーザはクオータ制限なしとする。
.sp
.if n \{\
.RS 4
.\}
.nf
        \fI[global]\fR
	\m[blue]\fBvfs objects = default_quota\fR\m[]
	\m[blue]\fBdefault_quota:uid = 65535\fR\m[]
	\m[blue]\fBdefault_quota:uid nolimit = yes\fR\m[]
.fi
.if n \{\
.RE
.\}
.SH "バージョン"
.PP
このマニュアルはSambaバージョン3\&.0\&.25に対応している。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\&.0\&.25\-3\&.2\&.4\-3\&.2\&.15対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\&.co\&.jp)
.sp
.RE
によって行なわれた。
