'\" t
.\"     Title: smb_traffic_analyzer
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 01/25/2011
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.4
.\"  Language: English
.\"
.TH "SMB_TRAFFIC_ANALYZER" "8" "01/25/2011" "Samba 3\&.4" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vfs_smb_traffic_analyzer \- ヘルパアプリケーションに対して、ソケット経由でのSamba VFS読み出し 書き込み操作のログを取る
.SH "SYNOPSIS"
.HP \w'\ 'u
vfs objects = smb_traffic_analyzer
.SH "説明"
.PP
このVFSモジュールは、\fBsamba\fR(7)システムの一部である。
.PP
vfs_smb_traffic_analyzer
VFSモジュールは、 Sambaサーバ上のクライアント書き込みと読み出し操作のログを取り、 このデータを、SQLデータベースに送る、ヘルパプログラムに対して ソケット上で送信する。ヘルパプログラムの詳細な情報は、 http://holger123\&.wordpress\&.com/smb\-traffic\-analyzer/ にあるプロジェクトホームページから得られる。
.PP
vfs_smb_traffic_analyzerは現在、以下のVFS操作を 理解する:
.RS 4
write
.RE
.RS 4
pwrite
.RE
.RS 4
read
.RE
.RS 4
pread
.RE
.PP
vfs_smb_traffic_analyzer
sends the following data in a fixed format seperated by a comma through either an internet or a unix domain socket:
.PP
vfs_smb_traffic_analyzerは、コンマによって分離された 固定フォーマットで、以下のデータを、インターネットまたはUNIXドメインソケット を通じて送る:
.sp
.if n \{\
.RS 4
.\}
.nf
	BYTES|USER|DOMAIN|READ/WRITE|SHARE|FILENAME|TIMESTAMP
	
.fi
.if n \{\
.RE
.\}
.PP
レコードの詳細:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
BYTES
\- VFS操作のバイト単位の長さ
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
USER
\- 操作を開始したユーザ
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
DOMAIN
\- ユーザのドメイン
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
READ/WRITE
\- "W"なら書き込み操作、"R"なら読み出し操作
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
SHARE
\- VFS操作が行われた共有の名前
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FILENAME
\- VFS操作によって使われたファイルの名前
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
TIMESTAMP
\- VFS操作が行われたことを示す "yyyy\-mm\-dd hh\-mm\-ss\&.ms" での時間
.sp
.RE
.PP
このモジュールはスタック可能である。
.SH "オプション"
.PP
smb_traffic_analyzer:mode = STRING
.RS 4
もしも、STRINGが "unix_domain_socket" に一致するならば、モジュール は/var/tmp/stadsocketに位置するunixドメインソケットを使い、もしも、 STRINGにそのほかの文字列か、未定義ならば、モジュールは、データの転送 のためにインターネットドメインソケットを使う。
.RE
.PP
smb_traffic_analyzer:host = STRING
.RS 4
モジュールはホスト名がSTRINGという名前のシステムにデータを送る。
.RE
.PP
smb_traffic_analyzer:port = STRING
.RS 4
モジュールはSTRING中で指定されたTCPポートにデータを送る。
.RE
.PP
smb_traffic_analyzer:anonymize_prefix = STRING
.RS 4
モジュールは、STRINGで与えられたプレフィックスと単純なハッシュ値で ユーザ名を置き換える。
.RE
.PP
smb_traffic_analyzer:total_anonymization = STRING
.RS 4
もしもSTRINGが\'yes\'に一致するならば、このモジュールは、 追加のハッシュ値を生成しないで、smb_traffic_analyzer:anonymize_prefix オプションによって与えられる文字列で、任意のユーザ名を置き換える。 これは、任意の転送データが1人のユーザにマッピングされ、ユーザに 関連するデータの完全な匿名化を提供する。
.RE
.SH "使用例"
.PP
unixドメインソケットを使い、共有"example_share"上でモジュールを走らせる
.sp
.if n \{\
.RS 4
.\}
.nf
	\fI[example_share]\fR
	\m[blue]\fBpath = /data/example\fR\m[]
	\m[blue]\fBvfs objects = smb_traffic_analyzer\fR\m[]
	\m[blue]\fBsmb_traffic_analyzer:mode = unix_domain_socket\fR\m[]
	
.fi
.if n \{\
.RE
.\}
.PP
The module running on share "example_share", using an internet socket, connecting to host "examplehost" on port 3491\&.
.PP
インターネットソケットを使い、ポート3491のホスト名"examplehost"に対して 接続し、共有"example_share"上でモジュールを走らせる
.sp
.if n \{\
.RS 4
.\}
.nf
	\fI[example_share]\fR
	\m[blue]\fBpath = /data/example\fR\m[]
	\m[blue]\fBvfs objects = smb_traffic_analyzer\fR\m[]
	\m[blue]\fBsmb_traffic_analyzer:host = examplehost\fR\m[]
	\m[blue]\fBsmb_traffic_analyzer:port = 3491\fR\m[]
	
.fi
.if n \{\
.RE
.\}
.PP
The module running on share "example_share", using an internet socket, connecting to host "examplehost" on port 3491, anonymizing user names with the prefix "User"\&.
.PP
インターネットソケットを使い、ポート3491のホスト名"examplehost"に対して 接続し、プレフィックス"User"でユーザ名を匿名化する
.sp
.if n \{\
.RS 4
.\}
.nf
	\fI[example_share]\fR
	\m[blue]\fBpath = /data/example\fR\m[]
	\m[blue]\fBvfs objects = smb_traffic_analyzer\fR\m[]
	\m[blue]\fBsmb_traffic_analyzer:host = examplehost\fR\m[]
	\m[blue]\fBsmb_traffic_analyzer:port = 3491\fR\m[]
	\m[blue]\fBsmb_traffic_analyzer:anonymize_prefix = User\fR\m[]
	
.fi
.if n \{\
.RE
.\}
.SH "バージョン"
.PP
このマニュアルページはSamba3\&.3(訳注 3\&.x?)用のものである。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.PP
オリジナルのバージョンのVFSモジュールとヘルパツールは、 Holger Hetterichによって作成された。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.3\&.6 \- 3\&.4\&.11 対応のものである。
.PP
このドキュメントの Samba 3\&.2\&.8 \- 3\&.4\&.11 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉 (ribbon@samba\&.gr\&.jp)
.sp
.RE
によって行なわれた。
