.\"     Title: vfs_cap
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/17/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.2
.\"
.TH "VFS_CAP" "8" "07/17/2009" "Samba 3\.2" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_cap - ファイル名をCAPでエンコード
.SH "SYNOPSIS"
.HP 1
vfs objects = cap
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である\.
.PP
CAP(Columbia Appletalk Protocol)エンコーディングは、ASCII文字を使って非アスキー文字のファイル名を 提供するテクニックである。
vfs_cap
VFSモジュールはファイル名をCAPフォーマットに、あるいはCAPフォーマット をユーザーのネーティブなエンコードに変換する。
.PP
CAPエンコードは日本語環境で最も一般的に使用されている。
.PP
このモジュールはスタッカブルである
.SH "使用例"
.PP
GNU libiconvを使用する環境では、CAPエンコードをShift_JISロケールをサポートするために使用している。
.sp
.RS 4
.nf
        \fI[global]\fR
	\fIdos charset = CP932\fR
	\fIdos charset = CP932\fR
	\fIvfs objects = cap\fR
.fi
.RE
.SH "バージョン"
.PP
このマニュアルはSambaシステムバージョン3\.0\.25に対応している
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\.0\.25\-3\.2\.4\-3\.2\.13対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\.co\.jp)
.sp
.RE
によって行なわれた。
