.\"     Title: vfs_catia
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 03/03/2009
.\"    Manual: System Administration tools
.\"    Source: Samba 3.2
.\"
.TH "VFS_CATIA" "8" "03/03/2009" "Samba 3\.2" "System Administration tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_catia - Catiaファイルシステムで無効な文字を変換する
.SH "SYNOPSIS"
.HP 1
vfs objects = catia
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である\.
.PP
Catia CADパッケージはCIFSファイルシステムで使用できない文字を使用して ファイルを作成する。
vfs_catia
VFS モジュールはCIFSクライアントが共有可能になるように 文字マッピングを行う。
.PP
このモジュールはスタッカブルである
.SH "EXAMPLES"
.PP
[CAD]共有のファイル名をマップする:
.sp
.RS 4
.nf
        \fI[CAD]\fR
	\fIpath = /data/cad\fR
	\fIvfs objects = catia\fR
.fi
.RE
.SH "VERSION"
.PP
このマニュアルはSambaシステムバージョン3\.0\.25に対応している
.SH "AUTHOR"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\.0\.25\-3\.2\.4\-3\.2\.8対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\.co\.jp)
.sp
.RE
によって行なわれた。
