.\"     Title: vfs_prealloc
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/17/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"
.TH "VFS_PREALLOC" "8" "07/17/2009" "Samba 3\.3" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_prealloc - あらかじめ指定されたサイズで、ファイルサイズを割り当てる
.SH "SYNOPSIS"
.HP 1
vfs objects = prealloc
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である。
.PP
vfs_preallocVFSモジュールはファイルが作成されるたびに あらかじめ指定されたサイズを割り当てることができる。この機能はディスクサブシステムに あらかじめ決まったサイズごとに書き込み、ファイルサイズを拡張することが負荷になるような 環境に対して有効である。
.PP
このモジュールはスタッカブルである
.SH "オプション"
.PP
prealloc:EXT = BYTES
.RS 4
すべてのファイルに対して、EXTという拡張子を付けて、BYTESで指定されたサイズを 割り当てる。
.sp
以下のサフィックスがBYTESに指定可能
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
K
\- BYTES はKBytes単位
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
M
\- BYTES はMBytes単位
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
G
\- BYTES はGBytes単位
.sp
.RE
.RE
.SH "設定例"
.PP
TIFFファイルをSamba共有に書き込む処理で、ファイルサイズが4MBytes近辺(4194304 バイト)であるとわかっているとき
.sp
.RS 4
.nf
    \fI[frames]\fR
	\fIpath = /data/frames\fR
	\fIvfs objects = prealloc\fR
	\fIprealloc:tiff = 4M\fR
.fi
.RE
.SH "注意"
.PP
vfs_preallocはすべてのプラットフォームとファイルシステム をサポートしているわけではない。現状ではLinuxとIRIXのXFSファイルシステムのみ、サポートしている。
.SH "バージョン"
.PP
このヘルプはSamba 3\.0\.25(訳注:3\.3)に対応している
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\.0\.25\-3\.3\.6対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\.co\.jp)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉 (ribbon@samba\.gr\.jp)
.sp
.RE
によって行なわれた。
