.\"     Title: vfs_acl_tdb
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/17/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"
.TH "VFS_ACL_TDB" "8" "07/17/2009" "Samba 3\.3" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_acl_tdb - tdbファイルにNTFSのACLを保存する
.SH "SYNOPSIS"
.HP 1
vfs objects = acl_tdb
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である。
.PP
vfs_acl_tdb
VFSモジュールは、 tdbファイルにNTFSのアクセスコントロールリスト（ACL)を格納する。 これは、Sambaサーバ上でWindows ACLの完全なマッピングを有効にする。
.PP
ACLの設定は
\fI$LOCKDIR/file_ntacls\.tdb\fR中に格納される。
.PP
このモジュールは
\fI実験的\fRであることに留意して欲しい!
.PP
このもジュールはスタッカブルである。
.SH "オプション"
.PP

vfs_acl_tdbに対してオプションはない。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\.3\.2\-3\.3\.6対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
太田俊哉 (ribbon@samba\.grjp)
.sp
.RE
によって行なわれた。
