.\"     Title: vfs_shadow_copy
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/17/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"
.TH "VFS_SHADOW_COPY" "8" "04/17/2009" "Samba 3\.3" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vfs_shadow_copy - Samba の共有を指定した時間帯に read only とする(訳注: これはコピペミスであり、実際は「シャドウコピー機能を実現する。」などとすべきである。)
.SH "SYNOPSIS"
.HP 1
vfs objects = shadow_copy
.SH "説明"
.PP
この VFS モジュールは
\fBsamba\fR(7)システムの一部である。
.PP
vfs_shadow_copy
VFS モジュールは Microsoft のシャドウコピーサービスと似た機能を提供する。 適切に設定された場合、このモジュールにより Microsoft シャドウコピークライアントから Samba の共有上にある "シャドウコピー" を参照することが可能となる。
.PP
このモジュールはスタック可能である。
.SH "設定"
.PP
vfs_shadow_copy
はファイルシステムのスナップショットの実装が必要である。 一般的なファイルシステムの多くが標準でこれをサポートしている。
.PP
ファイルシステムのシャドウコピーを
vfs_shadow_copy
が認識するためには、 特定の名称のディレクトリにマウントされる必要がある。 スナップショットのマウントポイントは共有ディレクトリの直下である必要がある。
.PP
スナップショットの名前形式は @GMT\-YYYY\.MM\.DD\-hh\.mm\.ss である必要がある。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
YYYY
には4桁で年を指定する
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
MM
は2桁で月を指定する
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
DD
は2桁で日を指定するis the 2 digit day
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
hh
は2桁で時間を指定する
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
mm
は2桁で分を指定する
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ss
は2桁で秒を指定する
.sp
.RE
.PP

vfs_shadow_copy
のスナップショットの名前形式は、
\fBdate\fR(1)
コマンドを用いて生成できる:
.sp
.RS 4
.nf
	TZ=GMT date +@GMT\-%Y\.%m\.%d\-%H\.%M\.%S
	
.fi
.RE
.SH "設定例"
.PP
ユーザーのホームディレクトリでシャドウコピーをサポートするには以下の設定を行なう:
.sp
.RS 4
.nf
        \fI[homes]\fR
	\fIvfs objects = shadow_copy\fR
.fi
.RE
.SH "警告"
.PP
これはバックアップ、アーカイブ、バージョン管理のための機能ではないことに注意。
.PP
Samba と Windows 双方とも
vfs_shadow_copy
はエンドユーザのための機能として設計されている。 これはバックアップやアーカイ機能を代替、もしくは拡張するものではなく、 そのような認識をしてはならない。 バージョン管理機能が必要な場合は、バージョン管理機能を実装する必要がある。
.SH "バージョン"
.PP
このマニュアルページは Samba 3\.0\.25 用(訳注:3\.3?)のものである。
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.2\.4\-3\.3\.2 対応のものである。
.PP
このドキュメントの Samba 3\.2\.4\-3\.3\.2 対応の翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
たかはしもとのぶ (monyo@samba\.gr\.jp)
.sp
.RE
によって行なわれた。
