'\" t
.\"     Title: vfs_extd_audit
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/02/2010
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"  Language: English
.\"
.TH "VFS_EXTD_AUDIT" "8" "03/02/2010" "Samba 3\&.3" "システム管理ツール"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vfs_extd_audit \- 指定したSambaVFSの動作を記録する
.SH "SYNOPSIS"
.HP \w'\ 'u
vfs objects = extd_audit
.SH "説明"
.PP
このVFSモジュールは
\fBsamba\fR(7)システムの一部である\&.
.PP
extd_audit
VFSモジュールは指定されたクライアントの動作を
\fBsmbd\fR(8)ログと、システムログ
\fBsyslog\fR(3))両方に記録する。
.PP

\fBsmbd\fR(8)でログをとるということは、
\fBvfs_audit\fR(8)でログをとることに他ならない。
.PP
このモジュールはスタッカブルである
.SH "バージョン"
.PP
このマニュアルはSambaシステムバージョン3\&.0\&.25(訳注:3\&.3?)に対応している
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、Andrew Tridgell によって作成された。現在 Samba は Samba Team に よって、Linuxカーネルの開発と同様のオープンソースプロジェクト として開発が行なわれている。
.SH "日本語訳"
.PP
このドキュメントは、Samba 3\&.0\&.25\-3\&.3\&.11対応のものである。
.PP
このドキュメントの翻訳は
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
平田祥司 (shouji@microft\&.co\&.jp)
.sp
.RE
によって行なわれた。
