'\" t
.\"     Title: wbinfo
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/13/2010
.\"    Manual: ユーザコマンド
.\"    Source: Samba 3.4
.\"  Language: English
.\"
.TH "WBINFO" "1" "05/13/2010" "Samba 3\&.4" "ユーザコマンド"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
wbinfo \- winbind デーモンから情報を問い合わせる
.SH "SYNOPSIS"
.HP \w'\ 'u
wbinfo [\-a\ user%password] [\-\-all\-domains] [\-\-allocate\-gid] [\-\-allocate\-uid] [\-D\ domain] [\-\-domain\ domain] [\-g] [\-\-getdcname\ domain] [\-\-get\-auth\-user] [\-G\ gid] [\-h] [\-i\ user] [\-I\ ip] [\-K\ user%password] [\-m] [\-n\ name] [\-N\ netbios\-name] [\-\-own\-domain] [\-p] [\-r\ user] [\-\-remove\-uid\-mapping\ uid,sid] [\-\-remove\-gid\-mapping\ gid,sid] [\-s\ sid] [\-\-separator] [\-\-sequence] [\-\-set\-auth\-user\ user%password] [\-\-set\-uid\-mapping\ uid,sid] [\-\-set\-gid\-mapping\ gid,sid] [\-S\ sid] [\-t] [\-u] [\-\-uid\-info\ uid] [\-\-user\-domgroups\ sid] [\-\-user\-sids\ sid] [\-U\ uid] [\-V] [\-Y\ sid] [\-\-verbose]
.SH "説明"
.PP
このツールは
\fBSamba\fR(7)
システムの一部である。
.PP
wbinfo
プログラムは、\fB winbindd\fR(8)
デーモンが生成し使用した情報を、問い合わせて返す。
.PP
wbinfo
プログラムが情報を取得できるように
\fBwinbindd\fR(8)
デーモンが正しく設定され、動作していなければならない。
.SH "オプション"
.PP
\-a|\-\-authenticate \fIusername%password\fR
.RS 4
\fBwinbindd\fR(8)経由でユーザの認証を試みる。これは、認証の方法をチェックし、その結果をレポートする。
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
サードパーティアプリケーション中で認証のためにこの機能を使うことを考えて はいけない。その代わりに
\fBntlm_auth\fR(1)を使うこと。
.sp .5v
.RE
.RE
.PP
\-\-allocate\-gid
.RS 4
idmap範囲外の新しいGIDを得る。
.RE
.PP
\-\-allocate\-uid
.RS 4
idmap範囲外の新しいUIDを得る。
.RE
.PP
\-\-all\-domains
.RS 4
すべてのドメインを表示する(信頼されたものと自分自身)。
.RE
.PP
\-\-domain \fIname\fR
.RS 4
このパラメータで指定された操作が行われるドメインを 設定する。特殊なドメイン名である \'\&.\' は、現在\fB winbindd\fR(8)が属する ドメインを表すために使用される。今のところ、\fB\-\-sequence \fR、\fB\-u\fR
と
\fB\-g\fR
オプションのみがこのパラメータに対応している。
.RE
.PP
\-D|\-\-domain\-info \fIdomain\fR
.RS 4
指定したドメインに関してのほとんどの情報を表示する。
.RE
.PP
\-g|\-\-domain\-groups
.RS 4
このオプションは
\fBSamba\fR(7)
デーモンが動作している、Windows NT ドメイン内で利用できる全グループを 一覧表示する。また、すべての信頼されるドメインのグループも 一覧表示される。この操作では
\fBwinbindd\fR(8)
で見えないグループの ID は取得できない。
.RE
.PP
\-\-get\-auth\-user
.RS 4
ドメインコントローラとのセッションセットアップで、
\fBwinbindd\fR(8)
で使用されるユーザ名とパスワードを表示する。ユーザ名と パスワードは
\fB\-\-set\-auth\-user\fRオプションを使って設定できる。 root しか使用できない。
.RE
.PP
\-\-getdcname \fIdomain\fR
.RS 4
指定したドメインのためのDC名を得る。
.RE
.PP
\-G|\-\-gid\-to\-sid \fIgid\fR
.RS 4
UNIX の group id を Windows NT の SID に変換しようとする。もし指定された gid が idmap gid で指定された 範囲に収まらない場合、この操作は失敗する。
.RE
.PP
\-i|\-\-user\-info \fIuser\fR
.RS 4
ユーザ情報を得る。
.RE
.PP
\-I|\-\-WINS\-by\-ip \fIip\fR
.RS 4
\fI\-I\fR
オプションは
\fBwinbindd\fR(8)
に、\fIip\fR
パラメータで指定された IP アドレスと対応する NetBIOS 名を問い合わせるため、node status request を送る。
.RE
.PP
\-K|\-\-krb5auth \fIusername%password\fR
.RS 4
Kerberos経由でユーザの認証を試みる。
.RE
.PP
\-m|\-\-trusted\-domains
.RS 4
\fBwinbindd\fR(8)
が名前解決の際に問い合わせを行う、Windows NT サーバが信頼している ドメインの一覧を提供する。このリストには、 サーバがプライマリドメインコントローラとなっている Windows NT ドメインは含まれない。
.RE
.PP
\-n|\-\-name\-to\-sid \fIname\fR
.RS 4
\fI\-n\fR
オプションは
\fBwinbindd\fR(8)
に対し、指定された名前と対応した SID を問い合わせる。Winbind separator として指定された文字を使用することで ユーザ名の前にドメイン名を指定することができる。 たとえば、CWDOM1/Administrator はドメイン CWDOM1 の Administrator ユーザとなる。もしドメインが指定されていない場合、使用されるドメインは
\fBsmb.conf\fR(5 )
の
\fIworkgroup\fR
パラメータで指定されたものとなる。
.RE
.PP
\-N|\-\-WINS\-by\-name \fIname\fR
.RS 4
\fI\-N\fR
オプションは
\fBwinbindd\fR(8 )
を使い、\fIname\fR
パラメータで指定された NetBIOS 名に対応する IP アドレスを WINS サーバに問い合わせる。
.RE
.PP
\-\-own\-domain
.RS 4
所有するドメインを一覧表示する。
.RE
.PP
\-p|\-\-ping
.RS 4
\fBwinbindd\fR(8)
が動作中かどうか確認する。\'成功\' か \'失敗\' かを表示する。
.RE
.PP
\-r|\-\-user\-groups \fIusername\fR
.RS 4
ユーザが所属する UNIX の group ids 一覧を表示しようとする。 これはドメインコントローラに登録されているユーザにのみ動作する。
.RE
.PP
\-s|\-\-sid\-to\-name \fIsid\fR
.RS 4
\fI\-s\fR
を使用して SID から名前を解決 することができる。これは前述の
\fI\-n\fR
オプションの 逆である。SID はこれまでどおり Microsoft のフォーマットを用いた ASCII 文字列で指定する必要がある。たとえば、 S\-1\-5\-21\-1455342024\-3071081365\-2475485837\-500 というふうに記述する。
.RE
.PP
\-\-separator
.RS 4
有効なwinbindセパレータを得る。
.RE
.PP
\-\-sequence
.RS 4
すべての既知のドメインのシーケンス番号を表示する。
.RE
.PP
\-\-set\-auth\-user \fIusername%password\fR
.RS 4
ドメインコントローラとのセッション確立時に使用される ユーザ名とパスワードを保存する。これは\fBwinbindd \fR(8)
が Restrict Anonymous が有効となっている Windows 2000 ドメインで動作することを可能にする。 (Windows 2000 サーバ互換のパーミッションのみ)
.RE
.PP
\-S|\-\-sid\-to\-uid \fIsid\fR
.RS 4
SID を UNIX の user id に変換する。もし SID が
\fBwinbindd\fR(8)
で UNIX ユーザにマッピングされていない場合、この操作は失敗する。
.RE
.PP
\-t|\-\-check\-secret
.RS 4
Samba サーバが動作中の Windows NT ドメインに参加時に、 ワークステーションの信頼するアカウントが作成されたことを確認する。
.RE
.PP
\-u|\-\-domain\-users
.RS 4
このオプションは
\fBwinbindd\fR(8)
デーモンが動作している Windows NT domain に存在する全てのユーザ を一覧表示する。全ての信頼されるドメインのユーザ一覧も表示する。 この操作は
\fBwinbindd\fR(8)
で見えるユーザ以外にはユーザ ID を割り当てることはない。
.RE
.PP
\-\-uid\-info \fIuid\fR
.RS 4
ユーザID UIDとして接続されたユーザのためのユーザ情報を得る。
.RE
.PP
\-\-user\-domgroups \fIsid\fR
.RS 4
ユーザドメイングループを得る。
.RE
.PP
\-\-user\-sids \fIsid\fR
.RS 4
ユーザのユーザグループSIDを得る。
.RE
.PP
\-U|\-\-uid\-to\-sid \fIuid\fR
.RS 4
UNIX の user id を Windows NT の SID に変換する。 もし指定された uid が idmap uid の範囲に収まらない場合、この操作は 失敗する。
.RE
.PP
\-\-verbose
.RS 4
問い合わせの結果に追加の情報を表示する。
.RE
.PP
\-Y|\-\-sid\-to\-gid \fIsid\fR
.RS 4
SID を UNIX の group id に変換する。もし SID が
\fBwinbindd\fR(8)
によって UNIX の group に関連付けられていない場合、操作は失敗する。
.RE
.PP
\-\-remove\-uid\-mapping uid,sid
.RS 4
IDmap バックエンドから、存在するuidからsidへの マッピングを削除する。
.RE
.PP
\-\-remove\-gid\-mapping gid,sid
.RS 4
IDmap バックエンドから、存在するgidからsidへの マッピングを削除する。
.RE
.PP
\-\-set\-uid\-mapping uid,sid
.RS 4
IDmap バックエンドに、uidからsidへのマッピングを 新規に作成するか、既存のものを変更する。
.RE
.PP
\-\-set\-gid\-mapping gid,sid
.RS 4
IDmap バックエンドに、gidからsidへのマッピングを 新規に作成するか、既存のものを変更する。
.RE
.PP
\-V
.RS 4
プログラムのバージョン番号を表示する。
.RE
.PP
\-h|\-\-help
.RS 4
コマンドラインオプションの要約を表示する。
.RE
.SH "終了ステータス"
.PP
wbinfo プログラムは操作に成功すると 0 を返し、失敗すると 0 を返す。もし
\fBwinbindd\fR(8)
デーモンが動作していない場合、wbinfo
は常に失敗を返す。
.SH "バージョン"
.PP
この man ページは、Samba システムのバージョン 3 用である。
.SH "関連項目"
.PP
\fBwinbindd\fR(8)と
\fBntlm_auth\fR(1)
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連するユーティリティは、 Andrew Tridgell によって作られた。Samba は現在 Linux カーネルが開発されているような方法でのオープンソースプロジェクトである Samba Team によって開発されている。
.PP
wbinfo
と
winbindd
は Tim Potter によって書かれた。
.PP
Samba 2\&.2 用の DocBook 形式への変換は Gerald Carter が行った。 Samba 3\&.0 用の DocBook XML 4\&.2 形式への変換は Alexander Bokovoy が行った。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\&.3\&.6 \- 3\&.4\&.8 対応のものである。
.PP
このドキュメントの Samba 3\&.0\&.0 対応の翻訳は 山田 史朗 (shiro@miraclelinux\&.com) によって行なわれた。
.PP
このドキュメントの Samba 3\&.2\&.4 \- 3\&.4\&.8 対応の翻訳は 太田俊哉(ribbon@samba\&.gr\&.jp)によって行われた。
