.\"     Title: winbindd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/30/2009
.\"    Manual: システム管理ツール
.\"    Source: Samba 3.3
.\"
.TH "WINBINDD" "8" "07/30/2009" "Samba 3\.3" "システム管理ツール"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
winbindd - NT サーバからの名前解決を行う Name Service Switch (NSS)デーモン
.SH "SYNOPSIS"
.HP 1
winbindd [\-F] [\-S] [\-i] [\-Y] [\-d\ <debug\ level>] [\-s\ <smb\ config\ file>] [\-n]
.SH "説明"
.PP
このプログラムは、\fBsamba\fR(7)
システムの一部である。
.PP
winbindd
は、 はデーモンであり、 現在 C ライブラリの大半に実装されている NSS (ネームサービススイッチ) 機能、 PAM を利用する任意のアプリケーション、
ntlm_auth
および Samba 自身に対する各種サービスを提供する。
.PP
NSS 機能を使用しない場合でも、 winbindd はドメインコントローラとの通信を行い、
smbd
、ntlm_auth
、 PAM モジュールの
pam_winbind\.so
に対するサービスを提供する。 この場合、
\fIidmap uid\fR
および
\fIidmap gid\fR
パラメータは不要である (これは「netlogon [proxy only mode」と呼ばれる)。
.PP
NSS 機能は、ユーザーやシステムの情報を NIS や DNS などの様々なデータベースサービスから取得することを可能とする。 実際の動作は、
\fI/etc/nsswitch\.conf\fR
ファイルにて設定する。 各ユーザやグループに対しては、 Samba サーバの管理者が指定したユーザ ID とグループ ID の範囲から ID が割り当てられる。
.PP

winbindd
によって提供されるサービスは「winbind」と呼ばれ、 Windows NT サーバからユーザとグループの情報を取得するために用いられる。 このサービスは関連する PAM モジュールを通じて、 認証サービスを提供することも可能である。
.PP

\fIpam_winbind\fR
モジュールは、
\fIauth\fR
、
\fIaccount\fR
、
\fIpassword\fR
の各モジュールタイプをサポートしている。
\fIaccount\fR
モジュールについては、システムによるユーザの UID の取得可否を確認するために getpwnam() を実行するだけの機能しかない。 これは、ドメインコントローラにより既にアクセス制御が行われているためである。
\fIlibnss_winbind\fR
もしくはシステムに応じた名称のライブラリが適切にインストールされていれば、このモジュールは必ず成功するはずである。
.PP
winbind サービスは、以下の NSS データベースを実装している:
.PP
\-D
.RS 4
もしも指定されたならば、このパラメータは、サーバをデーモンとして動かす。 すなわち、それ自身をデタッチして、適合したポート上でバックグラウンドとして動く。 このスイッチは、もしも、winbindd
がシェルのコマンド行上で実行された事を仮定する。
.RE
.PP
hosts
.RS 4
これは、 IRIX でのみ有効である。 ユーザ情報(訳注: ホスト情報だと思われる)は、伝統的に
\fIhosts(5)\fR
ファイルに格納され、
gethostbyname(3)
関数によって取得される。 名前解決は WINS サーバ経由か、ブロードキャストによって行われる。
.RE
.PP
passwd
.RS 4
ユーザ情報は、伝統的に
\fIpasswd(5)\fR
ファイルに格納され、
getpwent(3)
関数によって取得される。
.RE
.PP
group
.RS 4
グループ情報は、伝統的に
\fIgroup(5)\fR
ファイルに格納され、
getgrent(3)
関数によって取得される。
.RE
.PP
一例として、 以下のような簡単な設定を
\fI/etc/nsswitch\.conf\fR
ファイルに記述することで、 ユーザ情報やグループ情報は、最初に
\fI/etc/passwd\fR
や
\fI/etc/group\fR
ファイルから、ついで Windows NT サーバから取得される。
.sp
.RS 4
.nf
passwd:         files winbind
group:          files winbind
## IRIX においてのみ有効。hostを解決するためにwinbindを使う:
hosts:          files dns winbind
## その他のNSSが有効のシステムでは、以下のように libnss_wins\.soを使う:
hosts:          files dns wins
.fi
.RE
.PP
以下のような簡単な設定を
\fI/etc/nsswitch\.conf\fR
ファイルに記述することで、 ホスト名は、最初に
\fI/etc/hosts\fR
ファイルから、ついで WINS サーバから取得される。
.sp
.RS 4
.nf
hosts:		files wins
.fi
.RE
.SH "オプション"
.PP
\-F
.RS 4
このパラメータを指定すると、
winbindd
のメインプロセスがデーモンとして動作しなくなる。 つまり、 2 回の
fork(2)
と端末からの切り離しを行なわない。 接続要求を処理するための子プロセスは通常どおり生成されるが、 メインプロセスは終了しない。 この動作モードは、 Daniel J\. Bernstein 作の
daemontools
パッケージに含まれる
supervise
と
svscan
や、 AIX のプロセスモニタなどのプロセス監視機構配下で
winbindd
を動作させるためのものである。
.RE
.PP
\-S
.RS 4
このパラメータを指定すると、
winbindd
はファイルの代わりに標準出力にログを出力するようになる。
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
は0から10までの整数値である。 既定値の値は、パラメータが設定されていなければ0である。
.sp
この値を大きくするほど、サーバの動作に関するより詳細な情報が ログファイルに記録される。レベル 0 では、致命的なエラーと重大な警告 のみが記録される。レベル 1 は日々の運用に適しており、少量の稼働状況 に関する情報を生成する。
.sp
1 より上のレベルは大量のログが生成されるので、問題解決の時にのみ 使用すべきである。 3 より上のレベルは開発者だけが利用するように設計されて おり、莫大な量のログデータが生成される。そのほとんどは非常に謎めいた内容 となっている
.sp
このパラメータの指定は、\fIsmb\.conf\fRファイル中の、
\fI\%smb.conf.5.html#\fR
パラメータの 指定よりも優先する。
.RE
.PP
\-V
.RS 4
プログラムのバージョン番号を表示する。
.RE
.PP
\-s <configuration file>
.RS 4
サーバーが必要とする詳細な設定を含む設定ファイルを 指定する。このファイルには、サーバーが提供するサービスに関する記述や、 どの printcap ファイルを利用するかといった情報が含まれている。詳細は
\fIsmb\.conf\fR
を参照のこと。設定ファイルの名前の既定値は、コンパイル時 に決定される。
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
ログ/デバッグファイルのファイル名。拡張子として
\fB"\.progname"\fR
が追加される(例えば log\.smbclient, log\.smbd,など)。ログファイルはクライアントによって削除されることはない。
.RE
.PP
\-h|\-\-help
.RS 4
コマンドラインオプションの要約を表示する。
.RE
.PP
\-i
.RS 4

winbindd
にデーモンとしての動作と端末からの切り離しを行なわないように指示する。 このオプションは、
winbindd
の対話的なデバッグが必要な開発者のためのものである。 この際、\-S
パラメータが指定されたときと同じく、ログは標準出力に出力される。
.RE
.PP
\-n
.RS 4
キャッシュを無効にする。これにより、
winbindd
は、 クライアントに応答する前にドメインコントローラからの応答を毎回待たなければならず動作が遅くなるが、 キャッシュを使用しなくなるため、より厳密な結果を得られるようになる。 なお、ドメインコントローラが応答するまで
winbindd
は処理を停止してしまう。
.RE
.PP
\-Y
.RS 4
単一デーモンモード。
winbindd
は単一のプロセスだけで動作する (Samba 2\.2 での動作モード)。
winbindd
のデフォルトの動作では、 期限切れのキャッシュエントリの更新を行う子プロセスが起動される。
.RE
.SH "名前と ID の解決"
.PP
Windows NT サーバ上のユーザーとグループが作成された際には、全世界で一意な SID (セキュリティ識別子) が割り当てられる。 Windows NT のユーザとグループを UNIX のユーザとグループに変換するには、 SID とユーザ ID およびグループ ID 間のマッピングが必要となる。 これは
winbindd
が行なう作業の一つである。
.PP
winbindd のユーザとグループが解決される際に、 ユーザ ID とグループ ID が指定された範囲から割り当てられる。 ID は解決された順に順番に割り当てられるが、 クライアントがユーザやグループの列挙コマンドを実行すれば、存在するすべてのユーザとグループのマッピングが行われる。 割り当てられた UNIX 側の ID は、 Samba のロックディレクトリ配下のデータベースファイルに格納され、記憶される。
.PP
\fI警告:\fR
SID と UNIX の ID を変換するデータベース以外に winbindd がユーザとグループのマッピング情報を格納している場所はない。 このファイルが削除されたり壊れたりしてしまうと winbindd が、ユーザ ID やグループ ID と Windows NT のユーザあるいはグループの RID (訳注: SID) との対応を確認する手段はない。
.SH "設定"
.PP

winbindd
デーモンの設定は、
\fBsmb.conf\fR(5)
ファイルのパラメータで行う。 すべてのパラメータは、 smb\.conf の [global] セクション内に記述しなければならない。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIwinbind separator\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIidmap uid\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIidmap gid\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIidmap backend\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIwinbind cache time\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIwinbind enum users\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIwinbind enum groups\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fItemplate homedir\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fItemplate shell\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIwinbind use default domain\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIwinbind: rpc only\fR
このパラメータを設定すると、ドメインコントローラから情報を 検索するため、LDAPの変わりにwinbindがRPCを使うことを強制 する。
.SH "設定例"
.PP
ユーザとグループ名の解決と認証をドメインコントローラで行うには、 winbindd を以下のように設定する。 この設定例は、古いバージョンの Red Hat Linux で動作を確認した。
.PP
\fI/etc/nsswitch\.conf\fR
に以下の記述を行なう:
.sp
.RS 4
.nf
passwd: files winbind
group:  files winbind
.fi
.RE
.PP
\fI/etc/pam\.d/*\fR
内の
\fIauth\fR
行を以下のような設定に置き換える:
.sp
.RS 4
.nf
auth  required    /lib/security/pam_securetty\.so
auth  required	  /lib/security/pam_nologin\.so
auth  sufficient  /lib/security/pam_winbind\.so
auth  required    /lib/security/pam_unix\.so \e
                  use_first_pass shadow nullok
.fi
.RE
.sp
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
pam_unix PAM モジュールは、近年 pam_pwdb モジュールの代わりに用いられている。 Linux システムによっては、pam_unix の代わりに pam_unix2 モジュールが用いられている。
.PP
\fIsufficient\fR
キーワードと
\fIuse_first_pass\fR
キーワードを使用している点に注意すること。
.PP
ここで
\fIaccount\fR
行を以下の設定に置き換える:
.PP
account required /lib/security/pam_winbind\.so
.PP
次はドメインへの参加である。
net
プログラムを以下のように実行する:
.PP
net join \-S PDC \-U Administrator
.PP

\fI\-U\fR
に続くユーザ名は、 PDC 上で administrator 権限を持つドメインのユーザであれば誰でもよい。 「PDC」の部分は、実際の PDC の IP もしくは名前に置き換えること。
.PP
引き続き
\fIlibnss_winbind\.so\fR
を
\fI/lib\fR
に、
\fIpam_winbind\.so\fR
を
\fI/lib/security\fR
にコピーする。
\fI/lib/libnss_winbind\.so\fR
から
\fI/lib/libnss_winbind\.so\.2\fR
へのシンボリックリンクも用意する必要がある。 ただし古いバージョンの glibc を使用しているなら、 シンボリックリンク先は
\fI/lib/libnss_winbind\.so\.1\fR
にしなければならない。
.PP
最後に、
\fBsmb.conf\fR(5)
に以下のような設定を記述する:
.sp
.RS 4
.nf
[global]
	winbind separator = +
        winbind cache time = 10
        template shell = /bin/bash
        template homedir = /home/%D/%U
        idmap uid = 10000\-20000
        idmap gid = 10000\-20000
        workgroup = DOMAIN
        security = domain
        password server = *
.fi
.RE
.PP
ここで winbindd を起動すると、ユーザおよびグループの対応を行うデータベースが Windows NT のユーザとグループの情報を取り込むに従い、大きくなっていくのが確認できる。 また、「ドメイン名+ユーザー名」という形式でユーザ名を指定することで、 ドメインのユーザが UNIX にログインできることも確認できるだろう。
getent passwd
と
getent group
コマンドを実行すれば、 winbindd が正常に稼働していることを確認できる。
.SH "注意"
.PP
以下の注意点は、
winbindd
の設定や実行の際に有用である:
.PP

winbindd
が機能するには、同じマシン上で
\fBnmbd\fR(8)
を実行していなければならない。
.PP
PAM は非常に設定ミスを犯しやすい。 PAM の設定ファイルを変更する際は、 何を行なっているかをきちんと確認すること。 PAM の設定を誤ることで、 誰もシステムにログインできなくなってしまうこともあり得る。
.PP
複数の UNIX マシンで
winbindd
を実行した場合、一般的に winbindd によって割り当てられるユーザ ID とグループ ID はマシン毎に異なる。
\fI\%smb.conf.5.html#\fR
パラメータで、情報を共有する設定を行わない限り、 ユーザ ID とグループ ID はローカルマシン内でのみ有効である。
.PP
Windows NT の SID と UNIX のユーザ ID とグループ ID 間のマッピングファイルが壊れたりなくなったりすると、 マッピング情報は失われてしまう。
.SH "シグナル"
.PP
以下のシグナルによって
winbindd
デーモンを操作することが 可能である。
.PP
SIGHUP
.RS 4
\fBsmb.conf\fR(5)
ファイルを再読み込みさせ、 実行中の
winbindd
にパラメータの変更を反映させる。 このシグナルにより、 ユーザ情報とグループ情報のキャッシュもクリアされる。 また、winbindd が信頼するドメインの一覧も再取得される。
.RE
.PP
SIGUSR2
.RS 4
ステータス情報を
winbindd
のログファイルに書き込ませる。
.sp
ログファイルは、 log file パラメータで指定したファイルである。
.RE
.SH "ファイル"
.PP
\fI/etc/nsswitch\.conf(5)\fR
.RS 4
ネームサービススイッチの設定ファイル。
.RE
.PP
/tmp/\.winbindd/pipe
.RS 4
クライアントが
winbindd
と通信するための UNIX パイプ。 セキュリティ上の理由で、
\fI/tmp/\.winbindd\fR
ディレクトリと
\fI/tmp/\.winbindd/pipe\fR
ファイルの両方の所有者が root 以外の場合、クライアントは winbindd デーモンとの接続を行なわない。
.RE
.PP
$LOCKDIR/winbindd_privileged/pipe
.RS 4
winbind の「特権」クライアントが
winbindd
と通信するための UNIX パイプ。 セキュリティ上の理由で、 winbindd のいくつかの機能 (ntlm_auth
ユーティリティが必要とする機能など) へのアクセスは制限されており、 デフォルトでは、 「root」グループに属するユーザだけがアクセスできる。 管理者が $LOCKDIR/winbindd_privileged のグループパーミッションを変更することで、 「squid」などのプログラムが ntlm_auth を利用できるようにすることなどが可能である。
\fI$LOCKDIR/winbindd_privileged\fR
ディレクトリと
\fI$LOCKDIR/winbindd_privileged/pipe\fR
ファイルの両方の所有者が root 以外の場合、winbindクライアントは winbindd デーモンとの接続を行なわない事に注意。
.RE
.PP
/lib/libnss_winbind\.so\.X
.RS 4
ネームサービススイッチライブラリの実体。
.RE
.PP
$LOCKDIR/winbindd_idmap\.tdb
.RS 4
Windows NT の RID から UNIX の ユーザ/グループ ID へのマッピング情報の保管場所。 ロックディレクトリは、Samba のコンパイル時に
\fI\-\-with\-lockdir\fR
オプションを用いて指定する。 このディレクトリの既定値は
\fI/usr/local/samba/var/locks\fR
である。
.RE
.PP
$LOCKDIR/winbindd_cache\.tdb
.RS 4
キャッシュされたユーザ/グループ情報の保管場所。
.RE
.SH "バージョン"
.PP
このマニュアルは、Samba システムのバージョン 3 に適用される。
.SH "参照"
.PP
\fInsswitch\.conf(5)\fR,
\fBsamba\fR(7),
\fBwbinfo\fR(1),
\fBntlm_auth\fR(8),
\fBsmb.conf\fR(5),
\fBpam_winbind\fR(8)
.SH "著者"
.PP
オリジナルの Samba ソフトウェアと関連ユーティリティは、Andrew Tridgell によって作成された。現在 Samba は、Samba Team によって Linux カーネルの開発と同様に、オープンソースプロジェクトとして開発されている。
.PP
wbinfo
および
winbindd
コマンドは Tim Potter によって作成された。
.PP
Samba 2\.2 のための DocBook 形式への変換は Gerald Carter が行った。 Samba 3\.0 のための DocBook XML 4\.2 形式の変換は Alexander Bokovoy によって行われた。
.SH "日本語訳"
.PP
このマニュアルページは Samba 3\.3\.7 対応のものである。
.PP
このドキュメントの Samba 3\.0\.24 対応の翻訳は
.PP
たかはしもとのぶ (monyo@samba\.gr\.jp)
.PP
さとうふみやす
.sp
.RE
によって行なわれた。
.PP
このドキュメントの Samba 3\.2\.4\-3\.3\.7 対応の翻訳は 太田俊哉(ribbon@samba\.gr\.jp)によって行われた。
